{
  "formatVersion": "1.1",
  "component": {
    "group": "rs.whisker",
    "module": "whisker-runtime-android",
    "version": "0.1.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "rs.whisker",
          "module": "whisker-module-android",
          "version": {
            "requires": "0.1.15"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-base-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-trace-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-service-api-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "org.lynxsdk.lynx",
          "module": "primjs",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-runtime-android-0.1.15.aar",
          "url": "whisker-runtime-android-0.1.15.aar",
          "size": 12027,
          "sha512": "bd8151e561398d9ce5cb83df40eb4847c5fa53efa96f3b7fb3619513040f073b39d89793d4e80246d18ac0b0e3a46e6a97c070e47519a7df775a3d2f77fbbfae",
          "sha256": "fa308c5448293eb1309d60ae175b411d32775333c86289e886136264e9d3225c",
          "sha1": "bfe1873763085af38ed6309e3db8c3f4c7d8b6ab",
          "md5": "6334803ec6f90ecb898dee91910f8ed0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "rs.whisker",
          "module": "whisker-module-android",
          "version": {
            "requires": "0.1.15"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-base-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-trace-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-service-api-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "org.lynxsdk.lynx",
          "module": "primjs",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-runtime-android-0.1.15.aar",
          "url": "whisker-runtime-android-0.1.15.aar",
          "size": 12027,
          "sha512": "bd8151e561398d9ce5cb83df40eb4847c5fa53efa96f3b7fb3619513040f073b39d89793d4e80246d18ac0b0e3a46e6a97c070e47519a7df775a3d2f77fbbfae",
          "sha256": "fa308c5448293eb1309d60ae175b411d32775333c86289e886136264e9d3225c",
          "sha1": "bfe1873763085af38ed6309e3db8c3f4c7d8b6ab",
          "md5": "6334803ec6f90ecb898dee91910f8ed0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-runtime-android-0.1.15-sources.jar",
          "url": "whisker-runtime-android-0.1.15-sources.jar",
          "size": 9286,
          "sha512": "861b8d9bd1d25a9226d1495a80a1dcdc15ab64eab0846b981c586e5d4c70b88c952a5591e811d33d2911b92079c9deed4d1839f28daf1723e1d334de17338b39",
          "sha256": "9c6335b8cf8b14ee58f2edd5e8b8180cf666dc8b44277f99756c62d4f3cb8dd6",
          "sha1": "ff9dbc0f0122da7a1263e3f0fd890a48029c1d39",
          "md5": "41743bd8461daf19345aa915d11996c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-runtime-android-0.1.15-javadoc.jar",
          "url": "whisker-runtime-android-0.1.15-javadoc.jar",
          "size": 345301,
          "sha512": "5617277d8a878f7e1705eceb0efb6dd6a04c9c8a5e3ec44a24c64cdf287953d9a6a4574ede600b2dbd4df985c2d650a56e27a57efe9b68a1cd2be503239deec2",
          "sha256": "272b60eabf6ac9f2ec209c2938b628b5ce36eab5ab3f0158f3bfa781b23baa76",
          "sha1": "d3cee2787b58085cb35c40d81032540d6f67d1e8",
          "md5": "9d284afee3abdb21712700094ea480e7"
        }
      ]
    }
  ]
}
