{
  "formatVersion": "1.1",
  "component": {
    "group": "rs.whisker",
    "module": "whisker-module-android",
    "version": "0.1.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "rs.whisker",
          "module": "lynx-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-base-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-trace-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-service-api-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "org.lynxsdk.lynx",
          "module": "primjs",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-module-android-0.1.15.aar",
          "url": "whisker-module-android-0.1.15.aar",
          "size": 85116,
          "sha512": "902f90267c2240fa7dba7fd3396e24d9dde500419b3db45b52f49f363d6bc19bb0dac8ad1f89bcc1151549a687c3b9469c1146a0e35146b714fceda8e55de224",
          "sha256": "c3a222ac36bfb76d285f05907eb9faa9bd864e4cfcc6208e077136d4c831e7b9",
          "sha1": "484ef3b3906ba6e0752e555f209100cde3ef4a4d",
          "md5": "e36f5cd57d7138cf03bf84859536dffe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "rs.whisker",
          "module": "lynx-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-base-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-trace-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-service-api-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "org.lynxsdk.lynx",
          "module": "primjs",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-module-android-0.1.15.aar",
          "url": "whisker-module-android-0.1.15.aar",
          "size": 85116,
          "sha512": "902f90267c2240fa7dba7fd3396e24d9dde500419b3db45b52f49f363d6bc19bb0dac8ad1f89bcc1151549a687c3b9469c1146a0e35146b714fceda8e55de224",
          "sha256": "c3a222ac36bfb76d285f05907eb9faa9bd864e4cfcc6208e077136d4c831e7b9",
          "sha1": "484ef3b3906ba6e0752e555f209100cde3ef4a4d",
          "md5": "e36f5cd57d7138cf03bf84859536dffe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-module-android-0.1.15-sources.jar",
          "url": "whisker-module-android-0.1.15-sources.jar",
          "size": 27657,
          "sha512": "860496c920c2c04f105401213361435914a1cd48485ddd41067ab4daabdd8c43b03d6a06155fff29751f4dd240f34254b76a3b14c8ed71f264b1a4c1ed246f7e",
          "sha256": "9ccfc21cf19b42878fca18982e796e1184f34201db5cda681c39d16e5351a4e4",
          "sha1": "9a01f9e9e72dce78c162cf41fbd289a8c6a91381",
          "md5": "944e23b5efb370cab60fb0f31f6ea389"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-module-android-0.1.15-javadoc.jar",
          "url": "whisker-module-android-0.1.15-javadoc.jar",
          "size": 436986,
          "sha512": "04896fe49ea69f8284450794692521fe321016675305a8f8ffb48b8efc881894407279a6e613e6950970c0d2ccd6429fc0c74d1d3c62bfb01b9ee13aca04af29",
          "sha256": "0f0f954a30adf52a78f205873dfe20c266164ddbbc7db7ca0e50ca0ead105367",
          "sha1": "a3f64b317b801045e61864437ebb0fad98a34172",
          "md5": "aa119897814507d6cfd7760ff81c6c5a"
        }
      ]
    }
  ]
}
