// AUTO-GENERATED by whisker-cng. Do NOT edit — re-run
// `whisker run` to refresh.
//
// This is intentionally a plain Android application. The retained Rust
// renderer is connected in a later Host slice; bootstrapping the native shell
// must not pull the legacy Lynx SDK, bridge, or module code generation in.

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
{{extra_gradle_plugins}}
}

android {
    namespace = "{{android_application_id}}"
    compileSdk = {{android_target_sdk}}

    defaultConfig {
        applicationId = "{{android_application_id}}"
        minSdk = {{android_min_sdk}}
        targetSdk = {{android_target_sdk}}
        versionCode = {{build_number}}
        versionName = "{{version}}"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }

    val whiskerKeystore = System.getenv("WHISKER_ANDROID_KEYSTORE")
    if (whiskerKeystore != null) {
        signingConfigs {
            create("whiskerRelease") {
                storeFile = file(whiskerKeystore)
                storePassword = System.getenv("WHISKER_ANDROID_KEYSTORE_PASSWORD")
                keyAlias = System.getenv("WHISKER_ANDROID_KEY_ALIAS")
                keyPassword = System.getenv("WHISKER_ANDROID_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        getByName("debug") {
            isMinifyEnabled = false
        }
        getByName("release") {
            isMinifyEnabled = false
            if (whiskerKeystore != null) {
                signingConfig = signingConfigs.getByName("whiskerRelease")
            }
        }
    }
}

dependencies {
{{extra_gradle_dependencies}}
}
