{
  "formatVersion": "1.1",
  "component": {
    "group": "rs.whisker",
    "module": "ksp",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.5.jar",
          "url": "ksp-0.1.5.jar",
          "size": 11123,
          "sha512": "8cbec9532656cf30863cfb9a391aecc089b87242ff4327c6feae96cebecbd7a490b5d92610e25dd9b451cc284bc55d422cacfa5d0ea4e97632401c9e3afc5a32",
          "sha256": "7ec8c24c5a5c77935bd6fefb36fdbca6022578dd977b54c72a5e2ab125daca40",
          "sha1": "489ed6d06e381a04f2ccb4a7ed4a428737b26cfc",
          "md5": "b48918efd2bc10c328490e6f261aa8dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.0.21-1.0.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.5.jar",
          "url": "ksp-0.1.5.jar",
          "size": 11123,
          "sha512": "8cbec9532656cf30863cfb9a391aecc089b87242ff4327c6feae96cebecbd7a490b5d92610e25dd9b451cc284bc55d422cacfa5d0ea4e97632401c9e3afc5a32",
          "sha256": "7ec8c24c5a5c77935bd6fefb36fdbca6022578dd977b54c72a5e2ab125daca40",
          "sha1": "489ed6d06e381a04f2ccb4a7ed4a428737b26cfc",
          "md5": "b48918efd2bc10c328490e6f261aa8dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ksp-0.1.5-sources.jar",
          "url": "ksp-0.1.5-sources.jar",
          "size": 5750,
          "sha512": "18f3c850518b330a360eab0ef5f382ca61abc2fa45cf4950e12e0605d258f9d20231284de3fd2abfc29d306196f8bfab18c793126beb980f0b8a92e19c49540d",
          "sha256": "308c02f355a0e7347a1918edcf298e84df53ca392fa149a791a04cff864a6680",
          "sha1": "b214f9ae04d19bc1d193e26e18ad71cd46145d31",
          "md5": "2dbb3228dae64e4244a41426116b6099"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ksp-0.1.5-javadoc.jar",
          "url": "ksp-0.1.5-javadoc.jar",
          "size": 261,
          "sha512": "57991fe6441abb3525239cffc0eea5a5dc855d8e22c6820ad5717dac49986cb74de180697140f52f41f47a790ffa45b236f6faa9dc0c81b823f1bfc48bd1e069",
          "sha256": "8bddbfd7beb79f3a3113fa2c512050058cea521aad3a098bb0ce30472802bbdc",
          "sha1": "7246b68eab8b8d0193312cbf8890d4d4b11939a5",
          "md5": "d2b68f50ec901fc80fb270a043e23d1d"
        }
      ]
    }
  ]
}
