//! The 148 CSS named colors. Lynx accepts every keyword from the
//! CSS Color Module Level 4 named-color set.
//!
//! `transparent` is also a CSS named color, but Whisker exposes it
//! as [`Color::Transparent`](super::Color::Transparent) so the
//! `<color>` enum can branch on it without traversing this list.

#![allow(missing_docs)] // Each variant's name is its own documentation.

/// A CSS named color.
///
/// Serialized in lowercase to match the canonical CSS form.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum NamedColor {
    AliceBlue,
    AntiqueWhite,
    Aqua,
    Aquamarine,
    Azure,
    Beige,
    Bisque,
    Black,
    BlanchedAlmond,
    Blue,
    BlueViolet,
    Brown,
    BurlyWood,
    CadetBlue,
    Chartreuse,
    Chocolate,
    Coral,
    CornflowerBlue,
    Cornsilk,
    Crimson,
    Cyan,
    DarkBlue,
    DarkCyan,
    DarkGoldenRod,
    DarkGray,
    DarkGreen,
    DarkGrey,
    DarkKhaki,
    DarkMagenta,
    DarkOliveGreen,
    DarkOrange,
    DarkOrchid,
    DarkRed,
    DarkSalmon,
    DarkSeaGreen,
    DarkSlateBlue,
    DarkSlateGray,
    DarkSlateGrey,
    DarkTurquoise,
    DarkViolet,
    DeepPink,
    DeepSkyBlue,
    DimGray,
    DimGrey,
    DodgerBlue,
    FireBrick,
    FloralWhite,
    ForestGreen,
    Fuchsia,
    Gainsboro,
    GhostWhite,
    Gold,
    GoldenRod,
    Gray,
    Green,
    GreenYellow,
    Grey,
    HoneyDew,
    HotPink,
    IndianRed,
    Indigo,
    Ivory,
    Khaki,
    Lavender,
    LavenderBlush,
    LawnGreen,
    LemonChiffon,
    LightBlue,
    LightCoral,
    LightCyan,
    LightGoldenRodYellow,
    LightGray,
    LightGreen,
    LightGrey,
    LightPink,
    LightSalmon,
    LightSeaGreen,
    LightSkyBlue,
    LightSlateGray,
    LightSlateGrey,
    LightSteelBlue,
    LightYellow,
    Lime,
    LimeGreen,
    Linen,
    Magenta,
    Maroon,
    MediumAquaMarine,
    MediumBlue,
    MediumOrchid,
    MediumPurple,
    MediumSeaGreen,
    MediumSlateBlue,
    MediumSpringGreen,
    MediumTurquoise,
    MediumVioletRed,
    MidnightBlue,
    MintCream,
    MistyRose,
    Moccasin,
    NavajoWhite,
    Navy,
    OldLace,
    Olive,
    OliveDrab,
    Orange,
    OrangeRed,
    Orchid,
    PaleGoldenRod,
    PaleGreen,
    PaleTurquoise,
    PaleVioletRed,
    PapayaWhip,
    PeachPuff,
    Peru,
    Pink,
    Plum,
    PowderBlue,
    Purple,
    RebeccaPurple,
    Red,
    RosyBrown,
    RoyalBlue,
    SaddleBrown,
    Salmon,
    SandyBrown,
    SeaGreen,
    SeaShell,
    Sienna,
    Silver,
    SkyBlue,
    SlateBlue,
    SlateGray,
    SlateGrey,
    Snow,
    SpringGreen,
    SteelBlue,
    Tan,
    Teal,
    Thistle,
    Tomato,
    Turquoise,
    Violet,
    Wheat,
    White,
    WhiteSmoke,
    Yellow,
    YellowGreen,
}

impl NamedColor {
    /// The canonical lowercase CSS keyword for this color.
    pub fn name(self) -> &'static str {
        match self {
            NamedColor::AliceBlue => "aliceblue",
            NamedColor::AntiqueWhite => "antiquewhite",
            NamedColor::Aqua => "aqua",
            NamedColor::Aquamarine => "aquamarine",
            NamedColor::Azure => "azure",
            NamedColor::Beige => "beige",
            NamedColor::Bisque => "bisque",
            NamedColor::Black => "black",
            NamedColor::BlanchedAlmond => "blanchedalmond",
            NamedColor::Blue => "blue",
            NamedColor::BlueViolet => "blueviolet",
            NamedColor::Brown => "brown",
            NamedColor::BurlyWood => "burlywood",
            NamedColor::CadetBlue => "cadetblue",
            NamedColor::Chartreuse => "chartreuse",
            NamedColor::Chocolate => "chocolate",
            NamedColor::Coral => "coral",
            NamedColor::CornflowerBlue => "cornflowerblue",
            NamedColor::Cornsilk => "cornsilk",
            NamedColor::Crimson => "crimson",
            NamedColor::Cyan => "cyan",
            NamedColor::DarkBlue => "darkblue",
            NamedColor::DarkCyan => "darkcyan",
            NamedColor::DarkGoldenRod => "darkgoldenrod",
            NamedColor::DarkGray => "darkgray",
            NamedColor::DarkGreen => "darkgreen",
            NamedColor::DarkGrey => "darkgrey",
            NamedColor::DarkKhaki => "darkkhaki",
            NamedColor::DarkMagenta => "darkmagenta",
            NamedColor::DarkOliveGreen => "darkolivegreen",
            NamedColor::DarkOrange => "darkorange",
            NamedColor::DarkOrchid => "darkorchid",
            NamedColor::DarkRed => "darkred",
            NamedColor::DarkSalmon => "darksalmon",
            NamedColor::DarkSeaGreen => "darkseagreen",
            NamedColor::DarkSlateBlue => "darkslateblue",
            NamedColor::DarkSlateGray => "darkslategray",
            NamedColor::DarkSlateGrey => "darkslategrey",
            NamedColor::DarkTurquoise => "darkturquoise",
            NamedColor::DarkViolet => "darkviolet",
            NamedColor::DeepPink => "deeppink",
            NamedColor::DeepSkyBlue => "deepskyblue",
            NamedColor::DimGray => "dimgray",
            NamedColor::DimGrey => "dimgrey",
            NamedColor::DodgerBlue => "dodgerblue",
            NamedColor::FireBrick => "firebrick",
            NamedColor::FloralWhite => "floralwhite",
            NamedColor::ForestGreen => "forestgreen",
            NamedColor::Fuchsia => "fuchsia",
            NamedColor::Gainsboro => "gainsboro",
            NamedColor::GhostWhite => "ghostwhite",
            NamedColor::Gold => "gold",
            NamedColor::GoldenRod => "goldenrod",
            NamedColor::Gray => "gray",
            NamedColor::Green => "green",
            NamedColor::GreenYellow => "greenyellow",
            NamedColor::Grey => "grey",
            NamedColor::HoneyDew => "honeydew",
            NamedColor::HotPink => "hotpink",
            NamedColor::IndianRed => "indianred",
            NamedColor::Indigo => "indigo",
            NamedColor::Ivory => "ivory",
            NamedColor::Khaki => "khaki",
            NamedColor::Lavender => "lavender",
            NamedColor::LavenderBlush => "lavenderblush",
            NamedColor::LawnGreen => "lawngreen",
            NamedColor::LemonChiffon => "lemonchiffon",
            NamedColor::LightBlue => "lightblue",
            NamedColor::LightCoral => "lightcoral",
            NamedColor::LightCyan => "lightcyan",
            NamedColor::LightGoldenRodYellow => "lightgoldenrodyellow",
            NamedColor::LightGray => "lightgray",
            NamedColor::LightGreen => "lightgreen",
            NamedColor::LightGrey => "lightgrey",
            NamedColor::LightPink => "lightpink",
            NamedColor::LightSalmon => "lightsalmon",
            NamedColor::LightSeaGreen => "lightseagreen",
            NamedColor::LightSkyBlue => "lightskyblue",
            NamedColor::LightSlateGray => "lightslategray",
            NamedColor::LightSlateGrey => "lightslategrey",
            NamedColor::LightSteelBlue => "lightsteelblue",
            NamedColor::LightYellow => "lightyellow",
            NamedColor::Lime => "lime",
            NamedColor::LimeGreen => "limegreen",
            NamedColor::Linen => "linen",
            NamedColor::Magenta => "magenta",
            NamedColor::Maroon => "maroon",
            NamedColor::MediumAquaMarine => "mediumaquamarine",
            NamedColor::MediumBlue => "mediumblue",
            NamedColor::MediumOrchid => "mediumorchid",
            NamedColor::MediumPurple => "mediumpurple",
            NamedColor::MediumSeaGreen => "mediumseagreen",
            NamedColor::MediumSlateBlue => "mediumslateblue",
            NamedColor::MediumSpringGreen => "mediumspringgreen",
            NamedColor::MediumTurquoise => "mediumturquoise",
            NamedColor::MediumVioletRed => "mediumvioletred",
            NamedColor::MidnightBlue => "midnightblue",
            NamedColor::MintCream => "mintcream",
            NamedColor::MistyRose => "mistyrose",
            NamedColor::Moccasin => "moccasin",
            NamedColor::NavajoWhite => "navajowhite",
            NamedColor::Navy => "navy",
            NamedColor::OldLace => "oldlace",
            NamedColor::Olive => "olive",
            NamedColor::OliveDrab => "olivedrab",
            NamedColor::Orange => "orange",
            NamedColor::OrangeRed => "orangered",
            NamedColor::Orchid => "orchid",
            NamedColor::PaleGoldenRod => "palegoldenrod",
            NamedColor::PaleGreen => "palegreen",
            NamedColor::PaleTurquoise => "paleturquoise",
            NamedColor::PaleVioletRed => "palevioletred",
            NamedColor::PapayaWhip => "papayawhip",
            NamedColor::PeachPuff => "peachpuff",
            NamedColor::Peru => "peru",
            NamedColor::Pink => "pink",
            NamedColor::Plum => "plum",
            NamedColor::PowderBlue => "powderblue",
            NamedColor::Purple => "purple",
            NamedColor::RebeccaPurple => "rebeccapurple",
            NamedColor::Red => "red",
            NamedColor::RosyBrown => "rosybrown",
            NamedColor::RoyalBlue => "royalblue",
            NamedColor::SaddleBrown => "saddlebrown",
            NamedColor::Salmon => "salmon",
            NamedColor::SandyBrown => "sandybrown",
            NamedColor::SeaGreen => "seagreen",
            NamedColor::SeaShell => "seashell",
            NamedColor::Sienna => "sienna",
            NamedColor::Silver => "silver",
            NamedColor::SkyBlue => "skyblue",
            NamedColor::SlateBlue => "slateblue",
            NamedColor::SlateGray => "slategray",
            NamedColor::SlateGrey => "slategrey",
            NamedColor::Snow => "snow",
            NamedColor::SpringGreen => "springgreen",
            NamedColor::SteelBlue => "steelblue",
            NamedColor::Tan => "tan",
            NamedColor::Teal => "teal",
            NamedColor::Thistle => "thistle",
            NamedColor::Tomato => "tomato",
            NamedColor::Turquoise => "turquoise",
            NamedColor::Violet => "violet",
            NamedColor::Wheat => "wheat",
            NamedColor::White => "white",
            NamedColor::WhiteSmoke => "whitesmoke",
            NamedColor::Yellow => "yellow",
            NamedColor::YellowGreen => "yellowgreen",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn name_lookup_is_lowercase() {
        for c in ALL {
            assert!(c.name().chars().all(|ch| !ch.is_ascii_uppercase()));
        }
    }

    #[test]
    fn name_is_stable_for_each_variant() {
        assert_eq!(NamedColor::AliceBlue.name(), "aliceblue");
        assert_eq!(NamedColor::DodgerBlue.name(), "dodgerblue");
        assert_eq!(NamedColor::RebeccaPurple.name(), "rebeccapurple");
        assert_eq!(NamedColor::YellowGreen.name(), "yellowgreen");
    }

    // Exhaustive walk to keep coverage at 100%. If a new color is
    // added the array length will mismatch the match arm count and
    // both branches need updating.
    const ALL: &[NamedColor] = &[
        NamedColor::AliceBlue,
        NamedColor::AntiqueWhite,
        NamedColor::Aqua,
        NamedColor::Aquamarine,
        NamedColor::Azure,
        NamedColor::Beige,
        NamedColor::Bisque,
        NamedColor::Black,
        NamedColor::BlanchedAlmond,
        NamedColor::Blue,
        NamedColor::BlueViolet,
        NamedColor::Brown,
        NamedColor::BurlyWood,
        NamedColor::CadetBlue,
        NamedColor::Chartreuse,
        NamedColor::Chocolate,
        NamedColor::Coral,
        NamedColor::CornflowerBlue,
        NamedColor::Cornsilk,
        NamedColor::Crimson,
        NamedColor::Cyan,
        NamedColor::DarkBlue,
        NamedColor::DarkCyan,
        NamedColor::DarkGoldenRod,
        NamedColor::DarkGray,
        NamedColor::DarkGreen,
        NamedColor::DarkGrey,
        NamedColor::DarkKhaki,
        NamedColor::DarkMagenta,
        NamedColor::DarkOliveGreen,
        NamedColor::DarkOrange,
        NamedColor::DarkOrchid,
        NamedColor::DarkRed,
        NamedColor::DarkSalmon,
        NamedColor::DarkSeaGreen,
        NamedColor::DarkSlateBlue,
        NamedColor::DarkSlateGray,
        NamedColor::DarkSlateGrey,
        NamedColor::DarkTurquoise,
        NamedColor::DarkViolet,
        NamedColor::DeepPink,
        NamedColor::DeepSkyBlue,
        NamedColor::DimGray,
        NamedColor::DimGrey,
        NamedColor::DodgerBlue,
        NamedColor::FireBrick,
        NamedColor::FloralWhite,
        NamedColor::ForestGreen,
        NamedColor::Fuchsia,
        NamedColor::Gainsboro,
        NamedColor::GhostWhite,
        NamedColor::Gold,
        NamedColor::GoldenRod,
        NamedColor::Gray,
        NamedColor::Green,
        NamedColor::GreenYellow,
        NamedColor::Grey,
        NamedColor::HoneyDew,
        NamedColor::HotPink,
        NamedColor::IndianRed,
        NamedColor::Indigo,
        NamedColor::Ivory,
        NamedColor::Khaki,
        NamedColor::Lavender,
        NamedColor::LavenderBlush,
        NamedColor::LawnGreen,
        NamedColor::LemonChiffon,
        NamedColor::LightBlue,
        NamedColor::LightCoral,
        NamedColor::LightCyan,
        NamedColor::LightGoldenRodYellow,
        NamedColor::LightGray,
        NamedColor::LightGreen,
        NamedColor::LightGrey,
        NamedColor::LightPink,
        NamedColor::LightSalmon,
        NamedColor::LightSeaGreen,
        NamedColor::LightSkyBlue,
        NamedColor::LightSlateGray,
        NamedColor::LightSlateGrey,
        NamedColor::LightSteelBlue,
        NamedColor::LightYellow,
        NamedColor::Lime,
        NamedColor::LimeGreen,
        NamedColor::Linen,
        NamedColor::Magenta,
        NamedColor::Maroon,
        NamedColor::MediumAquaMarine,
        NamedColor::MediumBlue,
        NamedColor::MediumOrchid,
        NamedColor::MediumPurple,
        NamedColor::MediumSeaGreen,
        NamedColor::MediumSlateBlue,
        NamedColor::MediumSpringGreen,
        NamedColor::MediumTurquoise,
        NamedColor::MediumVioletRed,
        NamedColor::MidnightBlue,
        NamedColor::MintCream,
        NamedColor::MistyRose,
        NamedColor::Moccasin,
        NamedColor::NavajoWhite,
        NamedColor::Navy,
        NamedColor::OldLace,
        NamedColor::Olive,
        NamedColor::OliveDrab,
        NamedColor::Orange,
        NamedColor::OrangeRed,
        NamedColor::Orchid,
        NamedColor::PaleGoldenRod,
        NamedColor::PaleGreen,
        NamedColor::PaleTurquoise,
        NamedColor::PaleVioletRed,
        NamedColor::PapayaWhip,
        NamedColor::PeachPuff,
        NamedColor::Peru,
        NamedColor::Pink,
        NamedColor::Plum,
        NamedColor::PowderBlue,
        NamedColor::Purple,
        NamedColor::RebeccaPurple,
        NamedColor::Red,
        NamedColor::RosyBrown,
        NamedColor::RoyalBlue,
        NamedColor::SaddleBrown,
        NamedColor::Salmon,
        NamedColor::SandyBrown,
        NamedColor::SeaGreen,
        NamedColor::SeaShell,
        NamedColor::Sienna,
        NamedColor::Silver,
        NamedColor::SkyBlue,
        NamedColor::SlateBlue,
        NamedColor::SlateGray,
        NamedColor::SlateGrey,
        NamedColor::Snow,
        NamedColor::SpringGreen,
        NamedColor::SteelBlue,
        NamedColor::Tan,
        NamedColor::Teal,
        NamedColor::Thistle,
        NamedColor::Tomato,
        NamedColor::Turquoise,
        NamedColor::Violet,
        NamedColor::Wheat,
        NamedColor::White,
        NamedColor::WhiteSmoke,
        NamedColor::Yellow,
        NamedColor::YellowGreen,
    ];

    #[test]
    fn total_count_is_148() {
        assert_eq!(ALL.len(), 148);
    }
}
