// swift-tools-version:5.9
//
// Remote-consumable iOS module API. The application-owned WhiskerView and
// per-app Rust runtime are generated by `whisker run`; no renderer binary is
// shipped through SwiftPM.

import PackageDescription
import CompilerPluginSupport

let package = Package(
    name: "Whisker",
    platforms: [.iOS(.v13), .macOS(.v13)],
    products: [
        .library(name: "WhiskerModule", targets: ["WhiskerModule"]),
        .plugin(
            name: "WhiskerModuleCodegenPlugin",
            targets: ["WhiskerModuleCodegenPlugin"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/swiftlang/swift-syntax.git", from: "510.0.0"),
    ],
    targets: [
        .systemLibrary(
            name: "WhiskerCBridge",
            path: "platforms/ios/Sources/WhiskerCBridge/include"
        ),
        .macro(
            name: "WhiskerModuleMacros",
            dependencies: [
                .product(name: "SwiftCompilerPlugin", package: "swift-syntax"),
                .product(name: "SwiftSyntax", package: "swift-syntax"),
                .product(name: "SwiftSyntaxMacros", package: "swift-syntax"),
            ],
            path: "platforms/ios/macros/Sources/WhiskerModuleMacros"
        ),
        .target(
            name: "WhiskerModule",
            dependencies: ["WhiskerCBridge", "WhiskerModuleMacros"],
            path: "platforms/ios/Sources/WhiskerModule"
        ),
        .target(
            name: "WhiskerIOSHost",
            dependencies: ["WhiskerModule"],
            path: "crates/whisker-cng/src/templates/ios/Sources",
            exclude: ["AppDelegate.swift"],
            sources: ["WhiskerView.swift"],
            swiftSettings: [.define("WHISKER_HOST_CONFORMANCE")]
        ),
        .target(
            name: "WhiskerHostConformanceStubs",
            path: "tests/host-conformance/runners/ios/Stubs"
        ),
        .testTarget(
            name: "WhiskerIOSHostConformanceTests",
            dependencies: [
                "WhiskerIOSHost",
                "WhiskerModule",
                "WhiskerCBridge",
                "WhiskerHostConformanceStubs",
            ],
            path: "tests/host-conformance/runners/ios/Tests"
        ),
        .executableTarget(
            name: "WhiskerModuleCodegen",
            dependencies: [
                .product(name: "SwiftSyntax", package: "swift-syntax"),
                .product(name: "SwiftParser", package: "swift-syntax"),
            ],
            path: "platforms/ios/macros/Sources/WhiskerModuleCodegen"
        ),
        .plugin(
            name: "WhiskerModuleCodegenPlugin",
            capability: .buildTool(),
            dependencies: ["WhiskerModuleCodegen"],
            path: "platforms/ios/macros/Plugins/WhiskerModuleCodegenPlugin"
        ),
    ]
)
