//! `whisker-icons` example app.
//!
//! Renders every Lucide icon (~1700) in a 4-column flex-wrap
//! grid so the codegen + display-list pipeline gets exercised
//! end-to-end against the full upstream set. The grid body is
//! generated by the example's `build.rs` from
//! `../vendor/lucide/icons/*.svg` and `include!()`'d here at
//! module level — see `build.rs` for the design notes on why a
//! macro-time fan-out (vs a runtime `list(each: …)`) is the only
//! reachable path for a multi-column gallery today.

use whisker::prelude::*;
use whisker::runtime::view::Element;
use whisker_icons::{Icon, IconProps};

// Brings `pub const ICON_COUNT: usize` and `pub fn icons_grid()`
// into this module's namespace. See the generated `gallery.rs`.
include!(concat!(env!("OUT_DIR"), "/gallery.rs"));

const BG: &str = "#101012";
const CARD_BG: &str = "#1c1c1f";
const FG: &str = "#f0f0f3";

#[whisker::main]
pub fn app() -> Element {
    let page_style = format!(
        "background-color: {BG}; flex-grow: 1; flex-shrink: 1; \
         display: flex; flex-direction: column; \
         padding-top: 48px; padding-bottom: 24px;",
    );
    let header_style = format!(
        "color: {FG}; font-size: 22px; font-weight: 700; \
         margin-left: 20px; margin-bottom: 16px;",
    );
    let header_text = format!("lucide gallery (all {ICON_COUNT})");

    // The header sits outside the scroll-view so it stays pinned;
    // the grid is the only scrollable region. `flex-grow: 1` on the
    // scroll-view makes it claim whatever vertical space the page
    // has left after the header lays out — needed because Lynx's
    // `<scroll-view>` only scrolls within its own bounded height.
    let scroll_style =
        "flex-grow: 1; flex-shrink: 1; flex-basis: 0; width: 100%;".to_string();

    render! {
        page(style: page_style) {
            text(style: header_style, value: header_text)
            scroll_view(style: scroll_style) {
                IconsGridWrapper()
            }
        }
    }
}

/// Thin component wrapper so the build-time-generated
/// `icons_grid()` (which calls `render!` internally with all 1700
/// tiles inline) can be invoked from inside the outer `render!`.
/// `render!` only accepts component-style invocations as children,
/// not bare function calls, so the wrapper provides that shape.
#[component]
fn icons_grid_wrapper() -> Element {
    icons_grid()
}

/// One labelled tile. Reused for every icon. The macro-generated
/// `icons_grid()` calls this 1700 times with each Lucide const.
#[component]
fn tile(label: &'static str, svg: &'static str) -> Element {
    // 25% width per tile = 4 columns. Each tile owns its inner
    // padding so the 4-up wrap stays even across rows.
    let card_style = "width: 25%; \
                      display: flex; flex-direction: column; align-items: center; \
                      padding: 8px;"
        .to_string();
    let frame_style = format!(
        "width: 56px; height: 56px; \
         background-color: {CARD_BG}; \
         border-radius: 10px; \
         display: flex; align-items: center; justify-content: center;",
    );
    let caption_style = format!(
        "color: {FG}; font-size: 9px; margin-top: 4px; \
         text-align: center;",
    );

    render! {
        view(style: card_style) {
            view(style: frame_style) {
                Icon(svg: svg, color: FG, size: "28")
            }
            text(style: caption_style, value: label)
        }
    }
}
