//! FFI bindings to the C++ bridge that fronts Lynx Element PAPI.
//!
//! The bridge lives in `native/bridge/` and exposes a stable C ABI
//! (see `native/bridge/include/flint_bridge.h`). This crate will eventually
//! contain `bindgen`-generated raw bindings plus safe Rust wrappers.
//!
//! For now the module is empty — bindings are generated by `build.rs`
//! once the bridge is implemented.
