//! Build-time codegen for Lucide icons.
//!
//! Walks `vendor/lucide/icons/*.svg`, normalises each file's
//! whitespace so the multi-line attribute syntax Lucide uses
//! collapses into a single roxmltree-friendly line, and emits a
//! `pub const PascalCase: &str = "<svg …>…</svg>";` line per icon
//! into `$OUT_DIR/lucide_consts.rs`.
//!
//! The library's `lib.rs` `include!()`s the generated file as the
//! body of `pub mod lucide`. Each const is independent — the linker
//! drops the bytes of any icon the consumer doesn't reference, so a
//! binary that uses 5 icons only pays for those 5.
//!
//! ## Why bake the wrapper into every const
//!
//! An earlier draft stripped the common Lucide `<svg …>` wrapper
//! and re-synthesised it at runtime in the `Icon` component. That
//! cut generated source ~10x, but coupled `Icon` to Lucide's exact
//! attribute set — meaning a future Heroicons / Phosphor backend
//! would need its own component. Keeping the wrapper per-const
//! makes `Icon` a pure `Svg` forwarder and lets new icon sets
//! plug in by emitting their own constants in their own module.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let vendor_dir = PathBuf::from("vendor/lucide/icons");
    println!("cargo:rerun-if-changed=vendor/lucide/icons");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let out_path = out_dir.join("lucide_consts.rs");

    let mut entries: Vec<_> = fs::read_dir(&vendor_dir)
        .unwrap_or_else(|e| {
            panic!(
                "failed to read {}: {e}. Did `vendor/lucide` get clobbered?",
                vendor_dir.display()
            )
        })
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().and_then(|s| s.to_str()) == Some("svg"))
        .collect();
    entries.sort_by_key(|e| e.path());

    let mut out = String::new();
    out.push_str("// @generated by build.rs from vendor/lucide/icons/*.svg.\n");
    out.push_str("// Do not edit by hand — re-run `cargo build` to regenerate.\n\n");

    for entry in &entries {
        let path = entry.path();
        let stem = path
            .file_stem()
            .expect("svg filename has stem")
            .to_string_lossy()
            .into_owned();
        let name = pascal_case(&stem);
        let svg =
            fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let normalised = normalise(&svg);
        out.push_str(&format!(
            "/// Lucide [`{stem}`](https://lucide.dev/icons/{stem}).\n"
        ));
        out.push_str(&format!("pub const {name}: &str = {normalised:?};\n"));
    }

    fs::write(&out_path, out).unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));
}

/// `chevron-right` → `ChevronRight`. Lucide names are pure
/// kebab-case ASCII (no digits at the start, no underscores) so the
/// rule is straightforward — capitalise after every hyphen.
fn pascal_case(kebab: &str) -> String {
    let mut s = String::with_capacity(kebab.len());
    let mut next_upper = true;
    for c in kebab.chars() {
        if c == '-' {
            next_upper = true;
        } else if next_upper {
            for u in c.to_uppercase() {
                s.push(u);
            }
            next_upper = false;
        } else {
            s.push(c);
        }
    }
    s
}

/// Lucide ships SVGs with each attribute on its own line:
///
/// ```svg
/// <svg
///   xmlns="..."
///   viewBox="0 0 24 24"
/// >
///   <path d="m9 18 6-6-6-6" />
/// </svg>
/// ```
///
/// Whisker-svg's `roxmltree`-based parser accepts that as-is, but
/// the multi-line form bloats the resulting `pub const` strings
/// with newlines + per-line indentation. Trim each line and join
/// with a single space — preserves valid XML (the space between
/// `>` `<` is just an inter-tag text node, which roxmltree
/// ignores) and shrinks each icon string by ~60%.
fn normalise(svg: &str) -> String {
    svg.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty())
        .collect::<Vec<_>>()
        .join(" ")
}
