//! Build-time codegen for Lucide icons.
//!
//! Walks `vendor/lucide/icons/*.svg`, normalises each file's
//! whitespace so the multi-line attribute syntax Lucide uses
//! collapses into a single roxmltree-friendly line, and emits a
//! `pub const PascalCase: &str = "<svg …>…</svg>";` line per icon
//! into `$OUT_DIR/lucide_consts.rs`.
//!
//! The library's `lib.rs` `include!()`s the generated file as the
//! body of `pub mod lucide`. Each const is independent — the linker
//! drops the bytes of any icon the consumer doesn't reference, so a
//! binary that uses 5 icons only pays for those 5.
//!
//! Each const carries the full `<svg …>` wrapper rather than just the
//! inner shapes: ~10x more generated source, but it keeps `Icon` a pure
//! `Svg` forwarder instead of coupling it to Lucide's attribute set, so
//! another icon set can plug in by emitting its own constants.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let vendor_dir = PathBuf::from("vendor/lucide/icons");
    println!("cargo:rerun-if-changed=vendor/lucide/icons");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let out_path = out_dir.join("lucide_consts.rs");

    let mut entries: Vec<_> = fs::read_dir(&vendor_dir)
        .unwrap_or_else(|e| {
            panic!(
                "failed to read {}: {e}. Did `vendor/lucide` get clobbered?",
                vendor_dir.display()
            )
        })
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().and_then(|s| s.to_str()) == Some("svg"))
        .collect();
    entries.sort_by_key(|e| e.path());

    let mut out = String::new();
    out.push_str("// @generated by build.rs from vendor/lucide/icons/*.svg.\n");
    out.push_str("// Do not edit by hand — re-run `cargo build` to regenerate.\n\n");

    for entry in &entries {
        let path = entry.path();
        let stem = path
            .file_stem()
            .expect("svg filename has stem")
            .to_string_lossy()
            .into_owned();
        let name = pascal_case(&stem);
        let svg =
            fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let normalised = normalise(&svg);
        out.push_str(&format!(
            "/// Lucide [`{stem}`](https://lucide.dev/icons/{stem}).\n"
        ));
        out.push_str(&format!("pub const {name}: &str = {normalised:?};\n"));
    }

    fs::write(&out_path, out).unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));
}

/// `chevron-right` → `ChevronRight`. Lucide names are pure
/// kebab-case ASCII (no digits at the start, no underscores) so the
/// rule is straightforward — capitalise after every hyphen.
fn pascal_case(kebab: &str) -> String {
    let mut s = String::with_capacity(kebab.len());
    let mut next_upper = true;
    for c in kebab.chars() {
        if c == '-' {
            next_upper = true;
        } else if next_upper {
            for u in c.to_uppercase() {
                s.push(u);
            }
            next_upper = false;
        } else {
            s.push(c);
        }
    }
    s
}

/// Collapse Lucide's one-attribute-per-line SVGs onto a single line,
/// shrinking each generated `pub const` by ~60%. Joining with a space
/// keeps the XML valid — the space between `>` and `<` is an inter-tag
/// text node roxmltree ignores.
fn normalise(svg: &str) -> String {
    svg.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty())
        .collect::<Vec<_>>()
        .join(" ")
}
