{
  "formatVersion": "1.1",
  "component": {
    "group": "rs.whisker",
    "module": "whisker-module-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "rs.whisker",
          "module": "lynx-android",
          "version": {
            "requires": "3.8.0-whisker.10"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-base-android",
          "version": {
            "requires": "3.8.0-whisker.10"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-trace-android",
          "version": {
            "requires": "3.8.0-whisker.10"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-service-api-android",
          "version": {
            "requires": "3.8.0-whisker.10"
          }
        },
        {
          "group": "org.lynxsdk.lynx",
          "module": "primjs",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-module-android-0.1.4.aar",
          "url": "whisker-module-android-0.1.4.aar",
          "size": 75190,
          "sha512": "dae02ead0a21092158f4526ac0b2b951037a3f42e7923d142bd6976626ff0025cadf8af451323b536d03cbe2b31645226851879931b2bf650e6f85d09e659ba2",
          "sha256": "29996d71a211706b028fd3912e11fdc2b9caebbdee182eba2c2b4fbd0a2287ad",
          "sha1": "ce75cb7d632ce82471655267383e010cca65e416",
          "md5": "69051d62cff6c44023a47fdd9bc044cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "rs.whisker",
          "module": "lynx-android",
          "version": {
            "requires": "3.8.0-whisker.10"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-base-android",
          "version": {
            "requires": "3.8.0-whisker.10"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-trace-android",
          "version": {
            "requires": "3.8.0-whisker.10"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-service-api-android",
          "version": {
            "requires": "3.8.0-whisker.10"
          }
        },
        {
          "group": "org.lynxsdk.lynx",
          "module": "primjs",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-module-android-0.1.4.aar",
          "url": "whisker-module-android-0.1.4.aar",
          "size": 75190,
          "sha512": "dae02ead0a21092158f4526ac0b2b951037a3f42e7923d142bd6976626ff0025cadf8af451323b536d03cbe2b31645226851879931b2bf650e6f85d09e659ba2",
          "sha256": "29996d71a211706b028fd3912e11fdc2b9caebbdee182eba2c2b4fbd0a2287ad",
          "sha1": "ce75cb7d632ce82471655267383e010cca65e416",
          "md5": "69051d62cff6c44023a47fdd9bc044cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-module-android-0.1.4-sources.jar",
          "url": "whisker-module-android-0.1.4-sources.jar",
          "size": 22841,
          "sha512": "fda4ff3ecdea5ae829eba8e4965f02362999a245aa4c3191523d035251f15e6b6762004ba9132359cc568b4623eeff7ea33475dbd8ad04512d5b97e275cb1154",
          "sha256": "686e4e9f36eecddd184761a9542df7968765c70a0a90fa501019c55d3942ad78",
          "sha1": "b5fb0455a04e8af315e085afeb60f96a0a33662e",
          "md5": "636f330c1a81506155eb602780410bc7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-module-android-0.1.4-javadoc.jar",
          "url": "whisker-module-android-0.1.4-javadoc.jar",
          "size": 419245,
          "sha512": "9c57d63f79c3fe985f4b88b6bc85f1823e537b0726610e1d2d25c3a408b34114a0926bf5ce2d505f3fe3ddf1ae75ef995778db48d8e772ce17134b678d599ca0",
          "sha256": "96845fd91e0376f0c0f5341f363925037f151c1a173c6d9b9f57e5bdeb5a50a2",
          "sha1": "bb4bc3e4cd77690f068c20097d48c21a9b6101cf",
          "md5": "c115cb41124db78ac31caad50132aaab"
        }
      ]
    }
  ]
}
