{
  "formatVersion": "1.1",
  "component": {
    "group": "rs.whisker",
    "module": "whisker-module-android",
    "version": "0.1.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "rs.whisker",
          "module": "lynx-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-base-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-trace-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-service-api-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "org.lynxsdk.lynx",
          "module": "primjs",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-module-android-0.1.14.aar",
          "url": "whisker-module-android-0.1.14.aar",
          "size": 80240,
          "sha512": "173a77f956e97ccd41c5fd3795182b5f0d53436f799752ef52b178fea5ad71ca67af6d0fd5044de794d5f20cb9b1ad2437d60bcf1a5710f453acdfe20bb58f44",
          "sha256": "3d42530437bc70a23d9efab3fd0ab02022ffaac738db05ce64bbe35a37a7bf9c",
          "sha1": "a2baec1b96a714bae2bc374bfe7119052323d318",
          "md5": "2110a2a296b8074f3dea1b58fe71bdb3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "rs.whisker",
          "module": "lynx-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-base-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-trace-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-service-api-android",
          "version": {
            "requires": "3.8.0-whisker.13"
          }
        },
        {
          "group": "org.lynxsdk.lynx",
          "module": "primjs",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-module-android-0.1.14.aar",
          "url": "whisker-module-android-0.1.14.aar",
          "size": 80240,
          "sha512": "173a77f956e97ccd41c5fd3795182b5f0d53436f799752ef52b178fea5ad71ca67af6d0fd5044de794d5f20cb9b1ad2437d60bcf1a5710f453acdfe20bb58f44",
          "sha256": "3d42530437bc70a23d9efab3fd0ab02022ffaac738db05ce64bbe35a37a7bf9c",
          "sha1": "a2baec1b96a714bae2bc374bfe7119052323d318",
          "md5": "2110a2a296b8074f3dea1b58fe71bdb3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-module-android-0.1.14-sources.jar",
          "url": "whisker-module-android-0.1.14-sources.jar",
          "size": 25564,
          "sha512": "8804ab2154229dcd9ab7d3864194d65d5d4f1c41b12ab6f3f4f48ef651aadc41833a5a2db64eb24839e4dab2803bceac033ade998fbe26036dca14f0b1d83648",
          "sha256": "b68c49800cfe431a85961180d9f89794a0a7de1f880ab92f97fc874edf0a89e0",
          "sha1": "1ad8bc8944df335f442d6037b31cf834a495aca7",
          "md5": "567b5edc392f52f5cfc3cd9b9b3d5e26"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-module-android-0.1.14-javadoc.jar",
          "url": "whisker-module-android-0.1.14-javadoc.jar",
          "size": 428312,
          "sha512": "92d17261bebc0bfb9b87b0e4d825125e06eab19e33694b3976e478f6f8f51c42f309a8f8d87dbec5d464a13557a495b439b41de3d11583edeba9261e62fffb2c",
          "sha256": "709857704a85b1677fd48fb54dab93ca5ab3a66fa020e11a94ac5490e6bf005e",
          "sha1": "46388cb205d860bb28c41b1a4501adaa23da1fc3",
          "md5": "aa99b8acaec18363a80763d9e1a2ee82"
        }
      ]
    }
  ]
}
