// Generated by whisker-cng. Edit whisker.rs, not this file.

use wasm_bindgen::prelude::*;

#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    whisker_web::run_with_application_hash(
        whisker_web::WebAppConfig::new({{app_title_rust}}){{element_module_config}},
        whisker_app::__whisker_application,
        whisker_app::__whisker_application_hash,
    )
    .map_err(|error| JsValue::from_str(&error.to_string()))
}

#[cfg(feature = "hot-reload")]
#[wasm_bindgen]
pub fn __whisker_apply_hot_patch(header: &str, patch: Vec<u8>) -> Result<(), JsValue> {
    whisker_web::apply_hot_patch(
        header,
        &patch,
        whisker_app::__whisker_application,
        whisker_app::__whisker_application_hash,
    )
    .map_err(|error| JsValue::from_str(&error.to_string()))
}
