{
  "formatVersion": "1.1",
  "component": {
    "group": "rs.whisker",
    "module": "whisker-runtime-android",
    "version": "0.1.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "rs.whisker",
          "module": "whisker-module-android",
          "version": {
            "requires": "0.1.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-runtime-android-0.1.23.aar",
          "url": "whisker-runtime-android-0.1.23.aar",
          "size": 243942,
          "sha512": "18e282c6bb05e68def1fc2427778626f171613aeebbddbd20add412be8f94bb6576f24701b17df2ec2e088b33a011ef12077467e2805501de9cd0a97912e2e50",
          "sha256": "3359faa1e9722371e4d74705874338444ba11093674205a9f85fc2e72b641777",
          "sha1": "7e235d3da9c7d367ad18afe7eed4185c58dc0b75",
          "md5": "a3bdc27c97965a1be56273ddf2b00915"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "rs.whisker",
          "module": "whisker-module-android",
          "version": {
            "requires": "0.1.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-runtime-android-0.1.23.aar",
          "url": "whisker-runtime-android-0.1.23.aar",
          "size": 243942,
          "sha512": "18e282c6bb05e68def1fc2427778626f171613aeebbddbd20add412be8f94bb6576f24701b17df2ec2e088b33a011ef12077467e2805501de9cd0a97912e2e50",
          "sha256": "3359faa1e9722371e4d74705874338444ba11093674205a9f85fc2e72b641777",
          "sha1": "7e235d3da9c7d367ad18afe7eed4185c58dc0b75",
          "md5": "a3bdc27c97965a1be56273ddf2b00915"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-runtime-android-0.1.23-sources.jar",
          "url": "whisker-runtime-android-0.1.23-sources.jar",
          "size": 58177,
          "sha512": "bbd65888ed7d46eaaecc6e3fe82f540f57861b9cbdf4827739c89c2e97ebc0b70560422b0b0e93ad1dd9356cbfae750dd715c63b551e41f72011eddea1299c50",
          "sha256": "5a33a7c6c9e5a32104cc2babe85cb94e03869c775f4e4553669cac22ac59e3b4",
          "sha1": "5f3f6303223b6362f520f2d6f1b246b6b49f18bc",
          "md5": "f4672cd4ce4cba06563add46147b4c55"
        }
      ]
    }
  ]
}
