// `whisker-elements-codegen` — Swift executable that scans .swift
// source files for `@WhiskerElement("x-tag")` applications and emits
// `WhiskerModuleBehaviors.swift` containing the matching
// `LynxComponentRegistry.registerUI(...)` calls.
//
// Invoked at SwiftPM build time by `WhiskerElementsCodegenPlugin`
// (under `../../Plugins/`). The plugin passes:
//   --output <path>             ← target for the generated .swift
//   <input1.swift> <input2.swift> …
//
// Apple's SwiftSyntax parses each input file into an AST; we walk
// it to find any class declaration carrying a `@WhiskerElement`
// attribute, pull the string literal argument, and produce one
// registration line per match.
//
// Companion of `WhiskerElementProcessor.kt` (Android KSP). Same
// shape — annotation in, generated registry out. Apple's
// SwiftSyntax is the iOS equivalent of KSP's `Resolver`.

import Foundation
import SwiftSyntax
import SwiftParser

// ---- CLI argument parsing ----------------------------------------------------

struct Args {
    let outputPath: String
    let inputs: [String]
}

func parseArgs(_ argv: [String]) -> Args? {
    var output: String?
    var inputs: [String] = []
    var i = 1 // skip argv[0]
    while i < argv.count {
        switch argv[i] {
        case "--output":
            guard i + 1 < argv.count else { return nil }
            output = argv[i + 1]
            i += 2
        default:
            inputs.append(argv[i])
            i += 1
        }
    }
    guard let output else { return nil }
    return Args(outputPath: output, inputs: inputs)
}

// ---- AST walker --------------------------------------------------------------

/// One discovered `(tag, className)` pair. `className` is the bare
/// Swift class name as written; the generated registry's
/// `NSClassFromString` lookup applies both the `WhiskerModules.`
/// SwiftPM-target prefix AND the bare name (to support authors
/// who add their own `@objc(BareName)`).
struct Hit {
    let tag: String
    let className: String
}

final class WhiskerElementCollector: SyntaxVisitor {
    var hits: [Hit] = []

    override func visit(_ node: ClassDeclSyntax) -> SyntaxVisitorContinueKind {
        for attribute in node.attributes {
            guard let attr = attribute.as(AttributeSyntax.self) else { continue }
            // The attribute name appears as a single
            // `IdentifierTypeSyntax` for `@WhiskerElement` —
            // skip qualified-name spellings for now (rare).
            guard let attrName = attr.attributeName.as(IdentifierTypeSyntax.self) else { continue }
            guard attrName.name.text == "WhiskerElement" else { continue }
            guard let args = attr.arguments?.as(LabeledExprListSyntax.self) else { continue }
            guard let first = args.first else { continue }
            guard let strLit = first.expression.as(StringLiteralExprSyntax.self) else { continue }
            guard strLit.segments.count == 1 else { continue }
            guard let seg = strLit.segments.first?.as(StringSegmentSyntax.self) else { continue }
            let tag = seg.content.text
            let className = node.name.text
            hits.append(Hit(tag: tag, className: className))
        }
        return .skipChildren
    }
}

// ---- Codegen -----------------------------------------------------------------

func render(hits: [Hit]) -> String {
    // Deterministic order — sort by tag so two builds with the
    // same input produce byte-identical output (helps SwiftPM's
    // incremental-rebuild fingerprinting).
    let sorted = hits.sorted { $0.tag < $1.tag }

    var out = """
        // AUTO-GENERATED by `whisker-elements-codegen` (SwiftPM build plugin).
        // DO NOT EDIT — re-runs automatically on next `swift build`.
        //
        // Sourced from every `@WhiskerElement("x-tag")` application in
        // the WhiskerModules SwiftPM target's source set — i.e. every
        // module crate's `[ios].swift_sources` staged into
        // `gen/ios/whisker_modules/Sources/WhiskerModules/<crate>/`.
        //
        // Sibling of Android's `rs.whisker.ksp.WhiskerElementProcessor`
        // (under `packages/whisker-android-ksp/`).
        //
        // Generated count: \(sorted.count)

        import Foundation
        import Lynx

        @objc public final class WhiskerModuleBehaviors: NSObject {
            private static var registered = false
            private static let lock = NSLock()

            @objc public static func registerAll() {
                lock.lock()
                defer { lock.unlock() }
                if registered { return }
                registered = true

        """

    if sorted.isEmpty {
        out += "        // (no @WhiskerElement-annotated class found)\n"
    }
    for hit in sorted {
        // Same dual-resolution shape the previous Rust-side
        // generator used: prefixed name first (default SwiftPM-target
        // mangled), bare name fallback (for authors who declare
        // `@objc(BareName)` themselves).
        out += """
                    do {
                        let cls = NSClassFromString("WhiskerModules.\(hit.className)")
                            ?? NSClassFromString("\(hit.className)")
                        if let cls = cls {
                            LynxComponentRegistry.registerUI(cls, withName: "\(hit.tag)")
                        }
                    }

            """
    }
    out += """
            }
        }

        """
    return out
}

// ---- Main --------------------------------------------------------------------

guard let args = parseArgs(CommandLine.arguments) else {
    FileHandle.standardError.write(Data(
        "usage: whisker-elements-codegen --output <path> <input.swift>...\n".utf8
    ))
    exit(2)
}

let collector = WhiskerElementCollector(viewMode: .sourceAccurate)
for input in args.inputs {
    let source: String
    do {
        source = try String(contentsOfFile: input, encoding: .utf8)
    } catch {
        FileHandle.standardError.write(Data(
            "whisker-elements-codegen: cannot read \(input): \(error)\n".utf8
        ))
        exit(1)
    }
    let tree = Parser.parse(source: source)
    collector.walk(tree)
}

let generated = render(hits: collector.hits)
do {
    try generated.write(toFile: args.outputPath, atomically: true, encoding: .utf8)
} catch {
    FileHandle.standardError.write(Data(
        "whisker-elements-codegen: cannot write \(args.outputPath): \(error)\n".utf8
    ))
    exit(1)
}
