{
  "formatVersion": "1.1",
  "component": {
    "group": "rs.whisker",
    "module": "whisker-runtime-android",
    "version": "0.1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "rs.whisker",
          "module": "whisker-module-android",
          "version": {
            "requires": "0.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-runtime-android-0.1.21.aar",
          "url": "whisker-runtime-android-0.1.21.aar",
          "size": 241692,
          "sha512": "f586e491ec7051c1f7d256d33febb404df5731fb23efc607a11a98e3017d13b6975968b8d3830dc699e3cea1de527546ea7856e8a55239c2c93ddc80bd03a519",
          "sha256": "3cd344195fd417a108d9667c32ba9d8ba5e5c64c6be3c0f6644ef804417ff463",
          "sha1": "33fb21a361d167d574f09a16547c0c3155934737",
          "md5": "13674e6f017526fcabd73a7c0efda923"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "rs.whisker",
          "module": "whisker-module-android",
          "version": {
            "requires": "0.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-runtime-android-0.1.21.aar",
          "url": "whisker-runtime-android-0.1.21.aar",
          "size": 241692,
          "sha512": "f586e491ec7051c1f7d256d33febb404df5731fb23efc607a11a98e3017d13b6975968b8d3830dc699e3cea1de527546ea7856e8a55239c2c93ddc80bd03a519",
          "sha256": "3cd344195fd417a108d9667c32ba9d8ba5e5c64c6be3c0f6644ef804417ff463",
          "sha1": "33fb21a361d167d574f09a16547c0c3155934737",
          "md5": "13674e6f017526fcabd73a7c0efda923"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-runtime-android-0.1.21-sources.jar",
          "url": "whisker-runtime-android-0.1.21-sources.jar",
          "size": 57555,
          "sha512": "75aa134bd98997af406672fa58cdb13867a0178c203eb9adc99c7df6b911c536149c05c4657eaf387862b06539b84f49634f8cdb7e712270edbc51b4e1e41de4",
          "sha256": "89df2248d2890d25cee81edbe01478377772104c393780297e09215b1a138e49",
          "sha1": "be139101a0805059cf7f94612cfb4a683ea24554",
          "md5": "17403d06a6f2cba1f736607f23cfb223"
        }
      ]
    }
  ]
}
