package rs.whisker.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

// Generates the aggregator Kotlin file
//
//   rs/whisker/runtime/generated/WhiskerModuleBehaviors.kt
//
// whose `registerAll()` chains every Whisker module's KSP-emitted
// `<Module>Behaviors.registerAll()`. The host app's `Application.kt`
// (cng-rendered) calls
// `WhiskerModuleBehaviors.registerAll()` once at launch — that fans
// out to each module's `@WhiskerElement` / `@WhiskerModule`
// registrations.
//
// The behaviors objects all live in package
// `rs.whisker.runtime.generated`, same as the aggregator, so we can
// reference them by their short name without imports.
//
// AGP wiring: `addGeneratedSourceDirectory(task, ::outputDir)` is
// called from `WhiskerProjectPlugin`, so `compile<Variant>Kotlin`
// depends on this task automatically.
abstract class WhiskerModuleBehaviorsTask : DefaultTask() {

    @get:Input
    abstract val behaviorsClasses: ListProperty<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val pkgDir = outputDir.get().asFile
            .resolve("rs/whisker/runtime/generated")
        pkgDir.mkdirs()
        val file = pkgDir.resolve("WhiskerModuleBehaviors.kt")
        file.writeText(buildString {
            appendLine("// AUTO-GENERATED by rs.whisker.gradle. Do NOT edit.")
            appendLine("package rs.whisker.runtime.generated")
            appendLine()
            appendLine("import java.util.concurrent.atomic.AtomicBoolean")
            appendLine()
            appendLine("public object WhiskerModuleBehaviors {")
            appendLine("    private val registered = AtomicBoolean(false)")
            appendLine()
            appendLine("    @JvmStatic")
            appendLine("    public fun registerAll() {")
            appendLine("        if (!registered.compareAndSet(false, true)) return")
            val classes = behaviorsClasses.get()
            if (classes.isEmpty()) {
                appendLine("        // (no Whisker module deps)")
            } else {
                classes.forEach { cls ->
                    appendLine("        $cls.registerAll()")
                }
            }
            appendLine("    }")
            appendLine("}")
        })
    }
}
