// Generated by whisker-cng. Edit whisker.rs, not this file.

fn main() -> Result<(), whisker_macos::MacosHostError> {
    whisker_macos::run(
        whisker_macos::MacosAppConfig::new({{app_title_rust}}),
        whisker_app::__whisker_application,
    )
}
