{
  "formatVersion": "1.1",
  "component": {
    "group": "rs.whisker",
    "module": "whisker-runtime-android",
    "version": "0.1.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "rs.whisker",
          "module": "whisker-module-android",
          "version": {
            "requires": "0.1.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-runtime-android-0.1.25.aar",
          "url": "whisker-runtime-android-0.1.25.aar",
          "size": 257151,
          "sha512": "5d7ab660c5546cb7442378ef5bfd6c3a84c2dca50711197e99eafef785c4403e4fb932f1b740e4951955155487f61707ba7715a23adfce6053a4a2699ccc5d16",
          "sha256": "4c4b5c047eeaaf98222e153ce72b9da572dfde6e40c5cc2bb65764bb551c8fe4",
          "sha1": "eca598162178b8bb011d152caacc77a6a724de34",
          "md5": "9a77fe6502fead508d659774d64995f5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "rs.whisker",
          "module": "whisker-module-android",
          "version": {
            "requires": "0.1.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-runtime-android-0.1.25.aar",
          "url": "whisker-runtime-android-0.1.25.aar",
          "size": 257151,
          "sha512": "5d7ab660c5546cb7442378ef5bfd6c3a84c2dca50711197e99eafef785c4403e4fb932f1b740e4951955155487f61707ba7715a23adfce6053a4a2699ccc5d16",
          "sha256": "4c4b5c047eeaaf98222e153ce72b9da572dfde6e40c5cc2bb65764bb551c8fe4",
          "sha1": "eca598162178b8bb011d152caacc77a6a724de34",
          "md5": "9a77fe6502fead508d659774d64995f5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-runtime-android-0.1.25-sources.jar",
          "url": "whisker-runtime-android-0.1.25-sources.jar",
          "size": 60254,
          "sha512": "20db5e776fe8cead1b7bcf14f20616a23035231fb397a64343a188a4ffa133ab66521d8da50b4527ada6472172952b8ee11c354aef25f028b90400603339c732",
          "sha256": "0530e9a25f54a7e73e507729e53c20d546b349e9bb0ce0d824c1a215c06c4c61",
          "sha1": "2ace073ac6ff551d85d99b8cbe8292b19373aadc",
          "md5": "25c40120185ed613c04ecd36d5e3a351"
        }
      ]
    }
  ]
}
