//! Example app for `whisker-router` — a tabbed app declared with `routes!`:
//!
//! ```text
//! Layout(TabsLayout) {            // the tab bar chrome (a `Layout`, not the Switch)
//!     Switch {
//!         Stack { Route("", Home)            ..shared }   // tab 0 + /detail/:id
//!         Stack { Route("list", ListScreen)  ..shared }   // tab 1 + /detail/:id
//!     }
//! }   // `let shared = routes! { Route("detail/:id", Detail) };`
//! ```
//!
//! - **Home / List tabs**: a button → `nav.navigate("/detail/N")` pushes a
//!   Detail onto the active tab's stack; `Detail` reads its `:id` via
//!   `use_param`. Each tab keeps its **own** history (switching tabs preserves
//!   where you were); the shared `detail` route — declared once and `..shared`
//!   into both stacks — dedupes to whichever tab you are in (relative
//!   resolution).
//! - **`TabBar`**: the bottom chrome; it **highlights the active tab itself**
//!   by matching the current route, and tapping a tab calls `nav.select(..)`.
//! - **Back gestures**: `SwipeBack` (iOS edge swipe) and `AndroidPredictiveBack`
//!   (Android 13+ Material preview) pop the active stack.
//!
//! `Router` only publishes context + renders a bare `Outlet`; the route tree
//! (with its `Layout` chrome) is drawn there.

use whisker::css::{AlignItems, Color, Display, FlexDirection, JustifyContent};
use whisker::prelude::*;
use whisker::runtime::view::Element;
use whisker_router::core::Target;
use whisker_router::render::{
    AndroidPredictiveBack, Outlet, Router, RouterHandle, SwipeBack, TabBar, TabItem, use_navigator,
    use_param,
};
use whisker_router::routes;

fn build_handle() -> RouterHandle {
    // The whole tree + registry + chrome, generated by `routes!`. The Switch
    // (tabs) is wrapped in `Layout(TabsLayout)` so the tab bar is declared in
    // the route tree; the router applies it automatically when it draws the
    // Switch. Each route's id is its component name in snake_case (`Detail`
    // → `detail`, `ListScreen` → `list_screen`); `Detail` reads its `:id`
    // via `use_param`.
    // `detail` is shared by both tabs — declare it once as a spreadable
    // fragment and `..shared` it into each stack (each tab keeps its own
    // history; the two instances dedupe to a single nav target by id).
    let shared = routes! { Route("detail/:id", Detail) };
    RouterHandle::new(routes! {
        Layout(TabsLayout) {
            Switch {
                Stack { Route("", Home)            ..shared }
                Stack { Route("list", ListScreen)  ..shared }
            }
        }
    })
}

/// The tab-bar chrome (a `Layout(X)` component): an `Outlet` for the active
/// branch above a bottom nav bar. `TabBar` highlights the active tab itself
/// (by matching the current route), so the chrome needs no active-index wiring.
#[component]
fn tabs_layout() -> Element {
    render! {
        view(style: css!(
            flex_grow: 1.0,
            display: Display::Flex,
            flex_direction: FlexDirection::Column,
        )) {
            view(style: css!(
                flex_grow: 1.0,
                display: Display::Flex,
                flex_direction: FlexDirection::Column,
            )) {
                Outlet {}
            }
            TabBar(
                items: vec![
                    TabItem::new("Home", Target::id("home")),
                    TabItem::new("List", Target::id("list_screen")),
                ],
            )
        }
    }
}

#[whisker::main]
fn app() -> Element {
    let handle = build_handle();
    render! {
        Router(handle: handle) {
            // The route tree (with its `Layout` chrome) draws here.
            Outlet {}
            // Interactive back gestures — both mounted; each waits on its
            // own platform input. iOS = leading-edge swipe; Android =
            // system predictive back (13+ shows the Material live preview).
            AndroidPredictiveBack {}
            SwipeBack {}
        }
    }
}

// ---------------------------------------------------------------------
// Screens
// ---------------------------------------------------------------------

#[component]
fn home() -> Element {
    let nav = use_navigator();
    render! {
        view(style: screen_style(0x101018)) {
            text(value: "Home", style: title_style())
            text(value: "Tab 0 · its own stack", style: subtitle_style())
            view(
                style: button_style(),
                on_tap: move |_| {
                    let _ = nav.navigate("/detail/1");
                },
            ) {
                text(value: "Open Detail 1", style: button_label_style())
            }
        }
    }
}

#[component]
fn list_screen() -> Element {
    let nav = use_navigator();
    render! {
        view(style: screen_style(0x0E1414)) {
            text(value: "List", style: title_style())
            text(value: "Tab 1 · its own stack", style: subtitle_style())
            view(
                style: button_style(),
                on_tap: {
                    let nav = nav.clone();
                    move |_| {
                        let _ = nav.navigate("/detail/42");
                    }
                },
            ) {
                text(value: "Open Detail 42", style: button_label_style())
            }
            view(
                style: button_style(),
                on_tap: move |_| {
                    let _ = nav.navigate("/detail/99");
                },
            ) {
                text(value: "Open Detail 99", style: button_label_style())
            }
        }
    }
}

#[component]
fn detail() -> Element {
    let nav = use_navigator();
    // Read this route's `:id` param from context — the macro-free analogue
    // of `routes! { Route("detail/:id", Detail) }` + `use_param`.
    let id = use_param("id");
    let label = format!("Detail #{}", id.get().unwrap_or_default());
    render! {
        view(style: screen_style(0x1A1422)) {
            text(value: label, style: title_style())
            text(value: "Swipe from the left edge, or tap Back.", style: subtitle_style())
            view(
                style: button_style(),
                on_tap: move |_| {
                    let _ = nav.back();
                },
            ) {
                text(value: "Back", style: button_label_style())
            }
        }
    }
}

// ---------------------------------------------------------------------
// Tiny shared styles
// ---------------------------------------------------------------------

fn button_style() -> Css {
    css!(
        padding: (px(12), px(24)),
        margin_top: px(16),
        border_radius: px(12),
        background_color: Color::hex(0x7C5CFF),
    )
}

fn button_label_style() -> Css {
    css!(color: Color::hex(0xFFFFFF), font_size: px(16))
}

fn screen_style(bg: u32) -> Css {
    css!(
        flex_grow: 1.0,
        display: Display::Flex,
        flex_direction: FlexDirection::Column,
        justify_content: JustifyContent::Center,
        align_items: AlignItems::Center,
        background_color: Color::hex(bg),
    )
}

fn title_style() -> Css {
    css!(color: Color::hex(0xFFFFFF), font_size: px(28))
}

fn subtitle_style() -> Css {
    css!(color: Color::hex(0x9A9AB0), font_size: px(14), margin_top: px(8))
}
