// swift-tools-version:5.9
//
// SwiftPM manifest for the `whisker-hello-element` module package's
// iOS half (Phase 7-Φ.G).
//
// Each Whisker module package is now its own SwiftPM library that
// the user app's aggregator (`gen/ios/whisker_modules/Package.swift`,
// generated by whisker-build) depends on via a local-path
// `.package(path: …)` reference. That replaces Phase F's file-copy
// flow where module .swift files were staged into the aggregator's
// own source tree.
//
// Module authors are free to add their own SPM dependencies here
// — external Swift packages, CocoaPods-via-SPM, or whatever else
// the module needs. The aggregator picks everything up
// transitively via SwiftPM's regular dependency resolution; no
// special Whisker plumbing required.

import PackageDescription

// whisker-build injects the absolute location of Whisker's iOS
// runtime + macros packages via these env vars (the same paths it
// writes into the generated aggregator Package.swift), so this module
// resolves them no matter where the crate lives — in the monorepo, in
// a user's whisker project, or unpacked from the cargo registry. The
// relative-path fallback applies only when building this package
// standalone (e.g. opening it directly in Xcode from the monorepo).
let whiskerRuntimePath = Context.environment["WHISKER_IOS_RUNTIME"] ?? "../../platforms/ios"
let whiskerMacrosPath = Context.environment["WHISKER_IOS_MACROS"] ?? "../../platforms/ios/macros"

let package = Package(
    name: "whisker-hello-element",
    // macOS 13 is required because the SwiftPM build plugin
    // (`WhiskerComponentsCodegenPlugin`) is hosted by SwiftSyntax,
    // which requires that floor at build time. The module's
    // runtime artefacts only need iOS 13.
    platforms: [.iOS(.v13), .macOS(.v13)],
    products: [
        // Library name MUST match the target name — the
        // whisker-build-generated aggregator imports this product
        // via `.product(name: "WhiskerHelloElement",
        //               package: "whisker-hello-element")`.
        .library(name: "WhiskerHelloElement", targets: ["WhiskerHelloElement"]),
    ],
    dependencies: [
        // Package.swift at the package root (SwiftPM requirement;
        // identity = crate dir name, unique). WhiskerComponents
        // ships the codegen build-tool plugin; WhiskerModuleApi
        // exposes the `WhiskerUI` / `WhiskerContext` typealiases +
        // `WhiskerValue` + transitive `@_exported import Lynx`.
        .package(name: "macros", path: whiskerMacrosPath),
        .package(name: "WhiskerRuntime", path: whiskerRuntimePath),
    ],
    targets: [
        .target(
            name: "WhiskerHelloElement",
            dependencies: [
                .product(name: "WhiskerComponents", package: "macros"),
                .product(name: "WhiskerModuleApi", package: "WhiskerRuntime"),
            ],
            // Swift sources under the package's `ios/` directory
            // (Expo-style layout), next to `android/` and `src/`.
            path: "ios/Sources/WhiskerHelloElement",
            plugins: [
                // The plugin emits a per-target `+Generated.swift`
                // containing the `_whiskerRegisterModules_<Target>()`
                // fn the aggregator calls from
                // `WhiskerModuleBehaviors.registerAll()`.
                .plugin(name: "WhiskerComponentsCodegenPlugin", package: "macros"),
            ]
        ),
    ]
)
