// swift-tools-version:5.9
//
// SwiftPM manifest for the `whisker-hello-element` module package's
// iOS half (Phase 7-Φ.G).
//
// Each Whisker module package is now its own SwiftPM library that
// the user app's aggregator (`gen/ios/whisker_modules/Package.swift`,
// generated by whisker-build) depends on via a local-path
// `.package(path: …)` reference. That replaces Phase F's file-copy
// flow where module .swift files were staged into the aggregator's
// own source tree.
//
// Module authors are free to add their own SPM dependencies here
// — external Swift packages, CocoaPods-via-SPM, or whatever else
// the module needs. The aggregator picks everything up
// transitively via SwiftPM's regular dependency resolution; no
// special Whisker plumbing required.

import PackageDescription

let package = Package(
    name: "whisker-hello-element",
    // macOS 13 is required because the SwiftPM build plugin
    // (`WhiskerComponentsCodegenPlugin`) is hosted by SwiftSyntax,
    // which requires that floor at build time. The module's
    // runtime artefacts only need iOS 13.
    platforms: [.iOS(.v13), .macOS(.v13)],
    products: [
        // Library name MUST match the target name — the
        // whisker-build-generated aggregator imports this product
        // via `.product(name: "WhiskerHelloComponent",
        //               package: "whisker-hello-element")`.
        .library(name: "WhiskerHelloComponent", targets: ["WhiskerHelloComponent"]),
    ],
    dependencies: [
        // WhiskerComponents ships the `@WhiskerComponent` / `@WhiskerModule`
        // macros + the SwiftPM build-tool plugin that scans this
        // target's sources for those annotations.
        .package(name: "whisker-ios-macros", path: "../whisker-ios-macros"),
        // WhiskerRuntime gives module sources access to Lynx C++
        // types (LynxUI, LynxComponentRegistry, …) and re-exports
        // the WhiskerDriver C ABI symbols the macro-emitted
        // dispatch shim references.
        .package(name: "WhiskerRuntime", path: "../../native/ios"),
    ],
    targets: [
        .target(
            name: "WhiskerHelloComponent",
            dependencies: [
                .product(name: "WhiskerComponents", package: "whisker-ios-macros"),
                .product(name: "WhiskerRuntime", package: "WhiskerRuntime"),
                .product(name: "Lynx", package: "WhiskerRuntime"),
            ],
            // Sources live in `src/ios/` next to the Rust crate's
            // `src/lib.rs` — SwiftPM's `path:` is relative to the
            // package root and selects which directory the target
            // pulls its sources from.
            path: "src/ios",
            plugins: [
                // The plugin emits a per-target
                // `WhiskerHelloComponent+Generated.swift` containing
                // a top-level `_whiskerRegisterModules_WhiskerHelloComponent()`
                // fn the aggregator calls from
                // `WhiskerModuleBehaviors.registerAll()`.
                .plugin(name: "WhiskerComponentsCodegenPlugin", package: "whisker-ios-macros"),
            ]
        ),
    ]
)
