//! Platform application plugins contribute the Cargo root and OS metadata.
use super::*;
use std::collections::BTreeMap;
use whisker_plugin::{FileEntry, PluginConfig};

macro_rules! application {
    ($ty:ident, $config:ident, $platform:ident, $name:literal, $factory:ident) => {
        pub struct $ty {
            inputs: DesktopInputs,
        }
        #[derive(Default, serde::Serialize, serde::Deserialize)]
        #[serde(deny_unknown_fields)]
        pub struct $config {}
        impl PluginConfig for $config {
            const NAME: &'static str = $name;
        }
        impl $ty {
            pub const NAME: &'static str = $name;
            pub fn new(inputs: DesktopInputs) -> Self {
                Self { inputs }
            }
        }
        impl ProjectPlugin for $ty {
            type Config = $config;
            fn contribute(&self, ctx: &ProjectContext, _: &Self::Config) -> Result<ProjectUpdate> {
                if !matches!(ctx.project, ProjectIr::$platform(_)) {
                    return Ok(ProjectUpdate::Keep);
                }
                ensure!(
                    self.inputs.platform == crate::GenerationTarget::$platform,
                    "application platform mismatch"
                );
                Ok(ProjectUpdate::Merge {
                    project: Box::new(project(&self.inputs)?),
                })
            }
        }
        impl crate::ProjectEngine {
            pub fn $factory(inputs: DesktopInputs) -> Self {
                let mut engine = Self::with_initializer($ty::new(inputs));
                engine.register_mobile_builtins();
                engine
            }
        }
    };
}
application!(
    WindowsApplicationPlugin,
    WindowsApplicationConfig,
    Windows,
    "whisker-windows-application",
    with_windows_application
);
application!(
    LinuxApplicationPlugin,
    LinuxApplicationConfig,
    Linux,
    "whisker-linux-application",
    with_linux_application
);

fn project(i: &DesktopInputs) -> Result<ProjectIr> {
    let platform = i.platform.as_str();
    let windows = i.platform == crate::GenerationTarget::Windows;
    let mut files = ProjectFiles::new();
    let manifest = format!(
        r#"# Generated by whisker-cng. Edit whisker.rs.
[workspace]
resolver = "2"
[package]
name = {:?}
version = "0.0.0"
edition = "2024"
publish = false
[dependencies]
whisker-app = {{ package = {:?}, path = {:?}{} }}
whisker-{platform} = {}
whisker-desktop = {}
{}
[profile.dev.package."*"]
opt-level = 2
[profile.dev.package.{:?}]
opt-level = 0
"#,
        i.generated_package,
        i.user_package,
        i.user_crate_path.to_str().context("non-UTF-8 app path")?,
        i.cargo_selection.dependency_options(),
        i.host_dependency,
        i.desktop_dependency,
        crate::rust_element_module_dependencies(&i.element_modules),
        i.user_package
    );
    let [r, g, b] = crate::background::AppBackground::parse(&i.background)?.rgb();
    let type_prefix = if windows { "Windows" } else { "Linux" };
    let main = format!(
        r#"// Generated by whisker-cng.
#![cfg_attr(target_os = "windows", windows_subsystem = "windows")]
fn main() -> Result<(), whisker_{platform}::{type_prefix}Error> {{
    whisker_{platform}::run_with_application_hash(
        whisker_{platform}::{type_prefix}AppConfig::new({:?})
            .with_background_rgb({r}, {g}, {b}){},
        whisker_app::__whisker_application,
        whisker_app::__whisker_application_hash,
    )
}}
"#,
        i.app_name,
        crate::rust_element_module_config(&i.element_modules)
    );
    for (path, text) in [("Cargo.toml", manifest), ("src/main.rs", main)] {
        files.insert(
            ProjectPath::new(path)?,
            ProjectFile::Generated {
                entry: FileEntry::text(text),
            },
        );
    }
    let executable = DesktopExecutable {
        source: ExecutableSource::Cargo(RustBuild {
            manifest: ProjectPath::new("Cargo.toml")?,
            package: i.generated_package.clone(),
            target: i.generated_package.clone(),
            kind: RustArtifactKind::Bin,
            features: vec![],
            default_features: true,
        }),
        destination: ProjectPath::new(if windows {
            format!("{}.exe", i.generated_package)
        } else {
            format!("bin/{}", i.generated_package)
        })?,
    };
    if windows {
        let mut manifest = XmlElement::new("assembly");
        manifest.attributes = [
            ("xmlns".into(), "urn:schemas-microsoft-com:asm.v1".into()),
            ("manifestVersion".into(), "1.0".into()),
        ]
        .into();
        let mut identity = XmlElement::new("assemblyIdentity");
        let version = windows_version(&i.version, i.build_number)?;
        identity.attributes = [
            ("name".into(), i.app_id.clone()),
            (
                "version".into(),
                version
                    .iter()
                    .map(u16::to_string)
                    .collect::<Vec<_>>()
                    .join("."),
            ),
            ("type".into(), "win32".into()),
        ]
        .into();
        manifest.children.push(XmlNode::Element(identity));
        let mut exe = WindowsExecutable {
            executable,
            manifest: Some(manifest),
            icon: None,
            resource_scripts: vec![],
            version_info: Some(WindowsVersionInfo {
                file_version: version,
                product_version: version,
                strings: [(
                    "040904B0".into(),
                    [
                        ("FileDescription".into(), i.app_name.clone()),
                        ("ProductName".into(), i.app_name.clone()),
                        ("FileVersion".into(), i.version.clone()),
                        ("ProductVersion".into(), i.version.clone()),
                    ]
                    .into(),
                )]
                .into(),
                flags_mask: None,
                flags: None,
                file_os: Some(0x40004),
                file_type: Some(1),
                file_subtype: None,
            }),
        };
        if let Some(png) = &i.app_icon_png {
            // A PNG-compressed 256px ICO entry is supported by modern Windows.
            let png = icon_png(png, 256)?;
            let mut ico = vec![0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 32, 0];
            ico.extend_from_slice(&(png.len() as u32).to_le_bytes());
            ico.extend_from_slice(&22u32.to_le_bytes());
            ico.extend(png);
            let path = ProjectPath::new("AppIcon.ico")?;
            files.insert(
                path.clone(),
                ProjectFile::Generated {
                    entry: FileEntry::binary(&ico),
                },
            );
            exe.icon = Some(path);
        }
        Ok(ProjectIr::Windows(WindowsProjectIr {
            application: "app".into(),
            executables: [("app".into(), exe)].into(),
            files,
            ..Default::default()
        }))
    } else {
        let mut entry = DesktopEntry {
            entries: BTreeMap::from([
                (
                    "Type".into(),
                    DesktopEntryValue::String("Application".into()),
                ),
                ("Name".into(), DesktopEntryValue::String(i.app_name.clone())),
                (
                    "Exec".into(),
                    DesktopEntryValue::String(i.generated_package.clone()),
                ),
                ("Terminal".into(), DesktopEntryValue::Boolean(false)),
            ]),
            actions: BTreeMap::new(),
        };
        let mut resources = vec![];
        if let Some(png) = &i.app_icon_png {
            let path = ProjectPath::new("AppIcon.png")?;
            files.insert(
                path.clone(),
                ProjectFile::Generated {
                    entry: FileEntry::binary(&icon_png(png, 256)?),
                },
            );
            resources.push(Resource {
                source: path,
                destination: ProjectPath::new(format!(
                    "share/icons/hicolor/256x256/apps/{}.png",
                    i.app_id
                ))?,
                kind: ResourceKind::File,
            });
            entry
                .entries
                .insert("Icon".into(), DesktopEntryValue::String(i.app_id.clone()));
        }
        Ok(ProjectIr::Linux(LinuxProjectIr {
            app_id: i.app_id.clone(),
            application: "app".into(),
            executables: [("app".into(), executable)].into(),
            desktop_entries: [(
                ProjectPath::new(format!("share/applications/{}.desktop", i.app_id))?,
                entry,
            )]
            .into(),
            resources,
            files,
            ..Default::default()
        }))
    }
}
fn windows_version(version: &str, build: u32) -> Result<[u16; 4]> {
    let parts = version
        .split(['-', '+'])
        .next()
        .unwrap()
        .split('.')
        .map(str::parse::<u16>)
        .collect::<std::result::Result<Vec<_>, _>>()?;
    ensure!(
        parts.len() == 3,
        "Windows version must have three numeric components"
    );
    Ok([
        parts[0],
        parts[1],
        parts[2],
        build
            .try_into()
            .context("Windows build number must fit u16")?,
    ])
}
fn icon_png(bytes: &[u8], size: u32) -> Result<Vec<u8>> {
    let icon = image::load_from_memory_with_format(bytes, image::ImageFormat::Png)?;
    ensure!(
        icon.width() == icon.height() && icon.width() >= size,
        "desktop icon must be square and at least {size}px"
    );
    let mut out = std::io::Cursor::new(vec![]);
    icon.resize_exact(size, size, image::imageops::FilterType::Lanczos3)
        .write_to(&mut out, image::ImageFormat::Png)?;
    Ok(out.into_inner())
}
