use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::PathBuf;

use crate::Config;

/// A project generated by CNG; iOS device and simulator share one project.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum GenerationTarget {
    Android,
    Ios,
    Macos,
    Web,
}

impl GenerationTarget {
    /// All supported project generators, independent of the build machine.
    pub const ALL: [Self; 4] = [Self::Android, Self::Ios, Self::Macos, Self::Web];

    /// The platform name used in arguments and generated directory names.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Android => "android",
            Self::Ios => "ios",
            Self::Macos => "macos",
            Self::Web => "web",
        }
    }
}

impl std::str::FromStr for GenerationTarget {
    type Err = anyhow::Error;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "android" => Ok(Self::Android),
            "ios" => Ok(Self::Ios),
            "macos" | "desktop" => Ok(Self::Macos),
            "web" => Ok(Self::Web),
            _ => anyhow::bail!(
                "unknown generation target `{value}`; expected android, ios, desktop, or web"
            ),
        }
    }
}

/// The output of synchronizing one platform project.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlatformSync {
    /// Absolute directory containing the generated project.
    pub gen_dir: PathBuf,
    /// Whether this invocation rewrote the project instead of reusing it.
    pub regenerated: bool,
    /// The renderer's template revision, when the platform exposes one.
    pub template_version: Option<u32>,
}

/// Metadata written only after every requested project has been generated.
#[derive(Debug, Serialize, Deserialize)]
pub struct GenerationReport {
    /// Report format version, independent of the CNG package version.
    pub schema_version: u32,
    /// Canonical directory containing the application's Cargo.toml.
    pub crate_dir: PathBuf,
    /// The application's workspace root as resolved by Cargo.
    pub workspace_root: PathBuf,
    /// Application Cargo package name.
    pub package: String,
    /// Configuration used for this generation, also consumed by build tools.
    pub config: Config,
    /// Completed projects, keyed by their generation target.
    pub projects: BTreeMap<GenerationTarget, PlatformSync>,
}

/// Generate platform projects from the configuration supplied by `whisker.rs`.
///
/// Call once from `main`. With no arguments this generates Android, iOS, macOS,
/// and Web projects. Pass platform names (or `--target <platform>`) to select
/// projects. `--manifest-path <path>` selects the application manifest;
/// otherwise Cargo's runtime manifest directory or the current directory is used.
/// Relative paths in the closure resolve from the application directory.
///
/// Generation includes Cargo module discovery and native CNG plugin builds.
/// It writes a generation report to `target/.whisker/generation.json`, or to
/// `--report-path <path>`. There is no configuration-only execution mode.
/// The generated projects retain their normal Rust and native build steps.
///
/// # Feature and process requirements
///
/// Enable the `generate` feature to execute this function. Its interface remains
/// available without that feature for editor analysis. On failure this prints a
/// diagnostic and exits the process with status 1. Run it from the program's
/// entry point before starting threads: it sets the process working directory.
///
/// ```no_run
/// whisker_cng::run(|app| {
///     app.name("My App").bundle_id("com.example.myapp");
/// });
/// ```
pub fn run(configure: impl FnOnce(&mut Config)) {
    #[cfg(feature = "generate")]
    let result = run_inner(configure);
    #[cfg(not(feature = "generate"))]
    let result: anyhow::Result<()> = {
        let _ = configure;
        Err(anyhow::anyhow!(
            "enable whisker-cng's `generate` feature to execute the configuration binary"
        ))
    };
    if let Err(error) = result {
        eprintln!("Whisker generation failed: {error:#}");
        std::process::exit(1);
    }
}

#[cfg(feature = "generate")]
fn run_inner(configure: impl FnOnce(&mut Config)) -> anyhow::Result<()> {
    use anyhow::Context;
    let mut manifest = None;
    let mut report = None;
    let mut targets = Vec::new();
    let mut args = std::env::args_os().skip(1);
    while let Some(arg) = args.next() {
        match arg.to_str() {
            Some("--manifest-path") => {
                manifest = Some(PathBuf::from(
                    args.next().context("--manifest-path requires a path")?,
                ))
            }
            Some("--report-path") => {
                report = Some(PathBuf::from(
                    args.next().context("--report-path requires a path")?,
                ))
            }
            Some("--target") => targets.push(
                args.next()
                    .context("--target requires a platform")?
                    .to_str()
                    .context("target must be UTF-8")?
                    .parse()?,
            ),
            Some("--help" | "-h") => {
                println!(
                    "Generate Whisker projects: [android|ios|desktop|web]... [--manifest-path Cargo.toml] [--report-path path]\nWith no platform arguments, generate all four projects."
                );
                return Ok(());
            }
            Some(value) => targets.push(value.parse()?),
            None => anyhow::bail!("target must be UTF-8"),
        }
    }
    let manifest = match manifest {
        Some(path) => path
            .canonicalize()
            .context("resolve application manifest")?,
        None => {
            let start = std::env::var_os("CARGO_MANIFEST_DIR")
                .map(PathBuf::from)
                .unwrap_or(std::env::current_dir()?);
            start
                .ancestors()
                .map(|dir| dir.join("Cargo.toml"))
                .find(|path| path.is_file())
                .context("no Cargo.toml found; pass --manifest-path <application Cargo.toml>")?
                .canonicalize()?
        }
    };
    let crate_dir = manifest.parent().context("manifest has no parent")?;
    std::env::set_current_dir(crate_dir).context("enter application directory")?;
    let default_report = crate_dir.join("target/.whisker/generation.json");
    let report_path = report.unwrap_or_else(|| default_report.clone());
    match std::fs::remove_file(&report_path) {
        Ok(()) => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(error) => return Err(error).context("remove previous generation report"),
    }
    if report_path != default_report {
        match std::fs::remove_file(&default_report) {
            Ok(()) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(error).context("remove previous generation report"),
        }
    }
    let mut config = Config::default();
    configure(&mut config);
    let report = crate::generator::generate_config(&manifest, config, &targets)?;
    if report_path != default_report {
        write_report(&default_report, &report)?;
    }
    write_report(&report_path, &report)?;
    for (target, project) in &report.projects {
        eprintln!(
            "{} {} project at {}",
            if project.regenerated {
                "Generated"
            } else {
                "Reused"
            },
            target.as_str(),
            project.gen_dir.display()
        );
    }
    Ok(())
}

#[cfg(feature = "generate")]
fn write_report(path: &std::path::Path, report: &GenerationReport) -> anyhow::Result<()> {
    use anyhow::Context;
    use std::sync::atomic::{AtomicU64, Ordering};
    static SEQUENCE: AtomicU64 = AtomicU64::new(0);
    let parent = path.parent().context("report path has no parent")?;
    std::fs::create_dir_all(parent)?;
    let temporary = parent.join(format!(
        ".generation-{}-{}.tmp",
        std::process::id(),
        SEQUENCE.fetch_add(1, Ordering::Relaxed)
    ));
    let result = (|| {
        std::fs::write(&temporary, serde_json::to_vec(report)?)?;
        std::fs::rename(&temporary, path).context("publish generation report")
    })();
    if result.is_err() {
        let _ = std::fs::remove_file(temporary);
    }
    result
}
