#ifndef WHISKER_MOBILE_H_
#define WHISKER_MOBILE_H_

/* Generated by `cargo xtask mobile-abi generate`; do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Discriminants for [`WhiskerValueRaw::type`].
 */
#define WHISKER_VALUE_NULL 0

#define WHISKER_VALUE_BOOL 1

#define WHISKER_VALUE_INT 2

#define WHISKER_VALUE_FLOAT 3

#define WHISKER_VALUE_STRING 4

#define WHISKER_VALUE_BYTES 5

#define WHISKER_VALUE_ARRAY 6

#define WHISKER_VALUE_MAP 7

#define WHISKER_VALUE_ERROR 8

#define WHISKER_MOBILE_ABI_MAJOR 2

#define WHISKER_MOBILE_ABI_MINOR 29

#define WHISKER_FRAME_PROTOCOL_MAJOR 1

#define WHISKER_FRAME_PROTOCOL_MINOR 4

#define WHISKER_CAPABILITY_ELLIPTICAL_BORDER_RADIUS 1

#define WHISKER_CAPABILITY_BACKGROUND_LAYERS 2

#define WHISKER_CAPABILITY_VISUAL_EFFECTS 4

#define WHISKER_CAPABILITY_TEXT_EFFECTS 8

#define WHISKER_CAPABILITY_TEXT_TYPOGRAPHY 16


#define WHISKER_CAPABILITY_CURSOR 64

#define WHISKER_CAPABILITY_RESOURCE_LIFECYCLE 128

#define WHISKER_CAPABILITY_LINEAR_GRADIENTS 256

#define WHISKER_CAPABILITY_RADIAL_GRADIENTS 512

#define WHISKER_CAPABILITY_CONIC_GRADIENTS 1024

#define WHISKER_CAPABILITY_BACKGROUND_GEOMETRY 2048

#define WHISKER_CAPABILITY_BACKGROUND_LAYER_STACKING 4096

#define WHISKER_CAPABILITY_BACKGROUND_IMAGE_RESOURCES 8192

#define WHISKER_CAPABILITY_BACKDROP_BLUR 16384

#define WHISKER_POINTER_DOWN 0

#define WHISKER_POINTER_MOVE 1

#define WHISKER_POINTER_UP 2

#define WHISKER_POINTER_CANCEL 3

#define WHISKER_POINTER_MOUSE 0

#define WHISKER_POINTER_TOUCH 1

#define WHISKER_POINTER_PEN 2

#define WHISKER_POINTER_UNKNOWN 3

#define WHISKER_APPLY_ACCEPTED 0

#define WHISKER_APPLY_NEED_SNAPSHOT 1

#define WHISKER_APPLY_REJECTED 2

#define WHISKER_FRAME_SNAPSHOT 0

#define WHISKER_FRAME_DELTA 1

#define WHISKER_OP_CREATE 1

#define WHISKER_OP_DELETE 2

#define WHISKER_OP_INSERT 3

#define WHISKER_OP_REMOVE 4

#define WHISKER_OP_MOVE 5

#define WHISKER_OP_LAYOUT 6

#define WHISKER_OP_PAINT 7

#define WHISKER_OP_CLIP 8

#define WHISKER_OP_TRANSFORM 9

#define WHISKER_OP_OPACITY 10

#define WHISKER_OP_VISIBILITY 11

#define WHISKER_OP_Z_ORDER 12

#define WHISKER_OP_TEXT 13

#define WHISKER_OP_PROPERTY 14

#define WHISKER_OP_CLEAR_PROPERTY 15

#define WHISKER_OP_EVENT_MASK 16

#define WHISKER_OP_HIT_TEST 17

#define WHISKER_OP_CAPTURE 18

#define WHISKER_OP_RELEASE_CAPTURE 19

#define WHISKER_OP_COMMAND 20

#define WHISKER_OP_BACKGROUND_LAYERS 21

#define WHISKER_OP_BOX_SHADOWS 22

#define WHISKER_OP_CLIP_PATH 23

#define WHISKER_OP_BACKDROP_BLUR 24

#define WHISKER_OP_IMAGE_RENDERING 25

#define WHISKER_OP_CURSOR 26

#define WHISKER_OP_TEXT_STYLE 27

#define WHISKER_OP_ACCESSIBILITY 28

#define WHISKER_IMAGE_RENDERING_AUTO 0

#define WHISKER_IMAGE_RENDERING_PIXELATED 1

#define WHISKER_IMAGE_RENDERING_CRISP_EDGES 2

#define WHISKER_BACKGROUND_LINEAR 0

#define WHISKER_BACKGROUND_RADIAL 1

#define WHISKER_BACKGROUND_CONIC 2

#define WHISKER_BACKGROUND_RESOURCE 3

#define WHISKER_BACKGROUND_SIZE_AUTO 0

#define WHISKER_BACKGROUND_SIZE_EXPLICIT 1

#define WHISKER_BACKGROUND_SIZE_COVER 2

#define WHISKER_BACKGROUND_SIZE_CONTAIN 3

#define WHISKER_BACKGROUND_SIZE_WIDTH 4

#define WHISKER_BACKGROUND_SIZE_HEIGHT 5

#define WHISKER_BACKGROUND_REPEAT 0

#define WHISKER_BACKGROUND_NO_REPEAT 1

#define WHISKER_BACKGROUND_SPACE 2

#define WHISKER_BACKGROUND_ROUND 3

#define WHISKER_BACKGROUND_BOX_BORDER 0

#define WHISKER_BACKGROUND_BOX_PADDING 1

#define WHISKER_BACKGROUND_BOX_CONTENT 2

#define WHISKER_BACKGROUND_BOX_BORDER_AREA 3

#define WHISKER_BACKGROUND_ATTACHMENT_SCROLL 0

#define WHISKER_BACKGROUND_BLEND_NORMAL 0

#define WHISKER_CLIP_SHAPE_INSET 0

#define WHISKER_CLIP_SHAPE_CIRCLE 1

#define WHISKER_CLIP_SHAPE_ELLIPSE 2

#define WHISKER_CLIP_SHAPE_PATH 3

#define WHISKER_FILL_RULE_NON_ZERO 0

#define WHISKER_FILL_RULE_EVEN_ODD 1

#define WHISKER_PATH_MOVE_TO 0

#define WHISKER_PATH_LINE_TO 1

#define WHISKER_PATH_QUADRATIC_TO 2

#define WHISKER_PATH_CUBIC_TO 3

#define WHISKER_PATH_CLOSE 4

#define WHISKER_MEASURE_TEXT 1

#define WHISKER_MEASURE_REPLACED_CONTENT 2

#define WHISKER_MEASURE_NATIVE_CONTROL 3

#define WHISKER_MEASURE_EMBEDDED_SURFACE 4

#define WHISKER_MEASURE_CUSTOM 5

#define WHISKER_MEASURE_READY 1

#define WHISKER_MEASURE_PENDING 2

#define WHISKER_MEASURE_UNSUPPORTED 3

#define WHISKER_RESOURCE_COMMAND_LOAD 1

#define WHISKER_RESOURCE_COMMAND_RELEASE 2

#define WHISKER_RESOURCE_RASTER_IMAGE 1

#define WHISKER_RESOURCE_VECTOR_IMAGE 2

#define WHISKER_RESOURCE_FONT 3

#define WHISKER_RESOURCE_CURSOR 4

#define WHISKER_RESOURCE_PAINT_SERVER 5

#define WHISKER_RESOURCE_SOURCE_NONE 0

#define WHISKER_RESOURCE_SOURCE_URL 1

#define WHISKER_RESOURCE_SOURCE_BUNDLED_ASSET 2

#define WHISKER_RESOURCE_SOURCE_BYTES 3

#define WHISKER_RESOURCE_EVENT_READY 1

#define WHISKER_RESOURCE_EVENT_FAILED 2

#define WHISKER_RESOURCE_FAILURE_NONE 0

#define WHISKER_RESOURCE_FAILURE_NOT_FOUND 1

#define WHISKER_RESOURCE_FAILURE_DENIED 2

#define WHISKER_RESOURCE_FAILURE_NETWORK 3

#define WHISKER_RESOURCE_FAILURE_DECODE 4

#define WHISKER_RESOURCE_FAILURE_CANCELLED 5

#define WHISKER_RESOURCE_FAILURE_UNSUPPORTED 6

#define WHISKER_RESOURCE_DIMENSIONS_PRESENT 1

/**
 * Host-advertised renderer profile supplied once when a surface is created.
 */
typedef struct WhiskerMobileHostCapabilities {
  uint16_t abi_major;
  uint16_t abi_minor;
  uint16_t protocol_major;
  uint16_t protocol_minor;
  uint64_t native;
  uint64_t emulated;
} WhiskerMobileHostCapabilities;

typedef void (*WhiskerMobileRequestFrameCallback)(void*);

/**
 * Borrowed UTF-8 value.
 */
typedef struct WhiskerStringRef {
  const char *ptr;
  size_t len;
} WhiskerStringRef;

typedef struct WhiskerMobileMemberRegistration {
  uint32_t id;
  uint8_t value_kind;
  uint8_t optional_kind;
  uint8_t _pad[2];
  struct WhiskerStringRef name;
} WhiskerMobileMemberRegistration;

typedef struct WhiskerMobileElementRegistration {
  uint32_t element_type;
  uint8_t child_policy;
  uint8_t measurement;
  uint8_t text_style;
  uint8_t _pad;
  struct WhiskerStringRef name;
  const struct WhiskerMobileMemberRegistration *properties;
  size_t property_count;
  const struct WhiskerMobileMemberRegistration *events;
  size_t event_count;
  const struct WhiskerMobileMemberRegistration *commands;
  size_t command_count;
} WhiskerMobileElementRegistration;

typedef struct WhiskerMobileBootstrap {
  uint16_t abi_major;
  uint16_t abi_minor;
  uint16_t protocol_major;
  uint16_t protocol_minor;
  const struct WhiskerMobileElementRegistration *registrations;
  size_t registration_count;
} WhiskerMobileBootstrap;

typedef bool (*WhiskerMobileBootstrapCallback)(void*, const struct WhiskerMobileBootstrap*);

typedef struct WhiskerMobileFontFeature {
  uint8_t tag[4];
  uint32_t value;
} WhiskerMobileFontFeature;

typedef struct WhiskerMobileFontVariation {
  uint8_t tag[4];
  float value;
} WhiskerMobileFontVariation;

/**
 * Borrowed byte value.
 */
typedef struct WhiskerBytesRef {
  const uint8_t *ptr;
  size_t len;
} WhiskerBytesRef;

typedef struct WhiskerMobileMeasureRequest {
  uint64_t key;
  uint64_t node;
  uint32_t element_type;
  uint32_t kind;
  uint64_t environment_epoch;
  float known_width;
  float known_height;
  uint32_t known_mask;
  float available_width;
  float available_height;
  uint8_t available_width_kind;
  uint8_t available_height_kind;
  uint8_t font_style;
  uint8_t wrap;
  uint8_t word_break;
  uint8_t overflow;
  struct WhiskerStringRef text;
  struct WhiskerStringRef locale;
  const struct WhiskerStringRef *font_families;
  size_t font_family_count;
  float font_size;
  uint16_t font_weight;
  uint16_t payload_version;
  float line_height;
  float letter_spacing;
  const struct WhiskerMobileFontFeature *font_features;
  size_t font_feature_count;
  const struct WhiskerMobileFontVariation *font_variations;
  size_t font_variation_count;
  uint8_t font_optical_sizing;
  uint8_t _font_pad[7];
  float indent_logical_pixels;
  float indent_percentage;
  uint32_t max_lines;
  struct WhiskerBytesRef payload;
  float intrinsic_width;
  float intrinsic_height;
  uint32_t intrinsic_mask;
  uint8_t direction;
  uint8_t alignment;
  uint8_t _flow_pad[6];
} WhiskerMobileMeasureRequest;

typedef struct WhiskerMobileMeasureResponse {
  uint64_t key;
  uint64_t environment_epoch;
  uint32_t status;
  uint32_t reason;
  float width;
  float height;
  float first_baseline;
  float last_baseline;
  uint32_t metrics_mask;
  uint64_t request_id;
  uint64_t prepared_content;
} WhiskerMobileMeasureResponse;

typedef bool (*WhiskerMobileMeasureCallback)(void*,
                                             const struct WhiskerMobileMeasureRequest*,
                                             size_t,
                                             struct WhiskerMobileMeasureResponse*);

/**
 * Flat operation envelope. `payload` points to the type selected by `tag`.
 */
typedef struct WhiskerMobileOperation {
  uint32_t tag;
  uint32_t flags;
  uint64_t node;
  uint64_t parent;
  uint64_t child;
  uint32_t index;
  uint32_t member;
  int32_t integer;
  float scalar;
  uint64_t wide;
  const void *payload;
  size_t payload_count;
} WhiskerMobileOperation;

typedef struct WhiskerMobileFrame {
  uint16_t abi_major;
  uint16_t abi_minor;
  uint16_t protocol_major;
  uint16_t protocol_minor;
  uint8_t mode;
  uint8_t _pad[7];
  uint64_t surface;
  uint32_t scene_epoch;
  uint32_t viewport_epoch;
  uint64_t frame_id;
  uint64_t base_revision;
  uint64_t target_revision;
  const struct WhiskerMobileOperation *operations;
  size_t operation_count;
} WhiskerMobileFrame;

typedef struct WhiskerMobileApplyResponse {
  uint8_t status;
  uint8_t _pad[7];
  uint64_t revision;
} WhiskerMobileApplyResponse;

typedef bool (*WhiskerMobilePresentFrameCallback)(void*,
                                                  const struct WhiskerMobileFrame*,
                                                  struct WhiskerMobileApplyResponse*);

/**
 * One borrowed Rust-to-Host resource command. String and byte pointers are
 * valid only during the callback.
 */
typedef struct WhiskerMobileResourceCommand {
  uint32_t command;
  uint32_t kind;
  uint32_t source;
  uint32_t _reserved;
  uint64_t resource;
  uint64_t generation;
  struct WhiskerStringRef identifier;
  struct WhiskerBytesRef data;
} WhiskerMobileResourceCommand;

typedef bool (*WhiskerMobileResourceCommandCallback)(void*,
                                                     const struct WhiskerMobileResourceCommand*);

/**
 * Borrowed array value.
 */
typedef struct WhiskerValueArray {
  struct WhiskerValueRaw *items;
  size_t count;
} WhiskerValueArray;


/**
 * Borrowed map value.
 */
typedef struct WhiskerValueMap {
  struct WhiskerKeyValueRaw *entries;
  size_t count;
} WhiskerValueMap;

/**
 * Payload union for [`WhiskerValueRaw`].
 */
typedef union WhiskerValueUnion {
  bool b;
  int64_t i;
  double f;
  struct WhiskerStringRef s;
  struct WhiskerBytesRef bytes;
  struct WhiskerValueArray array;
  struct WhiskerValueMap map;
} WhiskerValueUnion;

/**
 * Raw FFI form of `WhiskerValue`.
 */
typedef struct WhiskerValueRaw {
  uint8_t type;
  uint8_t _pad[7];
  union WhiskerValueUnion v;
} WhiskerValueRaw;

/**
 * String-keyed map entry.
 */
typedef struct WhiskerKeyValueRaw {
  struct WhiskerStringRef key;
  struct WhiskerValueRaw value;
} WhiskerKeyValueRaw;

typedef void (*WhiskerMobileModuleResultCallback)(void*, const struct WhiskerValueRaw*);

typedef bool (*WhiskerMobileInvokeModuleCallback)(void*,
                                                  const uint8_t*,
                                                  size_t,
                                                  const uint8_t*,
                                                  size_t,
                                                  const struct WhiskerValueRaw*,
                                                  size_t,
                                                  bool,
                                                  WhiskerMobileModuleResultCallback,
                                                  void*);

typedef void (*WhiskerMobileObserveModuleCallback)(void*,
                                                   const uint8_t*,
                                                   size_t,
                                                   const uint8_t*,
                                                   size_t,
                                                   bool);

/**
 * One borrowed Host-to-Rust resource completion.
 */
typedef struct WhiskerMobileResourceEvent {
  uint32_t status;
  uint32_t failure_code;
  uint64_t resource;
  uint64_t generation;
  float width;
  float height;
  float scale;
  uint32_t dimensions_mask;
  struct WhiskerStringRef diagnostic;
} WhiskerMobileResourceEvent;

typedef struct WhiskerMobileRect {
  float x;
  float y;
  float width;
  float height;
} WhiskerMobileRect;

typedef struct WhiskerMobileLayoutGeometry {
  struct WhiskerMobileRect border;
  struct WhiskerMobileRect content;
} WhiskerMobileLayoutGeometry;

typedef struct WhiskerMobileColor {
  /**
   * 0 = named, 1 = sRGBA. Named colors borrow `name`.
   */
  uint32_t kind;
  uint8_t red;
  uint8_t green;
  uint8_t blue;
  uint8_t _pad;
  float alpha;
  struct WhiskerStringRef name;
} WhiskerMobileColor;

typedef struct WhiskerMobileLengthPercentage {
  float length;
  float fraction;
} WhiskerMobileLengthPercentage;

typedef struct WhiskerMobileBoxPaint {
  struct WhiskerMobileColor background;
  struct WhiskerMobileLengthPercentage widths[4];
  struct WhiskerMobileColor colors[4];
  uint32_t styles[4];
  struct WhiskerMobileLengthPercentage radii_horizontal[4];
  struct WhiskerMobileLengthPercentage radii_vertical[4];
} WhiskerMobileBoxPaint;

/**
 * One resolved box shadow. Arrays are ordered front to back.
 */
typedef struct WhiskerMobileBoxShadow {
  float offset_x;
  float offset_y;
  float blur_radius;
  float spread_radius;
  struct WhiskerMobileColor color;
  uint8_t inset;
  uint8_t _pad[7];
} WhiskerMobileBoxShadow;

/**
 * One rounded inset basic shape. Arrays use CSS top/right/bottom/left and
 * top-left/top-right/bottom-right/bottom-left ordering respectively.
 */
typedef struct WhiskerMobileClipInset {
  struct WhiskerMobileLengthPercentage edges[4];
  struct WhiskerMobileLengthPercentage radii_horizontal[4];
  struct WhiskerMobileLengthPercentage radii_vertical[4];
} WhiskerMobileClipInset;

typedef struct WhiskerMobileClipCircle {
  struct WhiskerMobileLengthPercentage radius;
  struct WhiskerMobileLengthPercentage center_x;
  struct WhiskerMobileLengthPercentage center_y;
} WhiskerMobileClipCircle;

typedef struct WhiskerMobileClipEllipse {
  struct WhiskerMobileLengthPercentage radius_x;
  struct WhiskerMobileLengthPercentage radius_y;
  struct WhiskerMobileLengthPercentage center_x;
  struct WhiskerMobileLengthPercentage center_y;
} WhiskerMobileClipEllipse;

/**
 * One fixed-width absolute path command. Point slots are x/y pairs: one for
 * move/line, two for quadratic, and three for cubic commands.
 */
typedef struct WhiskerMobilePathCommand {
  uint32_t kind;
  uint32_t _reserved;
  struct WhiskerMobileLengthPercentage points[6];
} WhiskerMobilePathCommand;

typedef struct WhiskerMobileClipPathCommands {
  uint32_t fill_rule;
  uint32_t _reserved;
  const struct WhiskerMobilePathCommand *commands;
  size_t command_count;
} WhiskerMobileClipPathCommands;

/**
 * One typed clip path. `payload` points to the shape selected by `shape_kind`.
 */
typedef struct WhiskerMobileClipPath {
  uint32_t reference_box;
  uint32_t shape_kind;
  const void *payload;
  size_t payload_count;
} WhiskerMobileClipPath;

/**
 * One explicit color stop shared by the additive gradient ABI subsets.
 */
typedef struct WhiskerMobileGradientStop {
  struct WhiskerMobileColor color;
  struct WhiskerMobileLengthPercentage position;
} WhiskerMobileGradientStop;

/**
 * One explicit, non-repeating elliptical radial gradient.
 */
typedef struct WhiskerMobileRadialGradient {
  struct WhiskerMobileLengthPercentage center_x;
  struct WhiskerMobileLengthPercentage center_y;
  struct WhiskerMobileLengthPercentage radius_x;
  struct WhiskerMobileLengthPercentage radius_y;
  const struct WhiskerMobileGradientStop *stops;
  size_t stop_count;
} WhiskerMobileRadialGradient;

/**
 * One non-repeating conic gradient with explicit fractional stops.
 */
typedef struct WhiskerMobileConicGradient {
  struct WhiskerMobileLengthPercentage center_x;
  struct WhiskerMobileLengthPercentage center_y;
  const struct WhiskerMobileGradientStop *stops;
  size_t stop_count;
} WhiskerMobileConicGradient;

/**
 * One typed gradient image nested in [`MobileBackgroundLayer`].
 */
typedef struct WhiskerMobileBackgroundImage {
  uint32_t kind;
  float scalar;
  const void *payload;
  size_t payload_count;
} WhiskerMobileBackgroundImage;

/**
 * One retained background layer with explicit geometry and a typed image.
 */
typedef struct WhiskerMobileBackgroundLayer {
  struct WhiskerMobileBackgroundImage image;
  struct WhiskerMobileLengthPercentage position_x;
  struct WhiskerMobileLengthPercentage position_y;
  struct WhiskerMobileLengthPercentage size_width;
  struct WhiskerMobileLengthPercentage size_height;
  uint32_t size_kind;
  uint32_t repeat_x;
  uint32_t repeat_y;
  uint32_t origin;
  uint32_t clip;
  uint32_t attachment;
  uint32_t blend_mode;
} WhiskerMobileBackgroundLayer;

typedef struct WhiskerMobileText {
  struct WhiskerStringRef text;
  const struct WhiskerStringRef *font_families;
  size_t font_family_count;
  float font_size;
  uint16_t font_weight;
  uint8_t font_style;
  uint8_t wrap;
  uint8_t word_break;
  uint8_t overflow;
  uint32_t max_lines;
  float line_height;
  float letter_spacing;
  const struct WhiskerMobileFontFeature *font_features;
  size_t font_feature_count;
  const struct WhiskerMobileFontVariation *font_variations;
  size_t font_variation_count;
  uint8_t font_optical_sizing;
  uint8_t _font_pad[7];
  struct WhiskerMobileColor color;
  float shadow_offset_x;
  float shadow_offset_y;
  float shadow_blur_radius;
  uint32_t shadow_flags;
  struct WhiskerMobileColor shadow_color;
  uint32_t decoration_flags;
  uint32_t decoration_style;
  struct WhiskerMobileColor decoration_color;
  uint32_t alignment;
  float indent_logical_pixels;
  float indent_percentage;
  uint64_t prepared_content;
  uint32_t direction;
  uint32_t _direction_pad;
} WhiskerMobileText;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

extern void *whisker_view_create(float width,
                                 float height,
                                 float scale,
                                 const struct WhiskerMobileHostCapabilities *capabilities,
                                 WhiskerMobileRequestFrameCallback request_frame,
                                 void *request_frame_data,
                                 WhiskerMobileBootstrapCallback bootstrap,
                                 void *bootstrap_data,
                                 WhiskerMobileMeasureCallback measure,
                                 void *measure_data,
                                 WhiskerMobilePresentFrameCallback present_frame,
                                 void *present_frame_data,
                                 WhiskerMobileResourceCommandCallback resource_command,
                                 void *resource_data,
                                 WhiskerMobileInvokeModuleCallback invoke_module,
                                 WhiskerMobileObserveModuleCallback observe_module,
                                 void *module_data);

extern bool whisker_view_tick(void *handle,
                              double timestamp_ms,
                              float width,
                              float height,
                              float scale);

extern void whisker_view_destroy(void *handle);

extern bool whisker_view_dispatch_event(void *handle,
                                        double timestamp_ms,
                                        uint64_t node,
                                        const uint8_t *name,
                                        size_t name_len,
                                        const struct WhiskerValueRaw *detail);

extern bool whisker_view_dispatch_pointer(void *handle,
                                          double timestamp_ms,
                                          uint32_t event,
                                          uint64_t pointer_id,
                                          uint32_t pointer_kind,
                                          float x,
                                          float y,
                                          uint32_t buttons,
                                          int16_t changed_button);

extern bool whisker_view_dispatch_module_event(void *handle,
                                               const uint8_t *module,
                                               size_t module_len,
                                               const uint8_t *event,
                                               size_t event_len,
                                               const struct WhiskerValueRaw *payload);

extern bool whisker_view_dispatch_resource_event(void *handle,
                                                 const struct WhiskerMobileResourceEvent *event);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WHISKER_MOBILE_H_ */


#ifndef WHISKER_MOBILE_ABI_ASSERTIONS_
#define WHISKER_MOBILE_ABI_ASSERTIONS_
#if defined(__cplusplus)
#define WHISKER_ABI_STATIC_ASSERT(condition, message) static_assert(condition, message)
#else
#define WHISKER_ABI_STATIC_ASSERT(condition, message) _Static_assert(condition, message)
#endif
WHISKER_ABI_STATIC_ASSERT(sizeof(WhiskerValueRaw) == 24, "WhiskerValueRaw ABI drift");
WHISKER_ABI_STATIC_ASSERT(sizeof(WhiskerKeyValueRaw) == 40, "WhiskerKeyValueRaw ABI drift");
WHISKER_ABI_STATIC_ASSERT(sizeof(WhiskerMobileHostCapabilities) == 24, "WhiskerMobileHostCapabilities ABI drift");
WHISKER_ABI_STATIC_ASSERT(sizeof(WhiskerMobileOperation) == 72, "WhiskerMobileOperation ABI drift");
WHISKER_ABI_STATIC_ASSERT(sizeof(WhiskerMobileFrame) == 72, "WhiskerMobileFrame ABI drift");
WHISKER_ABI_STATIC_ASSERT(sizeof(WhiskerMobileMeasureRequest) == 224, "WhiskerMobileMeasureRequest ABI drift");
WHISKER_ABI_STATIC_ASSERT(sizeof(WhiskerMobileMeasureResponse) == 64, "WhiskerMobileMeasureResponse ABI drift");
WHISKER_ABI_STATIC_ASSERT(sizeof(WhiskerMobileText) == 248, "WhiskerMobileText ABI drift");
WHISKER_ABI_STATIC_ASSERT(sizeof(WhiskerMobileBoxPaint) == 272, "WhiskerMobileBoxPaint ABI drift");
WHISKER_ABI_STATIC_ASSERT(sizeof(WhiskerMobileResourceCommand) == 64, "WhiskerMobileResourceCommand ABI drift");
WHISKER_ABI_STATIC_ASSERT(sizeof(WhiskerMobileResourceEvent) == 56, "WhiskerMobileResourceEvent ABI drift");
WHISKER_ABI_STATIC_ASSERT(offsetof(WhiskerValueRaw, type) == 0, "WhiskerValueRaw.type ABI drift");
WHISKER_ABI_STATIC_ASSERT(offsetof(WhiskerValueRaw, v) == 8, "WhiskerValueRaw.v ABI drift");
WHISKER_ABI_STATIC_ASSERT(offsetof(WhiskerKeyValueRaw, value) == 16, "WhiskerKeyValueRaw.value ABI drift");
WHISKER_ABI_STATIC_ASSERT(offsetof(WhiskerMobileHostCapabilities, native) == 8, "WhiskerMobileHostCapabilities.native ABI drift");
WHISKER_ABI_STATIC_ASSERT(offsetof(WhiskerMobileOperation, node) == 8, "WhiskerMobileOperation.node ABI drift");
WHISKER_ABI_STATIC_ASSERT(offsetof(WhiskerMobileOperation, integer) == 40, "WhiskerMobileOperation.integer ABI drift");
WHISKER_ABI_STATIC_ASSERT(offsetof(WhiskerMobileOperation, payload) == 56, "WhiskerMobileOperation.payload ABI drift");
WHISKER_ABI_STATIC_ASSERT(offsetof(WhiskerMobileFrame, surface) == 16, "WhiskerMobileFrame.surface ABI drift");
WHISKER_ABI_STATIC_ASSERT(offsetof(WhiskerMobileFrame, operations) == 56, "WhiskerMobileFrame.operations ABI drift");
#undef WHISKER_ABI_STATIC_ASSERT
#endif
