//! Shared native Desktop Host for Whisker.
//!
//! This crate is deliberately outside Whisker's runtime/engine dependency
//! graph. A thin OS adapter and CNG-generated `gen/<os>` executable use it as
//! the composition root: the Host owns the native window and event loop, while
//! [`whisker::RuntimeInstance`] owns application state, layout, and frame
//! production.
//!
//! The Host retains accepted semantic frames in a [`DesktopSurface`]-style
//! projection, shapes text with the platform font collection, and paints the
//! resulting display list through the target `wgpu` backend. Runtime state and
//! Taffy remain above this crate; GPU resources and prepared glyph buffers
//! remain below it.

#![cfg(any(target_os = "macos", target_os = "windows", target_os = "linux"))]
#![warn(missing_docs)]

use std::error::Error;
use std::fmt;
use std::sync::Arc;
use std::time::Instant;

use whisker::runtime::RuntimeWakeHandle;
use whisker::{Element, RuntimeInstance, SurfaceRuntime};
use whisker_engine::HostLayoutOptions;
use whisker_protocol::SurfaceId;
use whisker_style::StyleEnvironment;
use winit::application::ApplicationHandler;
use winit::dpi::{LogicalSize, PhysicalSize};
use winit::event::WindowEvent;
use winit::event_loop::{ActiveEventLoop, EventLoop, EventLoopProxy};
use winit::window::{Window, WindowAttributes, WindowId};

mod gpu;
mod paint;
mod scene;
mod surface;
mod text;

#[cfg(test)]
#[path = "../tests/host_conformance/mod.rs"]
mod host_conformance_tests;

use surface::DesktopSurface;
use text::NativeTextHost;

/// Configuration for one standalone Desktop window.
#[derive(Clone, Debug)]
pub struct DesktopAppConfig {
    /// Window and application display name.
    pub title: String,
    /// Initial logical width in points.
    pub width: f64,
    /// Initial logical height in points.
    pub height: f64,
}

impl DesktopAppConfig {
    /// Creates the default standalone window configuration.
    pub fn new(title: impl Into<String>) -> Self {
        Self {
            title: title.into(),
            width: 1024.0,
            height: 720.0,
        }
    }
}

/// Failure while creating or running the native Host.
#[derive(Debug)]
pub struct DesktopHostError(String);

impl fmt::Display for DesktopHostError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl Error for DesktopHostError {}

/// Runs a standalone Whisker application in a native Desktop window.
///
/// The application function is generated by `#[whisker::main]` and linked
/// directly into the CNG-generated executable. No FFI, serialization, or IPC
/// exists on this Desktop path.
pub fn run(config: DesktopAppConfig, application: fn() -> Element) -> Result<(), DesktopHostError> {
    let event_loop = EventLoop::<HostEvent>::with_user_event()
        .build()
        .map_err(|error| DesktopHostError(format!("create Desktop event loop: {error}")))?;
    let proxy = event_loop.create_proxy();
    let mut host = DesktopApplication::new(config, application, proxy);
    event_loop
        .run_app(&mut host)
        .map_err(|error| DesktopHostError(format!("run Desktop event loop: {error}")))
}

#[derive(Clone, Copy, Debug)]
enum HostEvent {
    RequestFrame,
}

struct DesktopApplication {
    config: DesktopAppConfig,
    application: fn() -> Element,
    proxy: EventLoopProxy<HostEvent>,
    window: Option<Arc<Window>>,
    runtime: Option<RuntimeInstance>,
    measurements: NativeTextHost,
    surface: Option<DesktopSurface>,
    viewport: PhysicalSize<u32>,
    viewport_epoch: u32,
    environment_epoch: u64,
    started_at: Instant,
    frame_failed: bool,
}

impl DesktopApplication {
    fn new(
        config: DesktopAppConfig,
        application: fn() -> Element,
        proxy: EventLoopProxy<HostEvent>,
    ) -> Self {
        Self {
            config,
            application,
            proxy,
            window: None,
            runtime: None,
            measurements: NativeTextHost::new(),
            surface: None,
            viewport: PhysicalSize::new(1, 1),
            viewport_epoch: 1,
            environment_epoch: 1,
            started_at: Instant::now(),
            frame_failed: false,
        }
    }

    fn mount(&mut self, event_loop: &ActiveEventLoop) -> Result<(), DesktopHostError> {
        if self.window.is_some() {
            return Ok(());
        }
        let attributes = WindowAttributes::default()
            .with_title(self.config.title.clone())
            .with_inner_size(LogicalSize::new(self.config.width, self.config.height));
        let window = Arc::new(
            event_loop
                .create_window(attributes)
                .map_err(|error| DesktopHostError(format!("create Desktop window: {error}")))?,
        );
        self.viewport = window.inner_size();
        let scale = window.scale_factor() as f32;
        let logical = self.viewport.to_logical::<f32>(window.scale_factor());
        let surface_id = SurfaceId::new(1).expect("the standalone surface id is non-zero");
        let surface = SurfaceRuntime::new(
            surface_id,
            StyleEnvironment::new(logical.width, logical.height, scale, 14.0),
        );
        let wake_proxy = self.proxy.clone();
        let wake = RuntimeWakeHandle::new(move || {
            let _ = wake_proxy.send_event(HostEvent::RequestFrame);
        });
        let mut runtime = RuntimeInstance::new(surface, wake);
        runtime
            .mount(self.application)
            .map_err(|error| DesktopHostError(format!("mount Whisker application: {error}")))?;
        let desktop_surface = pollster::block_on(DesktopSurface::new(window.clone(), surface_id))
            .map_err(|error| {
            DesktopHostError(format!("initialize Desktop renderer: {error}"))
        })?;
        self.surface = Some(desktop_surface);
        self.runtime = Some(runtime);
        self.window = Some(window);
        self.request_frame();
        Ok(())
    }

    fn request_frame(&self) {
        if !self.frame_failed
            && let Some(window) = &self.window
        {
            window.request_redraw();
        }
    }

    fn drive_frame(&mut self) {
        if self.frame_failed || self.viewport.width == 0 || self.viewport.height == 0 {
            return;
        }
        let (Some(window), Some(runtime), Some(surface)) =
            (&self.window, &self.runtime, &mut self.surface)
        else {
            return;
        };
        let logical = self.viewport.to_logical::<f32>(window.scale_factor());
        let environment = StyleEnvironment::new(
            logical.width,
            logical.height,
            window.scale_factor() as f32,
            14.0,
        );
        let timestamp_ms = self.started_at.elapsed().as_secs_f64() * 1000.0;
        match runtime.drive_frame(
            timestamp_ms,
            environment,
            self.environment_epoch,
            self.viewport_epoch,
            &mut self.measurements,
            surface,
            HostLayoutOptions::default(),
        ) {
            Ok(drive) => {
                if let Err(error) = surface.paint(
                    &mut self.measurements,
                    [logical.width, logical.height],
                    window.scale_factor() as f32,
                ) {
                    self.frame_failed = true;
                    eprintln!("whisker Desktop paint failed: {error}");
                    return;
                }
                if drive.needs_frame {
                    window.request_redraw();
                }
            }
            Err(error) => {
                self.frame_failed = true;
                eprintln!("whisker Desktop frame failed: {error}");
            }
        }
    }
}

impl ApplicationHandler<HostEvent> for DesktopApplication {
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        if let Err(error) = self.mount(event_loop) {
            eprintln!("{error}");
            event_loop.exit();
        }
    }

    fn user_event(&mut self, _event_loop: &ActiveEventLoop, event: HostEvent) {
        match event {
            HostEvent::RequestFrame => self.request_frame(),
        }
    }

    fn window_event(
        &mut self,
        event_loop: &ActiveEventLoop,
        window_id: WindowId,
        event: WindowEvent,
    ) {
        if self.window.as_ref().map(|window| window.id()) != Some(window_id) {
            return;
        }
        match event {
            WindowEvent::CloseRequested => {
                if let Some(runtime) = &mut self.runtime {
                    let _ = runtime.unmount();
                }
                event_loop.exit();
            }
            WindowEvent::Resized(size) => {
                self.viewport = size;
                if let Some(surface) = &mut self.surface {
                    surface.resize(size);
                }
                self.viewport_epoch = self.viewport_epoch.wrapping_add(1).max(1);
                self.environment_epoch = self.environment_epoch.wrapping_add(1).max(1);
                self.frame_failed = false;
                self.request_frame();
            }
            WindowEvent::ScaleFactorChanged { .. } => {
                if let Some(window) = &self.window {
                    self.viewport = window.inner_size();
                }
                if let Some(surface) = &mut self.surface {
                    surface.resize(self.viewport);
                }
                self.viewport_epoch = self.viewport_epoch.wrapping_add(1).max(1);
                self.environment_epoch = self.environment_epoch.wrapping_add(1).max(1);
                self.frame_failed = false;
                self.request_frame();
            }
            WindowEvent::RedrawRequested => self.drive_frame(),
            _ => {}
        }
    }
}
