package rs.whisker.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration

/**
 * KSP processor that scans the user app's compilation for every
 * `@WhiskerElement("x-tag")`- AND `@WhiskerModule("Name")`-annotated
 * Kotlin class and generates
 * `rs.whisker.runtime.generated.WhiskerModuleBehaviors`. The
 * generated `registerAll()` calls:
 *
 *  - `LynxEnv.inst().addBehavior(...)` for every `@WhiskerElement`,
 *    matching the Phase 7-Φ.H.2 element-registration path.
 *  - `WhiskerModuleRegistry.registerModuleClass(name, MyClass::class.java)`
 *    for every `@WhiskerModule`, matching the Phase 7-Φ.E.6
 *    native-module registration path.
 *
 * The generated object's symbol matches what
 * `WhiskerApplication.onCreate()` already invokes — see
 * `crates/whisker-cng/src/templates/android/app/src/main/kotlin/
 * Application.kt`. So adding the second annotation shape doesn't
 * change the consuming-app boilerplate.
 */
public class WhiskerElementProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    /** FQN of the `@WhiskerElement` annotation. Single source of truth. */
    private val elementAnnotationFqn = "rs.whisker.annotations.WhiskerElement"

    /** FQN of the `@WhiskerModule` annotation — Phase 7-Φ.E.6. */
    private val moduleAnnotationFqn = "rs.whisker.annotations.WhiskerModule"

    /**
     * KSP invokes `process` at least twice per compilation: once
     * when the user code is first processed (annotations visible)
     * and again after generated code has been integrated (annotations
     * empty). The `generated` guard avoids double-writing the file
     * on the second invocation.
     */
    private var generated = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (generated) return emptyList()

        val elementSymbols = resolver
            .getSymbolsWithAnnotation(elementAnnotationFqn)
            .filterIsInstance<KSClassDeclaration>()
            .filter { it.classKind == ClassKind.CLASS }
            .toList()

        val moduleSymbols = resolver
            .getSymbolsWithAnnotation(moduleAnnotationFqn)
            .filterIsInstance<KSClassDeclaration>()
            .filter { it.classKind == ClassKind.CLASS }
            .toList()

        // Always write the file, even when both annotation sets are
        // empty, so the user app's `Application.onCreate()` call to
        // `WhiskerModuleBehaviors.registerAll()` always resolves —
        // mirrors the iOS-side `WhiskerModuleBehaviors.swift` policy.
        writeBehavioursFile(elementSymbols, moduleSymbols)
        generated = true

        return emptyList()
    }

    private fun writeBehavioursFile(
        elements: List<KSClassDeclaration>,
        modules: List<KSClassDeclaration>,
    ) {
        // `Dependencies(aggregating = true, *sourceFiles)` makes the
        // generated file invalidate when ANY of the input source
        // files changes (add/remove of @WhiskerElement /
        // @WhiskerModule). Important for incremental compilation —
        // without `aggregating = true` KSP wouldn't re-run when a
        // new module's annotated class appears.
        val sourceFiles = (elements + modules).mapNotNull { it.containingFile }
        val dependencies = Dependencies(aggregating = true, *sourceFiles.toTypedArray())

        codeGenerator.createNewFile(
            dependencies = dependencies,
            packageName = "rs.whisker.runtime.generated",
            fileName = "WhiskerModuleBehaviors",
            extensionName = "kt",
        ).bufferedWriter().use { w ->
            w.appendLine("// AUTO-GENERATED by `whisker-ksp` (rs.whisker.ksp.WhiskerElementProcessor).")
            w.appendLine("// DO NOT EDIT — applies/removes happen automatically on next compile.")
            w.appendLine("//")
            w.appendLine("// Sourced from `@WhiskerElement(\"x-tag\")` and `@WhiskerModule(")
            w.appendLine("// \"Name\")` applications in the user app's compilation graph —")
            w.appendLine("// including module crates whose Kotlin sources are staged into")
            w.appendLine("// `gen/android/app/src/main/whisker_modules/<crate-name>/` by")
            w.appendLine("// whisker-build.")
            w.appendLine("//")
            w.appendLine("// Element registrations: ${elements.size}")
            w.appendLine("// Module  registrations: ${modules.size}")
            w.appendLine()
            w.appendLine("package rs.whisker.runtime.generated")
            w.appendLine()
            w.appendLine("import com.lynx.tasm.LynxEnv")
            w.appendLine("import com.lynx.tasm.behavior.Behavior")
            w.appendLine("import com.lynx.tasm.behavior.LynxContext")
            w.appendLine("import com.lynx.tasm.behavior.ui.LynxUI")
            w.appendLine("import rs.whisker.runtime.WhiskerModuleRegistry")
            w.appendLine("import java.util.concurrent.atomic.AtomicBoolean")
            w.appendLine()
            w.appendLine("public object WhiskerModuleBehaviors {")
            w.appendLine("    private val registered = AtomicBoolean(false)")
            w.appendLine()
            w.appendLine("    @JvmStatic")
            w.appendLine("    public fun registerAll() {")
            w.appendLine("        if (!registered.compareAndSet(false, true)) return")
            w.appendLine("        val env = LynxEnv.inst()")
            if (elements.isEmpty() && modules.isEmpty()) {
                w.appendLine("        // (no @WhiskerElement / @WhiskerModule-annotated class found)")
            }

            for (cls in elements) {
                val fqn = cls.qualifiedName?.asString()
                if (fqn == null) {
                    logger.warn(
                        "@WhiskerElement class has no qualified name; skipping",
                        cls,
                    )
                    continue
                }
                val tag = annotationStringArg(cls, elementAnnotationFqn, "tag")
                if (tag == null) {
                    logger.error(
                        "@WhiskerElement on `$fqn` has no `tag` argument",
                        cls,
                    )
                    continue
                }
                w.appendLine("        env.addBehavior(object : Behavior(\"$tag\") {")
                w.appendLine("            override fun createUI(context: LynxContext): LynxUI<*> =")
                w.appendLine("                $fqn(context)")
                w.appendLine("            override fun createUIFiber(context: LynxContext): LynxUI<*> =")
                w.appendLine("                $fqn(context)")
                w.appendLine("        })")
            }

            for (cls in modules) {
                val fqn = cls.qualifiedName?.asString()
                if (fqn == null) {
                    logger.warn(
                        "@WhiskerModule class has no qualified name; skipping",
                        cls,
                    )
                    continue
                }
                val name = annotationStringArg(cls, moduleAnnotationFqn, "name")
                if (name == null) {
                    logger.error(
                        "@WhiskerModule on `$fqn` has no `name` argument",
                        cls,
                    )
                    continue
                }
                w.appendLine("        WhiskerModuleRegistry.registerModuleClass(")
                w.appendLine("            name = \"$name\",")
                w.appendLine("            cls = $fqn::class.java,")
                w.appendLine("        )")
            }

            w.appendLine("    }")
            w.appendLine("}")
        }
    }

    /**
     * Pull a named string argument out of the `[annotationFqn]`
     * application on `cls`. Returns `null` when no matching
     * argument is found.
     */
    private fun annotationStringArg(
        cls: KSClassDeclaration,
        annotationFqn: String,
        argName: String,
    ): String? {
        for (annotation in cls.annotations) {
            val declared = annotation.annotationType.resolve().declaration
            if (declared.qualifiedName?.asString() != annotationFqn) continue
            for (arg in annotation.arguments) {
                if (arg.name?.asString() == argName || arg.name == null) {
                    return arg.value as? String
                }
            }
        }
        return null
    }
}

/**
 * Service-loaded entry point KSP uses to instantiate the processor.
 * `whisker-ksp/src/main/resources/META-INF/services/
 * com.google.devtools.ksp.processing.SymbolProcessorProvider` lists
 * this class as the discovered provider.
 */
public class WhiskerElementProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        WhiskerElementProcessor(
            codeGenerator = environment.codeGenerator,
            logger = environment.logger,
        )
}
