package rs.whisker.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration

/**
 * KSP processor that scans the user app's compilation for every
 * `@WhiskerElement("x-tag")`-annotated Kotlin class and generates
 * `rs.whisker.runtime.generated.WhiskerModuleBehaviors`. The
 * generated `registerAll()` calls `LynxEnv.inst().addBehavior(...)`
 * for each, replacing the previous whisker-build-time manual
 * Kotlin generation.
 *
 * The generated object's symbol matches what
 * `WhiskerApplication.onCreate()` already invokes — see
 * `crates/whisker-cng/src/templates/android/app/src/main/kotlin/
 * Application.kt`. So the migration is mostly invisible to the
 * consuming app's hand-written code.
 */
public class WhiskerElementProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    /** FQN of the annotation we look for. Single source of truth. */
    private val annotationFqn = "rs.whisker.annotations.WhiskerElement"

    /**
     * KSP invokes `process` at least twice per compilation: once
     * when the user code is first processed (annotations visible)
     * and again after generated code has been integrated (annotations
     * empty). The `generated` guard avoids double-writing the file
     * on the second invocation.
     */
    private var generated = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (generated) return emptyList()

        val symbols = resolver
            .getSymbolsWithAnnotation(annotationFqn)
            .filterIsInstance<KSClassDeclaration>()
            .filter { it.classKind == ClassKind.CLASS }
            .toList()

        // Always write the file, even when empty, so the user app's
        // `Application.onCreate()` call to
        // `WhiskerModuleBehaviors.registerAll()` always resolves —
        // mirrors the iOS-side `WhiskerModuleBehaviors.swift`
        // policy and matches the previous whisker-build-time
        // unconditional emission.
        writeBehavioursFile(symbols)
        generated = true

        return emptyList()
    }

    private fun writeBehavioursFile(classes: List<KSClassDeclaration>) {
        // `Dependencies(aggregating = true, *sourceFiles)` makes the
        // generated file invalidate when ANY of the input source
        // files changes (add/remove of @WhiskerElement). Important
        // for incremental compilation — without `aggregating = true`
        // KSP wouldn't re-run when a new module's annotated class
        // appears.
        val sourceFiles = classes.mapNotNull { it.containingFile }
        val dependencies = Dependencies(aggregating = true, *sourceFiles.toTypedArray())

        codeGenerator.createNewFile(
            dependencies = dependencies,
            packageName = "rs.whisker.runtime.generated",
            fileName = "WhiskerModuleBehaviors",
            extensionName = "kt",
        ).bufferedWriter().use { w ->
            w.appendLine("// AUTO-GENERATED by `whisker-ksp` (rs.whisker.ksp.WhiskerElementProcessor).")
            w.appendLine("// DO NOT EDIT — applies/removes happen automatically on next compile.")
            w.appendLine("//")
            w.appendLine("// Sourced from every `@WhiskerElement(\"x-tag\")` application in the")
            w.appendLine("// user app's compilation graph — including module crates whose")
            w.appendLine("// Kotlin sources are staged into `gen/android/app/src/main/")
            w.appendLine("// whisker_modules/<crate-name>/` by whisker-build.")
            w.appendLine("//")
            w.appendLine("// Generated count: ${classes.size}")
            w.appendLine()
            w.appendLine("package rs.whisker.runtime.generated")
            w.appendLine()
            w.appendLine("import com.lynx.tasm.LynxEnv")
            w.appendLine("import com.lynx.tasm.behavior.Behavior")
            w.appendLine("import com.lynx.tasm.behavior.LynxContext")
            w.appendLine("import com.lynx.tasm.behavior.ui.LynxUI")
            w.appendLine("import java.util.concurrent.atomic.AtomicBoolean")
            w.appendLine()
            w.appendLine("public object WhiskerModuleBehaviors {")
            w.appendLine("    private val registered = AtomicBoolean(false)")
            w.appendLine()
            w.appendLine("    @JvmStatic")
            w.appendLine("    public fun registerAll() {")
            w.appendLine("        if (!registered.compareAndSet(false, true)) return")
            w.appendLine("        val env = LynxEnv.inst()")
            if (classes.isEmpty()) {
                w.appendLine("        // (no @WhiskerElement-annotated class found)")
            }
            for (cls in classes) {
                val fqn = cls.qualifiedName?.asString()
                if (fqn == null) {
                    logger.warn(
                        "@WhiskerElement class has no qualified name; skipping",
                        cls,
                    )
                    continue
                }
                val tag = tagArgumentOf(cls)
                if (tag == null) {
                    logger.error(
                        "@WhiskerElement on `$fqn` has no `tag` argument",
                        cls,
                    )
                    continue
                }
                w.appendLine("        env.addBehavior(object : Behavior(\"$tag\") {")
                w.appendLine("            override fun createUI(context: LynxContext): LynxUI<*> =")
                w.appendLine("                $fqn(context)")
                w.appendLine("            override fun createUIFiber(context: LynxContext): LynxUI<*> =")
                w.appendLine("                $fqn(context)")
                w.appendLine("        })")
            }
            w.appendLine("    }")
            w.appendLine("}")
        }
    }

    /**
     * Pull the `tag = "x-..."` argument out of the `@WhiskerElement`
     * annotation usage on `cls`. Returns `null` when the annotation
     * is missing or the tag arg can't be resolved as a string —
     * `process` logs a diagnostic for the latter case.
     */
    private fun tagArgumentOf(cls: KSClassDeclaration): String? {
        for (annotation in cls.annotations) {
            val declared = annotation.annotationType.resolve().declaration
            if (declared.qualifiedName?.asString() != annotationFqn) continue
            for (arg in annotation.arguments) {
                if (arg.name?.asString() == "tag" || arg.name == null) {
                    return arg.value as? String
                }
            }
        }
        return null
    }
}

/**
 * Service-loaded entry point KSP uses to instantiate the processor.
 * `whisker-ksp/src/main/resources/META-INF/services/
 * com.google.devtools.ksp.processing.SymbolProcessorProvider` lists
 * this class as the discovered provider.
 */
public class WhiskerElementProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        WhiskerElementProcessor(
            codeGenerator = environment.codeGenerator,
            logger = environment.logger,
        )
}
