{
  "formatVersion": "1.1",
  "component": {
    "group": "rs.whisker",
    "module": "whisker-runtime-android",
    "version": "0.1.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "rs.whisker",
          "module": "whisker-module-android",
          "version": {
            "requires": "0.1.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-runtime-android-0.1.22.aar",
          "url": "whisker-runtime-android-0.1.22.aar",
          "size": 241992,
          "sha512": "b6c964f4f52edd3f4152cfaa2f397bcf13ad242b8288c8b5947199a58092fd02b1da5addcde3b98e0e12d2417001d30165af960680ea18ab520878f5ae48ff2f",
          "sha256": "756d990c89d35f5520923a3b8b03c1975b044b89f50ea26dc5bcaf27d2693024",
          "sha1": "aec4469a0c5881fc74cd11de29065e7d126ef86b",
          "md5": "f083ec56cfce8b097a6acf164bbd8178"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "rs.whisker",
          "module": "whisker-module-android",
          "version": {
            "requires": "0.1.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-runtime-android-0.1.22.aar",
          "url": "whisker-runtime-android-0.1.22.aar",
          "size": 241992,
          "sha512": "b6c964f4f52edd3f4152cfaa2f397bcf13ad242b8288c8b5947199a58092fd02b1da5addcde3b98e0e12d2417001d30165af960680ea18ab520878f5ae48ff2f",
          "sha256": "756d990c89d35f5520923a3b8b03c1975b044b89f50ea26dc5bcaf27d2693024",
          "sha1": "aec4469a0c5881fc74cd11de29065e7d126ef86b",
          "md5": "f083ec56cfce8b097a6acf164bbd8178"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-runtime-android-0.1.22-sources.jar",
          "url": "whisker-runtime-android-0.1.22-sources.jar",
          "size": 57701,
          "sha512": "0fa8c366be522705f60114b4828b9bddece119c490a250ab25a2524568366c7a9ec07a77dc9d497590c667a64f15b3fef1c4620aef7268fbc7f1d803aa23f51c",
          "sha256": "12140f1fb76a34ad43144cc76181bf4144f017ba8f2d382fffc70e9d10821c33",
          "sha1": "20d2fabd304e16f9d019c0b060549c9366f91a7d",
          "md5": "b672e2fb25b5712eeb3dbc878f62f1bc"
        }
      ]
    }
  ]
}
