{
  "formatVersion": "1.1",
  "component": {
    "group": "rs.whisker",
    "module": "ksp",
    "version": "0.1.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.17.jar",
          "url": "ksp-0.1.17.jar",
          "size": 11123,
          "sha512": "046b897b14362e5c2ec8fa11bd77f7397c0a908a9fda5f6a3dcf4b749d4e036d84547a10e0947469aef19a1cffce9af022ee7edc735d2e40ff49c6814f745485",
          "sha256": "fc6009a30aca0ec0472361430f8b7c8213d73af03a645c1d3be6e2821e12dc89",
          "sha1": "ea0bd450b18e413ec417cce8e54463dd28992247",
          "md5": "24e5d24ef6b01f925b08b93aa10066a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.0.21-1.0.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.17.jar",
          "url": "ksp-0.1.17.jar",
          "size": 11123,
          "sha512": "046b897b14362e5c2ec8fa11bd77f7397c0a908a9fda5f6a3dcf4b749d4e036d84547a10e0947469aef19a1cffce9af022ee7edc735d2e40ff49c6814f745485",
          "sha256": "fc6009a30aca0ec0472361430f8b7c8213d73af03a645c1d3be6e2821e12dc89",
          "sha1": "ea0bd450b18e413ec417cce8e54463dd28992247",
          "md5": "24e5d24ef6b01f925b08b93aa10066a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ksp-0.1.17-sources.jar",
          "url": "ksp-0.1.17-sources.jar",
          "size": 5750,
          "sha512": "991e38910a2cffa047fdf585edce7c12d50c3d704519395c9f1e6601643ac41069e8d59b0cb71b82bb0e981ca957753f9abf5deb7efa95930e9598064e5cec39",
          "sha256": "f81a5b02bac797bd1ba7c86f476d5e524d0b419573f307c5fb45c742eb3707e5",
          "sha1": "202472b5ac244fce545e5239063c603ccc23c4b1",
          "md5": "3a1cee4a45bafc274846d0db2d1761c4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ksp-0.1.17-javadoc.jar",
          "url": "ksp-0.1.17-javadoc.jar",
          "size": 261,
          "sha512": "aa15b1699103e9001a1dfedbeb97f469db6b904183998e7938a3f230c007d4ec10f19ba04de2c7071d0b4b4c46984a8ef2910ea4de63b84cd76c2f420d4dd3d3",
          "sha256": "399baab507787eee907506076ce7164a3a249c635b74caa1142151a1e6f440d9",
          "sha1": "656e3d11c6fb2f2ecd58b856f85ae2fffca9c4f5",
          "md5": "d4a673e537430ffaad51ff790c677e7e"
        }
      ]
    }
  ]
}
