{
  "formatVersion": "1.1",
  "component": {
    "group": "rs.whisker",
    "module": "ksp",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.4.jar",
          "url": "ksp-0.1.4.jar",
          "size": 11123,
          "sha512": "adc18c86e7a42ee17daa5fed6806c6385be8956e8a57bd9b9a9f4d9a0868c4d15ba059b81190f53aeb49b91b3689e573610dcf4391904cd4bac270cc89314260",
          "sha256": "3c371b326aa6ee518bc8f5479159ab5cf752deb16b8a9924bd6bc7fe4af54035",
          "sha1": "588710e9e9a47e47a87362f7982014b28815b491",
          "md5": "f36e840b03206c1ed7327393b8be1764"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.0.21-1.0.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.4.jar",
          "url": "ksp-0.1.4.jar",
          "size": 11123,
          "sha512": "adc18c86e7a42ee17daa5fed6806c6385be8956e8a57bd9b9a9f4d9a0868c4d15ba059b81190f53aeb49b91b3689e573610dcf4391904cd4bac270cc89314260",
          "sha256": "3c371b326aa6ee518bc8f5479159ab5cf752deb16b8a9924bd6bc7fe4af54035",
          "sha1": "588710e9e9a47e47a87362f7982014b28815b491",
          "md5": "f36e840b03206c1ed7327393b8be1764"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ksp-0.1.4-sources.jar",
          "url": "ksp-0.1.4-sources.jar",
          "size": 5750,
          "sha512": "cd965c89c142dcd7816b1deaa74c64466991c64c7d0fbb1a61be9c28f3f714945dd91810471bcc15c5d87f29bce292586f1f8c2506ea14b1bf553c6232a023cc",
          "sha256": "ea62af1c1f8d92c97066855d3da0aa364281fbef5157d0231c4fc95f64a1031e",
          "sha1": "53ad47604e2ec7ecb49cee2f3273927ae1e85dbd",
          "md5": "c02032ba076136f333e60bfaa6fa8f4f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ksp-0.1.4-javadoc.jar",
          "url": "ksp-0.1.4-javadoc.jar",
          "size": 261,
          "sha512": "746e79249008c777fd027b2fd7dace8a6507d399e47096cf8c9d9afc159a5d5f91a8e2e7fd5645f4b5c25d26e65129194b26aa655684c0acc9f5d11460f49c2f",
          "sha256": "2bc7e34439c7ee73488fdbde50e2f86612cbe0c34f0fdc328c1810762543c21a",
          "sha1": "f93b0551e406db522fa6d87f77787d7bcf2c0b4c",
          "md5": "d02b8a736f6a4c50b4dfaeeb115b0526"
        }
      ]
    }
  ]
}
