//! Build-time codegen for the full-gallery example.
//!
//! Walks `../vendor/lucide/icons/*.svg` (same source `whisker-icons`'
//! own build.rs reads) and emits a single Rust source file under
//! `$OUT_DIR/gallery.rs` that the example's `lib.rs` `include!()`s.
//! The generated file contains:
//!
//! ```ignore
//! pub fn icons_grid() -> ::whisker::runtime::view::Element {
//!     ::whisker::render! {
//!         view(style: GRID_STYLE) {
//!             tile(label: "AArrowDown", svg: ::whisker_icons::lucide::AArrowDown)
//!             tile(label: "AArrowUp",   svg: ::whisker_icons::lucide::AArrowUp)
//!             // … ~1700 tile() lines …
//!         }
//!     }
//! }
//! ```
//!
//! ## Why one big `render!` instead of `list(each: …)` / a loop
//!
//! Whisker's `render!` macro is a closed proc-macro: it parses its
//! body as a sequence of `IDENT(kwargs?) { … }?` nodes and rejects
//! bare Rust expressions, including `for` loops and `include!()`
//! calls inside the body. The render-props `list(...)` would work
//! and even virtualise, but Whisker drives Lynx's *decoupled* list
//! container which reads its layout config from the structured
//! `list-container-info` MAP — Whisker's `list_type` / `column_count`
//! setters target the older `AbsLynxList` direct-prop path that
//! the decoupled container ignores, so a multi-column grid isn't
//! reachable through the Rust API yet.
//!
//! The remaining option is to fan the tiles out at *macro-input*
//! time. That can't happen inside `render!`'s body (no
//! `include!` recursion), but it works at the *enclosing* module
//! level: `include!()` here pastes the entire `icons_grid()` fn
//! verbatim into the module, and the `render!` invocation that
//! lives inside it then sees a literal 1700-child node list. Slow
//! to compile, but lets us render every Lucide icon at once.
//!
//! ## Two build.rs walks
//!
//! `whisker-icons`'s own build.rs emits the per-icon `pub const`
//! tree-shakable surface. This walk is independent — the example
//! references every const so all 1700 end up in the binary, which
//! is the only way "show me all icons" can work. Keeping the slice
//! out of `whisker-icons` itself means a downstream consumer that
//! uses 5 icons doesn't accidentally pull all 1700 because a
//! transitive slice mentioned them.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let vendor_dir = PathBuf::from("../vendor/lucide/icons");
    println!("cargo:rerun-if-changed=../vendor/lucide/icons");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let out_path = out_dir.join("gallery.rs");

    let mut entries: Vec<_> = fs::read_dir(&vendor_dir)
        .unwrap_or_else(|e| {
            panic!(
                "failed to read {}: {e}. Did `whisker-icons/vendor/lucide` get clobbered?",
                vendor_dir.display()
            )
        })
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().and_then(|s| s.to_str()) == Some("svg"))
        .collect();
    entries.sort_by_key(|e| e.path());

    let mut out = String::new();
    out.push_str("// @generated by build.rs from ../vendor/lucide/icons/*.svg.\n");
    out.push_str("// Do not edit by hand — re-run `cargo build` to regenerate.\n\n");
    out.push_str("/// Total number of vendored Lucide icons. Updated by build.rs;\n");
    out.push_str("/// surfaced in the gallery's header text.\n");
    out.push_str(&format!(
        "pub const ICON_COUNT: usize = {};\n\n",
        entries.len()
    ));
    out.push_str("pub fn icons_grid() -> ::whisker::runtime::view::Element {\n");
    out.push_str(
        "    let grid_style = \"display: flex; flex-direction: row; flex-wrap: wrap; \
         padding-left: 8px; padding-right: 8px;\";\n",
    );
    out.push_str("    ::whisker::render! {\n");
    out.push_str("        view(style: grid_style) {\n");
    for entry in &entries {
        let stem = entry
            .path()
            .file_stem()
            .expect("svg filename has stem")
            .to_string_lossy()
            .into_owned();
        let name = pascal_case(&stem);
        out.push_str(&format!(
            "            tile(label: \"{name}\", svg: ::whisker_icons::lucide::{name})\n"
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    fs::write(&out_path, out).unwrap_or_else(|e| panic!("write {}: {e}", out_path.display()));
}

/// `chevron-right` → `ChevronRight`. Same rule as the upstream
/// `whisker-icons` build.rs — has to stay in sync so the const-path
/// lookups resolve. Lucide names are pure kebab-case ASCII so this
/// is the trivial form.
fn pascal_case(kebab: &str) -> String {
    let mut s = String::with_capacity(kebab.len());
    let mut next_upper = true;
    for c in kebab.chars() {
        if c == '-' {
            next_upper = true;
        } else if next_upper {
            for u in c.to_uppercase() {
                s.push(u);
            }
            next_upper = false;
        } else {
            s.push(c);
        }
    }
    s
}
