//! Native macOS Host for Whisker.
//!
//! This crate is deliberately outside Whisker's runtime/engine dependency
//! graph. A CNG-generated `gen/macos` executable uses it as the composition
//! root: the Host owns the native window and event loop, while
//! [`whisker::RuntimeInstance`] owns application state, layout, and frame
//! production.
//!
//! The first implementation establishes the lifecycle boundary only. It
//! accepts and validates frame packets and uses deterministic mock intrinsic
//! text metrics. Native text shaping and GPU painting replace those two seams
//! without changing application bootstrap or frame scheduling.

#![warn(missing_docs)]

use std::error::Error;
use std::fmt;
use std::time::Instant;

use whisker::runtime::RuntimeWakeHandle;
use whisker::{Element, RuntimeInstance, SurfaceRuntime};
use whisker_engine::whisker_layout::LayoutSize;
use whisker_engine::{HostLayoutOptions, MeasurementHost, RecordingRenderer};
use whisker_protocol::{
    AvailableSpace, MeasuredSize, MeasurementMetrics, MeasurementPayload, MeasurementRequest,
    MeasurementResponse, PreparedContentId, SurfaceId,
};
use whisker_style::StyleEnvironment;
use winit::application::ApplicationHandler;
use winit::dpi::{LogicalSize, PhysicalSize};
use winit::event::WindowEvent;
use winit::event_loop::{ActiveEventLoop, EventLoop, EventLoopProxy};
use winit::window::{Window, WindowAttributes, WindowId};

/// Configuration for one standalone macOS window.
#[derive(Clone, Debug)]
pub struct MacosAppConfig {
    /// Window and application display name.
    pub title: String,
    /// Initial logical width in points.
    pub width: f64,
    /// Initial logical height in points.
    pub height: f64,
}

impl MacosAppConfig {
    /// Creates the default standalone window configuration.
    pub fn new(title: impl Into<String>) -> Self {
        Self {
            title: title.into(),
            width: 1024.0,
            height: 720.0,
        }
    }
}

/// Failure while creating or running the native Host.
#[derive(Debug)]
pub struct MacosHostError(String);

impl fmt::Display for MacosHostError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl Error for MacosHostError {}

/// Runs a standalone Whisker application in a native macOS window.
///
/// The application function is generated by `#[whisker::main]` and linked
/// directly into the CNG-generated executable. No FFI, serialization, or IPC
/// exists on this Desktop path.
pub fn run(config: MacosAppConfig, application: fn() -> Element) -> Result<(), MacosHostError> {
    let event_loop = EventLoop::<HostEvent>::with_user_event()
        .build()
        .map_err(|error| MacosHostError(format!("create macOS event loop: {error}")))?;
    let proxy = event_loop.create_proxy();
    let mut host = MacosApplication::new(config, application, proxy);
    event_loop
        .run_app(&mut host)
        .map_err(|error| MacosHostError(format!("run macOS event loop: {error}")))
}

#[derive(Clone, Copy, Debug)]
enum HostEvent {
    RequestFrame,
}

struct MacosApplication {
    config: MacosAppConfig,
    application: fn() -> Element,
    proxy: EventLoopProxy<HostEvent>,
    window: Option<Window>,
    runtime: Option<RuntimeInstance>,
    measurements: MockMeasurementHost,
    frames: Option<RecordingRenderer>,
    viewport: PhysicalSize<u32>,
    viewport_epoch: u32,
    environment_epoch: u64,
    started_at: Instant,
    frame_failed: bool,
}

impl MacosApplication {
    fn new(
        config: MacosAppConfig,
        application: fn() -> Element,
        proxy: EventLoopProxy<HostEvent>,
    ) -> Self {
        Self {
            config,
            application,
            proxy,
            window: None,
            runtime: None,
            measurements: MockMeasurementHost,
            frames: None,
            viewport: PhysicalSize::new(1, 1),
            viewport_epoch: 1,
            environment_epoch: 1,
            started_at: Instant::now(),
            frame_failed: false,
        }
    }

    fn mount(&mut self, event_loop: &ActiveEventLoop) -> Result<(), MacosHostError> {
        if self.window.is_some() {
            return Ok(());
        }
        let attributes = WindowAttributes::default()
            .with_title(self.config.title.clone())
            .with_inner_size(LogicalSize::new(self.config.width, self.config.height));
        let window = event_loop
            .create_window(attributes)
            .map_err(|error| MacosHostError(format!("create macOS window: {error}")))?;
        self.viewport = window.inner_size();
        let scale = window.scale_factor() as f32;
        let logical = self.viewport.to_logical::<f32>(window.scale_factor());
        let surface_id = SurfaceId::new(1).expect("the standalone surface id is non-zero");
        let surface = SurfaceRuntime::new(
            surface_id,
            StyleEnvironment::new(logical.width, logical.height, scale, 14.0),
        );
        let wake_proxy = self.proxy.clone();
        let wake = RuntimeWakeHandle::new(move || {
            let _ = wake_proxy.send_event(HostEvent::RequestFrame);
        });
        let mut runtime = RuntimeInstance::new(surface, wake);
        runtime
            .mount(self.application)
            .map_err(|error| MacosHostError(format!("mount Whisker application: {error}")))?;
        self.frames = Some(RecordingRenderer::new(surface_id));
        self.runtime = Some(runtime);
        self.window = Some(window);
        self.request_frame();
        Ok(())
    }

    fn request_frame(&self) {
        if !self.frame_failed
            && let Some(window) = &self.window
        {
            window.request_redraw();
        }
    }

    fn drive_frame(&mut self) {
        if self.frame_failed {
            return;
        }
        let (Some(window), Some(runtime), Some(frames)) =
            (&self.window, &self.runtime, &mut self.frames)
        else {
            return;
        };
        let logical = self.viewport.to_logical::<f32>(window.scale_factor());
        let timestamp_ms = self.started_at.elapsed().as_secs_f64() * 1000.0;
        match runtime.drive_frame(
            timestamp_ms,
            LayoutSize::new(logical.width, logical.height),
            self.environment_epoch,
            self.viewport_epoch,
            &mut self.measurements,
            frames,
            HostLayoutOptions::default(),
        ) {
            Ok(drive) if drive.needs_frame => window.request_redraw(),
            Ok(_) => {}
            Err(error) => {
                self.frame_failed = true;
                eprintln!("whisker macOS frame failed: {error}");
            }
        }
    }
}

impl ApplicationHandler<HostEvent> for MacosApplication {
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        if let Err(error) = self.mount(event_loop) {
            eprintln!("{error}");
            event_loop.exit();
        }
    }

    fn user_event(&mut self, _event_loop: &ActiveEventLoop, event: HostEvent) {
        match event {
            HostEvent::RequestFrame => self.request_frame(),
        }
    }

    fn window_event(
        &mut self,
        event_loop: &ActiveEventLoop,
        window_id: WindowId,
        event: WindowEvent,
    ) {
        if self.window.as_ref().map(Window::id) != Some(window_id) {
            return;
        }
        match event {
            WindowEvent::CloseRequested => {
                if let Some(runtime) = &mut self.runtime {
                    let _ = runtime.unmount();
                }
                event_loop.exit();
            }
            WindowEvent::Resized(size) => {
                self.viewport = size;
                self.viewport_epoch = self.viewport_epoch.wrapping_add(1).max(1);
                self.environment_epoch = self.environment_epoch.wrapping_add(1).max(1);
                self.frame_failed = false;
                self.request_frame();
            }
            WindowEvent::ScaleFactorChanged { .. } => {
                if let Some(window) = &self.window {
                    self.viewport = window.inner_size();
                }
                self.viewport_epoch = self.viewport_epoch.wrapping_add(1).max(1);
                self.environment_epoch = self.environment_epoch.wrapping_add(1).max(1);
                self.frame_failed = false;
                self.request_frame();
            }
            WindowEvent::RedrawRequested => self.drive_frame(),
            _ => {}
        }
    }
}

/// Deterministic placeholder for the native CoreText-backed provider.
///
/// Keeping this behind `MeasurementHost` lets the application reach final
/// layout and frame generation today. The next renderer slice replaces only
/// this type with shaped CoreText/cosmic-text metrics and retained glyph data.
struct MockMeasurementHost;

impl MeasurementHost for MockMeasurementHost {
    type Error = std::convert::Infallible;

    fn measure_batch(
        &mut self,
        _surface: SurfaceId,
        requests: &[MeasurementRequest],
        responses: &mut Vec<MeasurementResponse>,
    ) -> Result<(), Self::Error> {
        responses.extend(requests.iter().map(|request| {
            let (mut width, mut height, baseline) = match &request.payload {
                MeasurementPayload::Text(text) => {
                    let line_height = match text.style.line_height {
                        whisker_protocol::MeasureLineHeight::Normal => text.style.font_size * 1.2,
                        whisker_protocol::MeasureLineHeight::LogicalPixels(value) => value,
                    };
                    let natural_width = text.text.chars().count() as f32
                        * (text.style.font_size * 0.55 + text.style.letter_spacing);
                    let available_width = match request.constraints.available_space[0] {
                        AvailableSpace::Definite(value) => value.max(0.0),
                        AvailableSpace::MinContent | AvailableSpace::MaxContent => natural_width,
                    };
                    let width = natural_width.min(available_width);
                    let lines = if width > 0.0 {
                        (natural_width / width).ceil().max(1.0)
                    } else {
                        1.0
                    };
                    (width, line_height * lines, Some(text.style.font_size * 0.8))
                }
                _ => (0.0, 0.0, None),
            };
            if let Some(known) = request.constraints.known_dimensions[0] {
                width = known;
            }
            if let Some(known) = request.constraints.known_dimensions[1] {
                height = known;
            }
            MeasurementResponse::Ready {
                key: request.key,
                environment_epoch: request.environment_epoch,
                metrics: MeasurementMetrics {
                    size: MeasuredSize::new(width.max(0.0), height.max(0.0)),
                    first_baseline: baseline,
                    last_baseline: baseline,
                    overflow: None,
                    prepared_content: PreparedContentId::new(request.key.get()),
                },
            }
        }));
        Ok(())
    }
}
