{
  "formatVersion": "1.1",
  "component": {
    "group": "rs.whisker",
    "module": "whisker-module-android",
    "version": "0.1.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-module-android-0.1.24.aar",
          "url": "whisker-module-android-0.1.24.aar",
          "size": 205945,
          "sha512": "cc494f7f1689cfb747895825b3457f26744fe9b6b044fe8b62c530e08ffab7f083e92bf0f05544be2846136a416d496f4b6a1c885f5680924f096e8ebbaa2f56",
          "sha256": "b5143badafca90ee16c41c92794126c96caef039f761e955e00d7e5421c17c48",
          "sha1": "fa2dd03670c7d11d1fb41fb5e0e1e9fc38ed39fc",
          "md5": "ce620236247a3cb118fafa7fe9bcd6f5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-module-android-0.1.24.aar",
          "url": "whisker-module-android-0.1.24.aar",
          "size": 205945,
          "sha512": "cc494f7f1689cfb747895825b3457f26744fe9b6b044fe8b62c530e08ffab7f083e92bf0f05544be2846136a416d496f4b6a1c885f5680924f096e8ebbaa2f56",
          "sha256": "b5143badafca90ee16c41c92794126c96caef039f761e955e00d7e5421c17c48",
          "sha1": "fa2dd03670c7d11d1fb41fb5e0e1e9fc38ed39fc",
          "md5": "ce620236247a3cb118fafa7fe9bcd6f5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-module-android-0.1.24-sources.jar",
          "url": "whisker-module-android-0.1.24-sources.jar",
          "size": 39699,
          "sha512": "c86aedf87d4d878a3eb5740e8f9486d3c1f4e338d47ac77ef75880b2e4cd0b14dc832de125b41ec1158a2b179170163522708b3810713807011e1bf6f72296a4",
          "sha256": "0a1bcbc6c01880a98d96f7594e9ea325dcdc310367c34d9afd678fbcf7257a32",
          "sha1": "62f6e2289a52f5f51b11d65ce2166da82ec2cc70",
          "md5": "73c0b9e2c20d3859c155020bb70ce5f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-module-android-0.1.24-javadoc.jar",
          "url": "whisker-module-android-0.1.24-javadoc.jar",
          "size": 666209,
          "sha512": "34a96414926309fc0d388cb6bfbca3dc00f2753bacca5770f27e21cc01dc7b2fceeb19b39e5527ea128118eef16babdb402f61eb49d5a04d119151d4d833c076",
          "sha256": "b6acd2e1fc6c893b5523122a5c4d10ce6b53822373d18b4bcba12029cd2ab6ed",
          "sha1": "d332a5f6a547898db149c865ba86eedab649722e",
          "md5": "014fb5b5df627b6ac93466877108b275"
        }
      ]
    }
  ]
}
