// `whisker-module-codegen` — Swift executable that scans .swift
// source files for class declarations marked `@WhiskerModule` and emits
// `<TargetName>+Generated.swift` containing the matching DSL-module
// registration calls.
//
// Invoked at SwiftPM build time by `WhiskerModuleCodegenPlugin`
// (under `../../Plugins/`). The plugin passes:
//   --target-name <name>        ← the SwiftPM target being built
//   --output <path>             ← target for the generated .swift
//   <input1.swift> <input2.swift> …
//
// Apple's SwiftSyntax parses each input file into an AST; we walk it to find
// the explicit marker, matching Rust and Android module discovery.
//
// Output is per-module: each module's SwiftPM target owns its
// registration code (`_whiskerRegisterModules_<TargetName>`), and the
// whisker-build-generated aggregator imports + calls every per-module
// register fn from its own `WhiskerModuleBehaviors.registerAll()`.

import Foundation
import SwiftSyntax
import SwiftParser

// ---- CLI argument parsing ----------------------------------------------------

struct Args {
    let targetName: String
    /// Cargo crate name (e.g. "whisker-hello-element"), passed from
    /// the SwiftPM plugin via `context.package.displayName`. Used as
    /// the element namespace so two modules' identical local names
    /// don't collide in the Whisker registry.
    let crateName: String
    let outputPath: String
    let inputs: [String]
}

func parseArgs(_ argv: [String]) -> Args? {
    var target: String?
    var crate: String?
    var output: String?
    var inputs: [String] = []
    var i = 1 // skip argv[0]
    while i < argv.count {
        switch argv[i] {
        case "--target-name":
            guard i + 1 < argv.count else { return nil }
            target = argv[i + 1]
            i += 2
        case "--crate-name":
            guard i + 1 < argv.count else { return nil }
            crate = argv[i + 1]
            i += 2
        case "--output":
            guard i + 1 < argv.count else { return nil }
            output = argv[i + 1]
            i += 2
        default:
            inputs.append(argv[i])
            i += 1
        }
    }
    guard let target, let crate, let output else { return nil }
    return Args(
        targetName: target,
        crateName: crate,
        outputPath: output,
        inputs: inputs
    )
}

// ---- AST walker --------------------------------------------------------------

/// One discovered `@WhiskerModule` declaration.
/// The codegen emits a registration block that instantiates the class,
/// assigns its fully-qualified name, and calls `registerWithWhisker()`.
/// The shared registrar handles both native-View and view-less modules.
struct DSLModuleHit {
    let className: String
}

final class WhiskerAnnotationCollector: SyntaxVisitor {
    var dslModules: [DSLModuleHit] = []

    override func visit(_ node: ClassDeclSyntax) -> SyntaxVisitorContinueKind {
        let marked = node.attributes.contains { element in
            guard let attribute = element.as(AttributeSyntax.self) else { return false }
            if let identifier = attribute.attributeName.as(IdentifierTypeSyntax.self) {
                return identifier.name.text == "WhiskerModule"
            }
            if let member = attribute.attributeName.as(MemberTypeSyntax.self) {
                return member.name.text == "WhiskerModule"
            }
            return false
        }
        if marked {
            dslModules.append(DSLModuleHit(className: node.name.text))
        }
        return .skipChildren
    }
}

// ---- Codegen -----------------------------------------------------------------

func render(
    targetName: String,
    crateName: String,
    dslModules: [DSLModuleHit]
) -> String {
    // Deterministic order — sort so two builds with the same input
    // produce byte-identical output (helps SwiftPM's incremental-
    // rebuild fingerprinting).
    let sortedDSLModules = dslModules.sorted { $0.className < $1.className }

    let registerFn = "_whiskerRegisterModules_\(targetName)"

    var out = """
        // AUTO-GENERATED by `whisker-module-codegen` (SwiftPM build plugin).
        // DO NOT EDIT — re-runs automatically on next `swift build`.
        //
        // Sourced from `@WhiskerModule` declarations in the `\(targetName)`
        // SwiftPM target's source set. Each view-bearing module registers
        // its generated RFC0004 name with the lightweight native View
        // registry. Each module package owns its own copy of this
        // generated file; the whisker-build-generated aggregator
        // imports every module and calls each per-target register fn
        // from a top-level `WhiskerModuleBehaviors.registerAll()`.
        //
        // Sibling of Android's `rs.whisker.ksp.WhiskerModuleProcessor`.
        //
        // DSL Module registrations: \(sortedDSLModules.count)

        import Foundation
        import WhiskerModule

        /// Per-target registration entry point. The aggregator
        /// (`gen/ios/whisker_modules/Sources/WhiskerModules/RegisterAll.swift`,
        /// emitted by whisker-build) imports the target's SwiftPM
        /// module and calls this fn from
        /// `WhiskerModuleBehaviors.registerAll()`.
        ///
        /// Top-level fn rather than a class method so it doesn't
        /// shadow the aggregator's `WhiskerModuleBehaviors` symbol
        /// when both modules end up in the same compiled product.
        public func \(registerFn)() {

        """

    if sortedDSLModules.isEmpty {
        out += "    // (no @WhiskerModule declaration found)\n"
    }
    // Every `@WhiskerModule` declaration uses the same explicit Host
    // registration entry point. Element definitions remain string-declared;
    // generated code only performs discovery and registration.
    if !sortedDSLModules.isEmpty {
        out += "        // ---- DSL modules (Phase L-3) ----\n"
    }
    let tagPrefix = "\(crateName):"
    for hit in sortedDSLModules {
        let instance = "_whiskerDSLInstance_\(hit.className)"
        out += """
                do {
                    let module = \(instance)
                    let def = module.definitionLazy
                    guard let name = def.name else {
                        preconditionFailure("ModuleDefinition requires Name")
                    }
                        // Phase L-2c — every DSL module records its
                        // fully-qualified name so `sendEvent` /
                        // observer-hook routing can find it.
                        let qname = name.contains("/") ? name : "\(tagPrefix)" + name
                        module.qualifiedName = qname
                    module.registerWithWhisker()
                }

            """
    }

    // Close the register fn.
    out += """
        }

        """

    // A stable top-level instance keeps the module alive for the lifetime of
    // the process. Dispatch is installed by WhiskerView/runtime integration,
    // not through a generated platform-specific C entry point.
    for hit in sortedDSLModules {
        let instance = "_whiskerDSLInstance_\(hit.className)"
        out += """
            // Top-level instance for `\(hit.className)`. Swift globals are
            // lazily initialised when the registration function first uses it.
            private let \(instance) = \(hit.className)()

        """
    }
    return out
}

// ---- Main --------------------------------------------------------------------

guard let args = parseArgs(CommandLine.arguments) else {
    FileHandle.standardError.write(Data(
        "usage: whisker-module-codegen --target-name <name> --crate-name <pkg> --output <path> <input.swift>...\n".utf8
    ))
    exit(2)
}

let collector = WhiskerAnnotationCollector(viewMode: .sourceAccurate)
for input in args.inputs {
    let source: String
    do {
        source = try String(contentsOfFile: input, encoding: .utf8)
    } catch {
        FileHandle.standardError.write(Data(
            "whisker-module-codegen: cannot read \(input): \(error)\n".utf8
        ))
        exit(1)
    }
    let tree = Parser.parse(source: source)
    collector.walk(tree)
}

let generated = render(
    targetName: args.targetName,
    crateName: args.crateName,
    dslModules: collector.dslModules
)
do {
    try generated.write(toFile: args.outputPath, atomically: true, encoding: .utf8)
} catch {
    FileHandle.standardError.write(Data(
        "whisker-module-codegen: cannot write \(args.outputPath): \(error)\n".utf8
    ))
    exit(1)
}
