{
  "formatVersion": "1.1",
  "component": {
    "group": "rs.whisker",
    "module": "whisker-runtime-android",
    "version": "0.1.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "rs.whisker",
          "module": "whisker-module-android",
          "version": {
            "requires": "0.1.18"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-android",
          "version": {
            "requires": "4.0.1-whisker.1"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-base-android",
          "version": {
            "requires": "4.0.1-whisker.1"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-trace-android",
          "version": {
            "requires": "4.0.1-whisker.1"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-service-api-android",
          "version": {
            "requires": "4.0.1-whisker.1"
          }
        },
        {
          "group": "org.lynxsdk.lynx",
          "module": "primjs",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-runtime-android-0.1.18.aar",
          "url": "whisker-runtime-android-0.1.18.aar",
          "size": 14102,
          "sha512": "0a84c6a3f9b1770dff5868ad10922e179e6229a27c48b04bbaad1e51a7947606ee47eae109905d7c1b6e92c19fef02173d640b1c4417cdd2fb5c412a65c2a9db",
          "sha256": "e84db914b2513b7f793a76c949b61f9f6216759e34dea1cb4fea71177f4af47e",
          "sha1": "f778aa27b643d04c1bca0af6578aa3b98cad9573",
          "md5": "af68e97b320345ae821add33a0fabf3e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "rs.whisker",
          "module": "whisker-module-android",
          "version": {
            "requires": "0.1.18"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-android",
          "version": {
            "requires": "4.0.1-whisker.1"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-base-android",
          "version": {
            "requires": "4.0.1-whisker.1"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-trace-android",
          "version": {
            "requires": "4.0.1-whisker.1"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-service-api-android",
          "version": {
            "requires": "4.0.1-whisker.1"
          }
        },
        {
          "group": "org.lynxsdk.lynx",
          "module": "primjs",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-runtime-android-0.1.18.aar",
          "url": "whisker-runtime-android-0.1.18.aar",
          "size": 14102,
          "sha512": "0a84c6a3f9b1770dff5868ad10922e179e6229a27c48b04bbaad1e51a7947606ee47eae109905d7c1b6e92c19fef02173d640b1c4417cdd2fb5c412a65c2a9db",
          "sha256": "e84db914b2513b7f793a76c949b61f9f6216759e34dea1cb4fea71177f4af47e",
          "sha1": "f778aa27b643d04c1bca0af6578aa3b98cad9573",
          "md5": "af68e97b320345ae821add33a0fabf3e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-runtime-android-0.1.18-sources.jar",
          "url": "whisker-runtime-android-0.1.18-sources.jar",
          "size": 9431,
          "sha512": "3a14a59afa6cd54660226821daf1bc81e66a3c4b4ec8fd54dbc4d27c08cbf50d80ccfd03aeb6c601338577b18f0e0509bbc5229145d0d5dd94b5ea344d08e5c7",
          "sha256": "bfc4d2843c8b35584de062cfeadd4b546364f3114bc5d801f0ae41ac3e0aae3c",
          "sha1": "7160ac5727011fdd366e06c2913640c3e5ba51e6",
          "md5": "305b444a3b4abc54be821aeb91a13bef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-runtime-android-0.1.18-javadoc.jar",
          "url": "whisker-runtime-android-0.1.18-javadoc.jar",
          "size": 345740,
          "sha512": "010c7fed188b8b5dfaad8bc2ae5542ef6d2df6ee36f83ad21d467c93987555f67b306fbfab88ab7c7bea71cc494538d09ecd0eed1786edf8603c329025601ac2",
          "sha256": "a668f1a3abb83dc9e3839b670e796e50eaed3e997f6ce918d74ee437b1524d05",
          "sha1": "42c9a6cdc788836fe2f1ca1cfb2377b8f3ab61d6",
          "md5": "5564d1a9b3de58275d21a016fa3820bf"
        }
      ]
    }
  ]
}
