//! `whisker-local-store` — reference Whisker native module.
//!
//! Persistent string-keyed key-value store backed by:
//!   - **iOS**: `UserDefaults.standard`
//!   - **Android**: `SharedPreferences` (named `"WhiskerLocalStore"`)
//!
//! Both platforms persist across app launches but don't sync across
//! devices. For app-level preferences, small state, and similar
//! data — not for large blobs (use a real file API or database for
//! anything > ~1 MB per entry).
//!
//! The module is also the documented template for first-party
//! Whisker native modules. Phase 7-Φ.F shape:
//!
//!   1. A `-sys` trait annotated with
//!      `#[whisker::native_module(name = "...")]`. Every method
//!      takes `args: Vec<WhiskerValue>` and returns `WhiskerValue`
//!      — no magic, no type coercion. The proc macro emits a unit
//!      struct + thin pass-through methods that call
//!      [`whisker::native_module::invoke`] verbatim.
//!
//!   2. A hand-written typed wrapper on top — `pub struct
//!      WhiskerLocalStore;` with methods like
//!      `fn save(key: String, value: String) -> Result<bool, _>`
//!      that build the `Vec<WhiskerValue>`, dispatch through the
//!      sys trait, and lift the `WhiskerValue` return into the
//!      typed result. This is where application-specific
//!      validation, defaults, and ergonomic types live; the
//!      proc macro stays unaware of any of it.
//!
//! Each platform-side class (`WhiskerLocalStoreImpl`) implements
//! the same `[WhiskerValue]` → `WhiskerValue` contract — the
//! `@WhiskerModule` Swift Macro emits the `@_cdecl` dispatch
//! shim, the KSP processor emits a `<Class>_Dispatch` Kotlin
//! object.
//!
//! ## Usage
//!
//! Add the crate to your app's `Cargo.toml`:
//!
//! ```toml
//! [dependencies]
//! whisker-local-store = { path = "../whisker/packages/whisker-local-store" }
//! ```
//!
//! Call from anywhere reactive runs (component bodies, event
//! handlers, effects):
//!
//! ```ignore
//! use whisker_local_store::WhiskerLocalStore;
//!
//! let _ = WhiskerLocalStore::save("user_id".into(), "abc".into())?;
//! let loaded = WhiskerLocalStore::load("user_id".into())?;
//! // -> Some("abc".to_string())
//! ```
//!
//! Each method returns `Result<T, WhiskerModuleError>` — the
//! platform side can't reasonably fail under normal conditions,
//! but Whisker's bridge reports any class-lookup / dispatch
//! issue through the same channel so callers handle every error
//! uniformly.

use whisker::native_module::{WhiskerModuleError, WhiskerValue};

/// Raw `-sys` proxy for the WhiskerLocalStore native module.
///
/// Generated by `#[whisker::native_module]` — every method is a
/// thin pass-through that calls
/// `whisker::native_module::invoke("WhiskerLocalStore", method, args)`.
/// Type-safe wrappers live in the public [`WhiskerLocalStore`]
/// struct below.
#[whisker::native_module(name = "WhiskerLocalStore")]
pub trait WhiskerLocalStoreRaw {
    fn save(args: Vec<WhiskerValue>) -> WhiskerValue;
    fn load(args: Vec<WhiskerValue>) -> WhiskerValue;
    fn remove(args: Vec<WhiskerValue>) -> WhiskerValue;
}

/// Typed Rust API for the WhiskerLocalStore native module.
///
/// Hand-written wrapper on top of [`WhiskerLocalStoreRaw`] —
/// builds the `Vec<WhiskerValue>` arg list, dispatches through
/// the proc-macro-emitted sys proxy, and lifts the returned
/// `WhiskerValue` into the matching typed result.
///
/// The wrapper pattern is documented as the recommended shape
/// for first-party + community modules — keeps the bridge
/// surface uniform (always `WhiskerValue`-only) while letting
/// each module expose ergonomic, idiomatic Rust.
pub struct WhiskerLocalStore;

impl WhiskerLocalStore {
    /// Persist `value` under `key`. Returns `true` on success.
    ///
    /// Subsequent [`load`](WhiskerLocalStore::load) calls with
    /// the same key resolve to `Some(value)` even across app
    /// launches. Overwrites any previously-stored value.
    pub fn save(key: String, value: String) -> Result<bool, WhiskerModuleError> {
        let result = WhiskerLocalStoreRaw::save(vec![
            WhiskerValue::String(key),
            WhiskerValue::String(value),
        ]);
        match result {
            WhiskerValue::Bool(b) => Ok(b),
            WhiskerValue::Error(msg) => Err(WhiskerModuleError(msg)),
            other => Err(WhiskerModuleError(format!(
                "WhiskerLocalStore::save expected Bool, got {other:?}"
            ))),
        }
    }

    /// Look up the value previously stored under `key`.
    ///
    /// Returns `None` when no entry exists. Doesn't distinguish
    /// "never saved" from "saved then removed" — both surface as
    /// `None`. Use [`save`](WhiskerLocalStore::save) to set a
    /// sentinel value if you need that distinction.
    pub fn load(key: String) -> Result<Option<String>, WhiskerModuleError> {
        let result = WhiskerLocalStoreRaw::load(vec![WhiskerValue::String(key)]);
        match result {
            WhiskerValue::Null => Ok(None),
            WhiskerValue::String(s) => Ok(Some(s)),
            WhiskerValue::Error(msg) => Err(WhiskerModuleError(msg)),
            other => Err(WhiskerModuleError(format!(
                "WhiskerLocalStore::load expected String or Null, got {other:?}"
            ))),
        }
    }

    /// Drop `key`'s entry (if any). No-op when the key isn't
    /// present.
    pub fn remove(key: String) -> Result<(), WhiskerModuleError> {
        let result = WhiskerLocalStoreRaw::remove(vec![WhiskerValue::String(key)]);
        match result {
            WhiskerValue::Null => Ok(()),
            WhiskerValue::Error(msg) => Err(WhiskerModuleError(msg)),
            // Be permissive: any non-error return is treated as
            // success. The platform-side contract for `remove`
            // is "side effect only, return null", but a stale
            // return shape shouldn't fail the call.
            _ => Ok(()),
        }
    }
}
