// AUTO-GENERATED by whisker-cng. Do NOT edit — re-run
// `whisker run` to refresh.
//
// Minimal Android shell. Host/runtime dependencies are added only when their
// retained-renderer integration is enabled; app startup itself stays a plain
// AGP project and never resolves Lynx artifacts.

pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "{{android_project_name}}"
include(":app")
