// AUTO-GENERATED by whisker-cng. Do NOT edit — re-run
// `whisker run` to refresh.
//
// Minimal Android shell. The app consumes the Whisker Host as an SDK library;
// no renderer implementation is generated into the application target.

pluginManagement {
    val localGradlePlugin = file("{{whisker_workspace_path}}/platforms/android/gradle-plugin")
    if (localGradlePlugin.isDirectory) {
        includeBuild(localGradlePlugin)
    }
    repositories {
        maven { url = uri("{{whisker_maven_url}}") }
        gradlePluginPortal()
        google()
        mavenCentral()
    }
    plugins {
        id("rs.whisker") version "{{whisker_gradle_plugin_version}}"
        id("rs.whisker.gradle") version "{{whisker_gradle_plugin_version}}"
    }
}

plugins {
    id("rs.whisker")
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = uri("{{whisker_maven_url}}") }
        google()
        mavenCentral()
    }
}

rootProject.name = "{{android_project_name}}"
include(":app")

val whiskerWorkspace = file("{{whisker_workspace_path}}")
// Refresh before the Settings plugin reads its Cargo.lock cache. Feature and
// path-manifest edits need not change Cargo.lock. Keeping this in the generated
// project also supports the currently published Gradle plugin.
val whiskerCli = System.getenv("WHISKER_CLI")?.takeIf { it.isNotBlank() } ?: "whisker"
val moduleRefresh = ProcessBuilder(
    whiskerCli, "modules",
    "--workspace=${whiskerWorkspace.absolutePath}",
    "--package={{whisker_user_package}}", "--write-cache",
).inheritIO().start()
check(moduleRefresh.waitFor() == 0) { "Whisker module discovery failed" }

whisker {
    workspace = whiskerWorkspace
    userPackage = "{{whisker_user_package}}"
}
val localAndroidSdk = whiskerWorkspace.resolve("platforms/android")
if (localAndroidSdk.isDirectory) {
    include(":whisker-module")
    project(":whisker-module").projectDir = localAndroidSdk.resolve("module")
    include(":whisker-runtime")
    project(":whisker-runtime").projectDir = localAndroidSdk.resolve("runtime")
}
val localKsp = whiskerWorkspace.resolve("platforms/android/ksp")
if (localKsp.isDirectory) {
    includeBuild(localKsp) {
        dependencySubstitution {
            substitute(module("rs.whisker:ksp")).using(project(":ksp"))
        }
    }
}
