// AUTO-GENERATED by whisker-cng. Do NOT edit — re-run
// `whisker run` to refresh.
//
// Minimal Android shell. The app consumes the Whisker Host as an SDK library;
// no renderer implementation is generated into the application target and no
// Lynx artifacts are resolved.

pluginManagement {
    repositories {
        maven { url = uri("{{whisker_maven_url}}") }
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = uri("{{whisker_maven_url}}") }
        google()
        mavenCentral()
    }
}

rootProject.name = "{{android_project_name}}"
include(":app")

val whiskerWorkspace = file("{{whisker_workspace_path}}")
val localAndroidSdk = whiskerWorkspace.resolve("platforms/android")
if (localAndroidSdk.isDirectory) {
    include(":whisker-module")
    project(":whisker-module").projectDir = localAndroidSdk.resolve("module")
    include(":whisker-runtime")
    project(":whisker-runtime").projectDir = localAndroidSdk.resolve("runtime")
}
val localKsp = whiskerWorkspace.resolve("platforms/android/ksp")
if (localKsp.isDirectory) {
    includeBuild(localKsp) {
        dependencySubstitution {
            substitute(module("rs.whisker:ksp")).using(project(":ksp"))
        }
    }
}

apply(from = "whisker_modules.settings.gradle.kts")
