// Whisker module-system iOS attached macro — `@WhiskerElement`.
//
// Applied to a `LynxUI<View>` subclass to mark it as the Lynx UI
// class for a given tag name:
//
// ```swift
// import WhiskerElements
// import Lynx
// import UIKit
//
// @WhiskerElement("x-hello")
// public class WhiskerHelloElement: LynxUI<UIView> {
//     public override func createView() -> UIView {
//         let v = UIView()
//         v.backgroundColor = .systemPink
//         return v
//     }
// }
// ```
//
// The macro decorates the annotated class with `@objc(<ClassName>)`
// so the Obj-C runtime name is stable (no Swift name mangling) and
// matches the string `whisker.module.toml`'s `[ios].behaviors` entry
// carries through to the generated registration code.
//
// Behaviour registration itself isn't generated by the macro — it
// lives in `WhiskerModuleBehaviors.swift`, which `whisker-build`
// renders from the manifest's `behaviors = [{ tag, class }]` list.
// The macro is the DX layer that ties the in-source declaration to
// the manifest entry; long-term `whisker-build` will parse macro
// applications directly via SwiftSyntax and the manifest list goes
// away, but v1 keeps both for orchestration simplicity.

/// Marks a `LynxUI` subclass as a Whisker native element for `tag`.
///
/// Apply to any subclass of `LynxUI<View>` (or a Lynx-provided
/// flatten variant) declared in a Whisker module crate's
/// `swift_sources`. The matching `[ios].behaviors` manifest entry
/// in the crate's `whisker.module.toml` declares the mapping
/// `whisker-build` uses to emit a registration call against Lynx's
/// behaviour registry.
@attached(member, names: arbitrary)
@attached(memberAttribute)
public macro WhiskerElement(_ tag: String) =
    #externalMacro(module: "WhiskerElementsMacros", type: "WhiskerElementMacro")

/// Marks a class as a Whisker native module under `name`.
///
/// Apply to a class whose instance methods follow the shape
/// `func name(_ args: [WhiskerValue]) -> WhiskerValue` — that's
/// the wire contract the C bridge dispatches against. The class
/// must have a zero-arg initialiser (`init()`); a fresh instance
/// is constructed per dispatch.
///
/// The macro expands into a top-level `@_cdecl` C-callable
/// dispatch shim that switches on the incoming method name and
/// routes to the matching instance method. The
/// `WhiskerElementsCodegen` SwiftPM build-tool plugin discovers
/// the annotation at build time and emits a
/// `whisker_bridge_register_module_dispatch(name, _whiskerDispatch_…)`
/// call into `WhiskerModuleBehaviors.swift` so the C bridge's
/// by-name lookup finds the shim at runtime.
///
/// Pairs with the Rust-side `#[whisker::native_module]` proc macro
/// (Phase 7-Φ.E.5) — the Swift class provides the platform-side
/// implementation, the Rust proxy provides the typed call surface.
/// Authors are encouraged to hand-write a separate typed wrapper
/// in front of the proc-macro-emitted unit struct rather than
/// publish the `[WhiskerValue]`-shaped API directly.
///
/// ```swift
/// import WhiskerElements
/// import WhiskerRuntime  // brings WhiskerValue + WhiskerValueRaw into scope
///
/// @WhiskerModule("WhiskerStorage")
/// public class WhiskerStorageImpl {
///     func save(_ args: [WhiskerValue]) -> WhiskerValue {
///         guard args.count >= 2,
///               case .string(let key)   = args[0],
///               case .string(let value) = args[1] else {
///             return .bool(false)
///         }
///         UserDefaults.standard.set(value, forKey: key)
///         return .bool(true)
///     }
/// }
/// ```
///
/// Phase 7-Φ.F: dispatch shim replaces the previous Obj-C
/// `NSInvocation`-based registry. The class no longer needs to
/// inherit from `NSObject` or declare `@objc` selectors.
// `names: prefixed(...)` covers both peer functions the macro
// emits:
//   - `_whiskerDispatch_<ClassName>` — the @_cdecl C dispatch shim
//   - `_whiskerRegister_<ClassName>` — a tiny registration helper
//     that calls `whisker_bridge_register_module_dispatch`. Lives
//     in the same .o as the dispatch shim so Swift can convert
//     the dispatch fn to `@convention(c)` locally (no inter-.o
//     thunk → no duplicate-symbol linker error in Debug). The
//     codegen plugin calls `_whiskerRegister_<ClassName>()` rather
//     than taking the dispatch shim's address directly.
//
// Swift rejects `names: arbitrary` on peer macros at global scope
// (a macro could otherwise shadow any top-level decl), so we
// enumerate each prefix explicitly.
@attached(peer, names: prefixed(_whiskerDispatch_), prefixed(_whiskerRegister_))
public macro WhiskerModule(_ name: String) =
    #externalMacro(module: "WhiskerElementsMacros", type: "WhiskerModuleMacro")
