// Whisker module-system iOS attached macro — `@WhiskerElement`.
//
// Applied to a `LynxUI<View>` subclass to mark it as the Lynx UI
// class for a given tag name:
//
// ```swift
// import WhiskerElements
// import Lynx
// import UIKit
//
// @WhiskerElement("x-hello")
// public class WhiskerHelloElement: LynxUI<UIView> {
//     public override func createView() -> UIView {
//         let v = UIView()
//         v.backgroundColor = .systemPink
//         return v
//     }
// }
// ```
//
// The macro decorates the annotated class with `@objc(<ClassName>)`
// so the Obj-C runtime name is stable (no Swift name mangling) and
// matches the string `whisker.module.toml`'s `[ios].behaviors` entry
// carries through to the generated registration code.
//
// Behaviour registration itself isn't generated by the macro — it
// lives in `WhiskerModuleBehaviors.swift`, which `whisker-build`
// renders from the manifest's `behaviors = [{ tag, class }]` list.
// The macro is the DX layer that ties the in-source declaration to
// the manifest entry; long-term `whisker-build` will parse macro
// applications directly via SwiftSyntax and the manifest list goes
// away, but v1 keeps both for orchestration simplicity.

/// Marks a `LynxUI` subclass as a Whisker native element for `tag`.
///
/// Apply to any subclass of `LynxUI<View>` (or a Lynx-provided
/// flatten variant) declared in a Whisker module crate's
/// `swift_sources`. The matching `[ios].behaviors` manifest entry
/// in the crate's `whisker.module.toml` declares the mapping
/// `whisker-build` uses to emit a registration call against Lynx's
/// behaviour registry.
@attached(member, names: arbitrary)
@attached(memberAttribute)
public macro WhiskerElement(_ tag: String) =
    #externalMacro(module: "WhiskerElementsMacros", type: "WhiskerElementMacro")

/// Marks an `NSObject` subclass as a Whisker native module under `name`.
///
/// Apply to a class implementing one or more single-`NSArray*`-arg
/// Obj-C methods (the wire shape `whisker_bridge_invoke_module`
/// expects on the platform side). The matching
/// `WhiskerElementsCodegen` SwiftPM build-tool plugin discovers
/// this annotation and emits a registration call against
/// `WhiskerModuleRegistry` so the C bridge's by-name lookup finds
/// the class at runtime.
///
/// Pairs with the Rust-side `#[whisker::native_module]` proc macro
/// (Phase 7-Φ.E.5) — the Swift class provides the platform-side
/// implementation, the Rust proxy provides the typed call surface.
///
/// ```swift
/// @WhiskerModule("WhiskerStorage")
/// @objc(WhiskerStorageImpl)
/// public class WhiskerStorageImpl: NSObject {
///     @objc public func save(_ args: NSArray) -> NSObject {
///         guard args.count >= 2,
///               let key = args[0] as? String,
///               let value = args[1] as? String else {
///             return NSNumber(value: false)
///         }
///         UserDefaults.standard.set(value, forKey: key)
///         return NSNumber(value: true)
///     }
/// }
/// ```
///
/// The macro decorates the annotated class with a
/// `__whiskerModuleName` constant carrying the registration name,
/// for SwiftSyntax-driven discovery at build time. Phase 7-Φ.E.6.
@attached(member, names: arbitrary)
@attached(memberAttribute)
public macro WhiskerModule(_ name: String) =
    #externalMacro(module: "WhiskerElementsMacros", type: "WhiskerModuleMacro")
