// Whisker module-system iOS attached macro — `@WhiskerElement`.
//
// Applied to a `LynxUI<View>` subclass to mark it as the Lynx UI
// class for a given tag name:
//
// ```swift
// import WhiskerElements
// import Lynx
// import UIKit
//
// @WhiskerElement("x-hello")
// public class WhiskerHelloElement: LynxUI<UIView> {
//     public override func createView() -> UIView {
//         let v = UIView()
//         v.backgroundColor = .systemPink
//         return v
//     }
// }
// ```
//
// The macro decorates the annotated class with `@objc(<ClassName>)`
// so the Obj-C runtime name is stable (no Swift name mangling) and
// matches the string `whisker.module.toml`'s `[ios].behaviors` entry
// carries through to the generated registration code.
//
// Behaviour registration itself isn't generated by the macro — it
// lives in `WhiskerModuleBehaviors.swift`, which `whisker-build`
// renders from the manifest's `behaviors = [{ tag, class }]` list.
// The macro is the DX layer that ties the in-source declaration to
// the manifest entry; long-term `whisker-build` will parse macro
// applications directly via SwiftSyntax and the manifest list goes
// away, but v1 keeps both for orchestration simplicity.

/// Marks a `LynxUI` subclass as a Whisker native element for `tag`.
///
/// Apply to any subclass of `LynxUI<View>` (or a Lynx-provided
/// flatten variant) declared in a Whisker module crate's
/// `swift_sources`. The matching `[ios].behaviors` manifest entry
/// in the crate's `whisker.module.toml` declares the mapping
/// `whisker-build` uses to emit a registration call against Lynx's
/// behaviour registry.
@attached(member, names: arbitrary)
@attached(memberAttribute)
public macro WhiskerElement(_ tag: String) =
    #externalMacro(module: "WhiskerElementsMacros", type: "WhiskerElementMacro")
