{
  "formatVersion": "1.1",
  "component": {
    "group": "rs.whisker",
    "module": "ksp",
    "version": "0.1.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.12.jar",
          "url": "ksp-0.1.12.jar",
          "size": 11123,
          "sha512": "791c6181cac2cd4c0ef870c0004266f2e14a41523dd3e7885b4b53ebd89fe5a39d4dce0abc8937faddb9eb09a739c69a398922c494dea6961ab4adca6a70dae2",
          "sha256": "5edcd13ab3b25e728ae04558890b3b163b0ba9935e2f7f02b9debb7bda3ea84c",
          "sha1": "916a0c480450f599c0b88da4ec720f5bb38fe00b",
          "md5": "3ba7c09fe15219299f725ce5773d05fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.0.21-1.0.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.12.jar",
          "url": "ksp-0.1.12.jar",
          "size": 11123,
          "sha512": "791c6181cac2cd4c0ef870c0004266f2e14a41523dd3e7885b4b53ebd89fe5a39d4dce0abc8937faddb9eb09a739c69a398922c494dea6961ab4adca6a70dae2",
          "sha256": "5edcd13ab3b25e728ae04558890b3b163b0ba9935e2f7f02b9debb7bda3ea84c",
          "sha1": "916a0c480450f599c0b88da4ec720f5bb38fe00b",
          "md5": "3ba7c09fe15219299f725ce5773d05fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ksp-0.1.12-sources.jar",
          "url": "ksp-0.1.12-sources.jar",
          "size": 5750,
          "sha512": "ece2136e7f0645627e2bf8fa34e5a6fa215291a14283649fcecc08ccfdfb3bdbfc10c68e4f23763d7353c9e620d444fe8f64dbd2abec5cac92057fb1615c08d9",
          "sha256": "4a32d440067e050f167d8d790efde66e9a8a0a1df877eb6ada8ce0f0fde36d0e",
          "sha1": "ab7f62d43f0a54ffff782fc860edc19a49594061",
          "md5": "72c957be619e7a43db760d786ba844c8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ksp-0.1.12-javadoc.jar",
          "url": "ksp-0.1.12-javadoc.jar",
          "size": 261,
          "sha512": "e4a8ca1b2e630186ca09d9da2635aeee39b9cb31078799c255c1c96190e02cd34ef2b75ec8d02f9fd428d4dd1b7031464d1e0f12eab8e7abfd384b9b8352386f",
          "sha256": "4e95b8e4b204d11ce89a13fc3911c779cf4f1e6e2b2c2046063ecfde4988480e",
          "sha1": "9491e1b8c24863053c5b1800b1703b9183988174",
          "md5": "108a25568a14b9eef4550a0d1f6487a3"
        }
      ]
    }
  ]
}
