//! Run a tiny probe binary that includes the user's `whisker.rs` and
//! emits the resulting `AppConfig` as JSON on stdout.
//!
//! ## Why a probe binary?
//!
//! `whisker.rs` is regular Rust source — there's no parser we could
//! point at the file. The user's `configure` function can do
//! arbitrary computation (env lookups, conditional fields, etc.), so
//! the only way to know what it *means* is to execute it.
//!
//! The probe is a one-file `cargo run` that:
//!   1. `include!("path/to/whisker.rs")` — splices the user's
//!      `configure` fn into our tiny `main`.
//!   2. Calls `configure(&mut AppConfig::default())`.
//!   3. Serializes the populated config to JSON and prints it.
//!
//! Compile cost is single-digit seconds the first time (just
//! `whisker-app-config` + `serde_json`), and the result is cached
//! under `target/.whisker/config-cache.json`. The cache is
//! invalidated by mtime: re-running the probe is a no-op unless
//! `whisker.rs` was touched since the cache write.
//!
//! ## Why not include the umbrella `whisker` crate?
//!
//! `whisker-app-config` is intentionally a small, dependency-light
//! crate so the probe build is cheap. Pulling in `whisker`
//! (umbrella) would also pull `whisker-runtime`, `whisker-driver`,
//! Lynx headers, etc. — turning the probe into a multi-minute build.
//! The user crate's `whisker.rs` therefore writes
//! `use whisker_app_config::AppConfig` directly, not `use
//! whisker::AppConfig`.

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::SystemTime;
use whisker_app_config::AppConfig;

/// Run the probe and return the parsed config. Caches via mtime so
/// the second call (and later) returns instantly until `whisker.rs`
/// changes.
///
/// `crate_name` is used to name the probe binary (so the temp `target/`
/// doesn't collide if the user happens to also have a probe-shaped
/// crate of their own).
pub fn run(whisker_rs: &Path, crate_dir: &Path, crate_name: &str) -> Result<AppConfig> {
    let cache = crate_dir.join("target/.whisker/config-cache.json");
    if cache_is_fresh(&cache, whisker_rs) {
        let json = std::fs::read_to_string(&cache)
            .with_context(|| format!("read cache {}", cache.display()))?;
        return serde_json::from_str(&json)
            .with_context(|| format!("parse cached config {}", cache.display()));
    }
    let probe_dir = crate_dir.join("target/.whisker/config-probe");
    write_probe_project(&probe_dir, whisker_rs, crate_name)?;
    let json = run_cargo_probe(&probe_dir, crate_name)?;
    if let Some(parent) = cache.parent() {
        std::fs::create_dir_all(parent).with_context(|| format!("mkdir {}", parent.display()))?;
    }
    std::fs::write(&cache, &json).with_context(|| format!("write cache {}", cache.display()))?;
    serde_json::from_str(&json).with_context(|| "parse probe stdout as AppConfig JSON")
}

fn cache_is_fresh(cache: &Path, whisker_rs: &Path) -> bool {
    let Ok(cache_mtime) = std::fs::metadata(cache).and_then(|m| m.modified()) else {
        return false;
    };
    let Ok(src_mtime) = std::fs::metadata(whisker_rs).and_then(|m| m.modified()) else {
        return false;
    };
    cache_mtime
        .duration_since(src_mtime)
        .map(|d| d > std::time::Duration::ZERO)
        .unwrap_or(false)
        || cache_mtime > src_mtime
        // Defensive: clock skew can make duration_since fail even when
        // mtime ordering says fresh. Compare SystemTime directly.
        || matches!(
            cache_mtime.duration_since(SystemTime::UNIX_EPOCH),
            Ok(_),
        ) && cache_mtime >= src_mtime
}

/// Write the probe's `Cargo.toml` + `src/main.rs`. Both files are
/// idempotent: we rewrite them on every cache-miss so an out-of-tree
/// edit (or a probe-dir delete) self-heals.
fn write_probe_project(probe_dir: &Path, whisker_rs: &Path, crate_name: &str) -> Result<()> {
    let src_dir = probe_dir.join("src");
    std::fs::create_dir_all(&src_dir).with_context(|| format!("mkdir {}", src_dir.display()))?;

    let probe_crate_name = format!("__whisker_config_probe_{}", crate_name.replace('-', "_"));
    let cargo_toml = format!(
        r#"# Auto-generated by whisker-cli (do not edit).
[package]
name = "{probe_crate_name}"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
whisker-app-config = {{ path = "{app_config_path}" }}
serde_json = "1"

[[bin]]
name = "{probe_crate_name}"
path = "src/main.rs"

# Avoid leaking workspace inheritance: every published-config field
# the parent workspace sets (rust-version, license, …) would have to
# match here. Stand-alone keeps the probe immune to workspace churn.
[workspace]
"#,
        // The probe lives under target/.whisker/config-probe/, so
        // whisker-app-config is 4 ../../../../ up from there:
        //   <user-crate>/target/.whisker/config-probe/
        //   ../.., ../.., …, up to the workspace root, then over to
        //   crates/whisker-app-config.
        //
        // For external Whisker users this won't work — the published
        // version of whisker-app-config from crates.io should be used
        // instead. For now Whisker development happens inside this
        // workspace; once we publish, swap this for
        // `version = "0.1"` and let cargo resolve from crates.io.
        app_config_path = whisker_app_config_path()?.display(),
    );
    std::fs::write(probe_dir.join("Cargo.toml"), cargo_toml)
        .with_context(|| format!("write {}/Cargo.toml", probe_dir.display()))?;

    // `include!` takes an absolute path; we use display() so the path
    // is a normal forward-slashed string (Windows isn't supported by
    // the dev server, so display() is safe).
    let main_rs = format!(
        r#"// Auto-generated by whisker-cli (do not edit).
//
// This probe binary splices the user's `whisker.rs` into a `main`
// that prints the resulting `AppConfig` as JSON on stdout. The
// host shell (`whisker run`) parses that JSON and projects the
// fields it needs into a flat `whisker_dev_server::Config`.

include!({whisker_rs:?});

fn main() {{
    let mut cfg = whisker_app_config::AppConfig::default();
    configure(&mut cfg);
    let stdout = std::io::stdout();
    serde_json::to_writer(stdout.lock(), &cfg).expect("serialize AppConfig");
}}
"#,
        whisker_rs = whisker_rs.to_string_lossy(),
    );
    std::fs::write(src_dir.join("main.rs"), main_rs)
        .with_context(|| format!("write {}/src/main.rs", src_dir.display()))?;

    Ok(())
}

fn run_cargo_probe(probe_dir: &Path, _crate_name: &str) -> Result<String> {
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let out = Command::new(&cargo)
        .arg("run")
        .arg("--quiet")
        .arg("--release")
        .arg("--manifest-path")
        .arg(probe_dir.join("Cargo.toml"))
        .output()
        .with_context(|| format!("spawn cargo run for probe at {}", probe_dir.display()))?;
    if !out.status.success() {
        anyhow::bail!(
            "config probe build/run failed (exit {})\nstderr:\n{}",
            out.status,
            String::from_utf8_lossy(&out.stderr),
        );
    }
    String::from_utf8(out.stdout).context("probe stdout not valid UTF-8")
}

/// Path to `whisker-app-config`'s source dir as referenced by the
/// probe's `Cargo.toml`. For in-workspace development this lives
/// under the same parent workspace as `whisker-cli`; if Whisker is
/// ever published to crates.io we'll swap this for `version = "..."`
/// and let cargo resolve normally.
fn whisker_app_config_path() -> Result<PathBuf> {
    // `CARGO_MANIFEST_DIR` of `whisker-cli` at build time is
    // `<workspace>/crates/whisker-cli`. Its great-grandparent path
    // dance puts us at `<workspace>/crates/whisker-app-config`.
    let cli_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let app_config = cli_dir
        .parent()
        .ok_or_else(|| anyhow::anyhow!("whisker-cli has no parent dir"))?
        .join("whisker-app-config");
    if !app_config.is_dir() {
        anyhow::bail!(
            "whisker-app-config source dir not found at {}",
            app_config.display(),
        );
    }
    Ok(app_config)
}
