// Generated by `cargo xtask mobile-abi generate`; do not edit.
package rs.whisker.runtime.bridge

internal object AndroidFrameBatch {
    const val STRIDE: Int = 10
    const val TAG: Int = 0
    const val FLAGS: Int = 1
    const val NODE: Int = 2
    const val PARENT: Int = 3
    const val CHILD: Int = 4
    const val INDEX: Int = 5
    const val MEMBER: Int = 6
    const val INTEGER: Int = 7
    const val SCALAR: Int = 8
    const val WIDE: Int = 9
}
