//! `whisker-icons` — Lucide-icons widget for Whisker.
//!
//! **API shape — 1 (pure Component) + constants module.** See
//! [`docs/module-api-design.md`](https://github.com/whiskerrs/whisker/blob/main/docs/module-api-design.md)
//! §"Shape 1". The [`Icon`] component is a pure `whisker_svg::Svg`
//! forwarder; the icon library itself is exposed as a set of
//! `pub const &str` items under [`lucide`] (codegen, see `build.rs`).
//!
//! ```ignore
//! use whisker::prelude::*;
//! use whisker_icons::{Icon, lucide};
//!
//! #[component]
//! fn liked() -> Element {
//!     render! {
//!         Icon(svg: lucide::Heart, color: "#ff5577", size: "24")
//!     }
//! }
//! ```
//!
//! ## Tree shaking
//!
//! Every icon is its own `pub const &str`. `whisker_icons::lucide`
//! is generated by `build.rs` from `vendor/lucide/icons/*.svg` —
//! when the user references e.g. `lucide::Heart`, only the bytes
//! of Heart's SVG end up in their binary. The other ~1700 icons
//! the compiler sees in the module are unreferenced and get
//! linker-DCE'd alongside any other unused static rodata.
//!
//! That's why the icons surface as constants instead of one
//! lookup-by-string `fn icon(name: &str)` — a runtime lookup
//! would force the linker to keep every icon string reachable
//! "just in case", defeating the whole point.
//!
//! ## Why not a Lucide-specific renderer
//!
//! Each `pub const` carries the full `<svg viewBox="0 0 24 24"
//! stroke="currentColor" …>` wrapper, not just the inner shapes.
//! Cost: ~280 bytes per icon instead of ~30. Win: the [`Icon`]
//! component is a pure `whisker_svg::Svg` forwarder, so a future
//! `whisker_icons::heroicons` (or `::phosphor`, …) module can
//! emit its own constants under its own attribute conventions and
//! plug into the exact same `Icon`.
//!
//! ## Native source
//!
//! This crate has no native side — rendering is delegated to
//! `whisker-svg`, whose platform replayers live at
//! `packages/whisker-svg/{ios,android}/`. Icon bytes are vendored
//! under `packages/whisker-icons/vendor/lucide/`.

use whisker::prelude::*;
use whisker::runtime::view::Element;
use whisker_svg::{Svg, SvgProps};

/// One Lucide-style icon at a square `size × size` box.
///
/// Props:
///
/// - `svg` — the SVG XML to render. In practice this is one of the
///   constants under [`lucide`] (or any other module that follows
///   the same shape), but the component accepts any SVG string —
///   it's just a `whisker_svg::Svg` with a generated `style:`.
/// - `color` — CSS-style colour used as the `currentColor`
///   substitution. Lucide icons use `stroke="currentColor"`
///   throughout, so this drives the visible stroke.
/// - `size` — square edge length. Plain numbers (`"24"`) are
///   treated as `px`; values that already carry a CSS unit
///   (`"1.5em"`, `"100%"`, `"24px"`) pass through unchanged.
#[component]
pub fn icon(svg: Signal<String>, color: Signal<String>, size: Signal<String>) -> Element {
    let style = {
        let size = size.clone();
        computed(move || {
            let raw = size.get();
            let t = raw.trim();
            // Common CSS length units pass through; bare numbers
            // are treated as `px`.
            let has_unit = ["px", "em", "rem", "%", "vw", "vh"]
                .iter()
                .any(|u| t.ends_with(u));
            if has_unit {
                format!("width: {t}; height: {t};")
            } else {
                format!("width: {t}px; height: {t}px;")
            }
        })
    };

    render! {
        Svg(
            content: svg.clone(),
            color: color.clone(),
            style: style,
        )
    }
}

/// Lucide icon set — ~1700 PascalCase `&'static str` constants
/// (`AlarmClock`, `ChevronRight`, `Heart`, …), each holding the
/// full v0 Lucide SVG markup. Generated from `vendor/lucide/icons/`
/// by `build.rs`. License (ISC): `vendor/lucide/LICENSE`.
///
/// `#[allow(non_upper_case_globals)]` keeps the PascalCase names
/// the React / Vue Lucide bindings use — the price of trip-free
/// drop-in conversion for users coming from JS.
#[allow(non_upper_case_globals)]
pub mod lucide {
    include!(concat!(env!("OUT_DIR"), "/lucide_consts.rs"));
}

#[cfg(test)]
mod tests {
    use super::lucide;

    #[test]
    fn well_known_icons_resolve_to_nonempty_svg() {
        // Compile-time existence checks the PascalCase rule + the
        // build.rs walk; runtime non-empty checks that bytes landed.
        for (label, body) in [
            ("Heart", lucide::Heart),
            ("ChevronRight", lucide::ChevronRight),
            ("ChevronLeft", lucide::ChevronLeft),
            ("Search", lucide::Search),
            ("X", lucide::X),
            ("AlarmClock", lucide::AlarmClock),
        ] {
            assert!(!body.is_empty(), "{label} has empty body");
            assert!(body.starts_with("<svg"), "{label} missing svg wrapper");
        }
    }

    #[test]
    fn icons_round_trip_through_whisker_svg_compiler() {
        // The display-list pipeline is the only consumer on-device;
        // catch compiler-unsupported attrs here, not as a blank tile.
        let sample = [lucide::Heart, lucide::ChevronRight, lucide::AlarmClock];
        for svg in sample {
            let compiled = whisker_svg::compile(svg).expect("compile");
            assert_eq!(&compiled.bytes[0..4], b"WSDL");
        }
    }
}
