//! Project-relative paths and staged files shared by platform models

use crate::FileEntry;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// A normalized path relative to a project or artifact root
///
/// Uses `/` separators on every host. Absolute paths, drive prefixes, backslashes,
/// empty segments, `.` and `..` are rejected at construction and deserialization.
/// This is a lexical contract. Windows project validation additionally checks
/// portable Win32 names and ASCII case collisions. Backends still validate native
/// filenames/Unicode equivalence and prevent symlink traversal.
///
/// ```
/// use whisker_plugin::project::ProjectPath;
/// let path = ProjectPath::new("assets/icon.png")?;
/// assert_eq!(path.as_str(), "assets/icon.png");
/// assert!(ProjectPath::new("../secret").is_err());
/// # Ok::<(), anyhow::Error>(())
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct ProjectPath(String);

impl ProjectPath {
    /// Construct a relative path, rejecting nonportable or escaping syntax
    pub fn new(path: impl Into<String>) -> anyhow::Result<Self> {
        let path = path.into();
        anyhow::ensure!(
            !path.is_empty()
                && !path.contains(['\\', ':'])
                && !path.chars().any(char::is_control)
                && path.split('/').all(|part| !matches!(part, "" | "." | "..")),
            "invalid project-relative path: {path:?}"
        );
        Ok(Self(path))
    }

    /// Borrow the path using portable `/` separators
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for ProjectPath {
    type Error = anyhow::Error;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::new(value)
    }
}

impl From<ProjectPath> for String {
    fn from(value: ProjectPath) -> Self {
        value.0
    }
}

/// Files staged into the generated project, keyed by destination path
///
/// A directory entry owns its entire subtree. Entries must not overlap. Staging
/// makes source provenance explicit without embedding machine-specific paths.
pub type ProjectFiles = BTreeMap<ProjectPath, ProjectFile>;

/// Contents or app-relative input to stage at a [`ProjectFiles`] destination
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case", deny_unknown_fields)]
pub enum ProjectFile {
    /// Generated bytes, with optional POSIX mode.
    Generated {
        /// Reuses the plugin protocol's text/binary representation.
        entry: FileEntry,
    },
    /// Copy one file from the consuming application's crate directory.
    AppFile {
        /// Path relative to the consuming app, not the generated project.
        source: ProjectPath,
    },
    /// Copy a complete directory from the consuming application's crate directory.
    AppDirectory {
        /// Path relative to the consuming app; owns the destination subtree.
        source: ProjectPath,
    },
}

/// A staged file or directory copied into a final bundle or distribution
///
/// Unlike project staging, this controls the runtime location. For a directory,
/// its contents are placed under `destination`, preserving their relative paths.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Resource {
    /// Path in the generated project.
    pub source: ProjectPath,
    /// Path relative to the platform's resource root (e.g. Contents/Resources).
    pub destination: ProjectPath,
    /// Whether to copy one file or a directory tree.
    pub kind: ResourceKind,
}

/// Copy semantics for a [`Resource`]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ResourceKind {
    /// Copy a single file.
    File,
    /// Copy a directory tree.
    Directory,
}

/// A Cargo artifact used by a generated Host or native target
///
/// The selected features describe this artifact's build. Native target triples
/// and profiles are supplied by the platform build invocation, not guessed from
/// the machine executing a plugin.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RustBuild {
    /// Staged Cargo.toml path in the generated project.
    pub manifest: ProjectPath,
    /// Cargo package containing the artifact.
    pub package: String,
    /// Binary or library target name inside that package.
    pub target: String,
    /// Kind of Cargo artifact to produce.
    pub kind: RustArtifactKind,
    /// Features selected in addition to any defaults.
    #[serde(default)]
    pub features: Vec<String>,
    /// Whether to enable this package's default features.
    pub default_features: bool,
}

/// Rust artifact roles used by native and Web builds
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RustArtifactKind {
    /// Standalone executable.
    Bin,
    /// Static library linked by a native target.
    Staticlib,
    /// Dynamic library, including a WebAssembly cdylib.
    Cdylib,
}
