//! The static [`RouteTree`] and its compiled, addressable form
//! [`CompiledTree`].
//!
//! A [`RouteTree`] is the description of the app's screen structure. It is
//! normally generated by the `routes!` macro, but can also be built by hand
//! with the constructor helpers ([`RouteTree::route`], [`RouteTree::stack`],
//! [`RouteTree::switch`]).
//!
//! [`CompiledTree`] wraps a `RouteTree` and pre-computes, in a
//! pre-order walk, a flat table of node metadata keyed by [`NodeId`],
//! plus parent links and full URLs — everything resolution and URL
//! derivation need without re-walking the tree each time.

use std::collections::BTreeMap;

/// A stable identity for a node, assigned in pre-order at
/// [`CompiledTree`] build time.
///
/// Two *different* nodes always get different `NodeId`s. Logical
/// **nav-target identity** (the "shared route deduped to one target"
/// case) is expressed separately by [`RouteDef::id`], not by `NodeId`:
/// the same `post/:id` route spread into several tabs is several
/// distinct `NodeId`s that share one [`RouteDef::id`].
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct NodeId(pub usize);

/// A positional address: the chain of child indices from the root to a
/// node.
///
/// The root is `NodePath(vec![])`. A `Switch`'s third branch reached
/// through the root stack's first entry is `NodePath(vec![0, 2])`.
/// `NodePath` is what [`RouteState::current`](crate::core::RouteState::current)
/// returns and what resolution produces.
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
pub struct NodePath(pub Vec<usize>);

impl NodePath {
    /// The root path (empty).
    pub fn root() -> Self {
        NodePath(Vec::new())
    }

    /// A child path: `self` extended by `index`.
    pub fn child(&self, index: usize) -> Self {
        let mut v = self.0.clone();
        v.push(index);
        NodePath(v)
    }

    /// Depth (number of edges from the root).
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Whether this is the root path.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// Whether `self` is an ancestor of (or equal to) `other`.
    pub fn is_ancestor_of(&self, other: &NodePath) -> bool {
        other.0.len() >= self.0.len() && other.0[..self.0.len()] == self.0[..]
    }
}

/// The definition of a `Route` node — the **only** named node kind.
///
/// A Route can be a leaf screen, a layout (component + Outlet for children),
/// a URL-grouping namespace, or any combination. The three axes are
/// independent:
///
/// | `segment` | `component` | `children` | Role |
/// |---|---|---|---|
/// | Some | Some | empty | leaf screen |
/// | Some | Some | non-empty | layout at a URL segment |
/// | Some | None | non-empty | URL grouping (implicit Outlet) |
/// | None | Some | non-empty | pathless layout (tab chrome, etc.) |
/// | None | Some | empty | pathless screen (root, etc.) |
/// | None | None | non-empty | transparent wrapper |
///
/// A segment wrapped in `()` (e.g. `"(home)"`) is a **group**: it qualifies
/// an internal destination but never contributes to the public URL
/// (Expo Router's `(group)` equivalent). Read the active group with
/// [`use_group`](crate::render::use_group); [`use_pathname`](crate::render::use_pathname)
/// returns only the public pathname.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RouteDef {
    /// The path segment, e.g. `"users"`, `":id"`, `"(home)"`.
    /// `None` = pathless (contributes nothing to the URL).
    pub segment: Option<String>,
    /// The nav-target identity. Derived from the component name or segment.
    pub id: String,
    /// The names of the dynamic (`:name`) segments, in order.
    pub params: Vec<String>,
    /// The component id registered for this route (`None` = no screen,
    /// either a transparent pass-through or a URL-only grouping).
    pub component: Option<String>,
    /// `true` when the segment is a group — `"(name)"`. Groups do not
    /// contribute to the public pathname.
    pub is_group: bool,
}

impl RouteDef {
    /// A route with a path segment and a component.
    pub fn new(segment: impl Into<String>, id: impl Into<String>) -> Self {
        let segment = segment.into();
        let is_group = segment.starts_with('(') && segment.ends_with(')');
        let params = segment
            .split('/')
            .filter_map(|p| p.strip_prefix(':').map(str::to_string))
            .collect();
        RouteDef {
            segment: Some(segment),
            id: id.into(),
            params,
            component: None,
            is_group,
        }
    }

    /// Builder: set the component id.
    pub fn with_component(mut self, component: impl Into<String>) -> Self {
        self.component = Some(component.into());
        self
    }

    /// A pathless route (no segment, no URL contribution).
    pub fn pathless(id: impl Into<String>) -> Self {
        RouteDef {
            segment: None,
            id: id.into(),
            params: Vec::new(),
            component: None,
            is_group: false,
        }
    }

    /// The group name without parentheses (e.g. `"(home)"` → `"home"`).
    /// `None` if this is not a group.
    pub fn group_name(&self) -> Option<&str> {
        if self.is_group {
            self.segment.as_deref().map(|s| &s[1..s.len() - 1])
        } else {
            None
        }
    }
}

/// Optional configuration for a [`RouteTree::Switch`].
///
/// Branch names come from the child `Route` nodes (every Switch child
/// must be a Route), not from the Switch itself.
#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct SwitchDef {
    /// An optional identifier (for debugging / `within(scope)` targeting).
    pub id: Option<String>,
    /// The branch selected on cold start (when `selected` is otherwise
    /// undefined). `None` falls back to branch `0` (declaration order).
    pub default: Option<usize>,
    /// What a group-only `navigate` does when its branch is already active.
    pub reselect: ReselectBehavior,
}

/// Behavior when the active branch is selected again.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum ReselectBehavior {
    /// Pop the branch's first stack to its root screen.
    #[default]
    PopToRoot,
    /// Keep the branch exactly as it is.
    Preserve,
}

impl SwitchDef {
    /// A switch with a named id and an explicit default branch.
    pub fn new(id: impl Into<String>, default: usize) -> Self {
        SwitchDef {
            id: Some(id.into()),
            default: Some(default),
            reselect: ReselectBehavior::PopToRoot,
        }
    }

    /// Configure active-branch reselect behavior.
    pub fn with_reselect(mut self, reselect: ReselectBehavior) -> Self {
        self.reselect = reselect;
        self
    }

    /// The default branch index (the declared default, else `0`).
    pub fn default_branch(&self) -> usize {
        self.default.unwrap_or(0)
    }
}

/// The static route structure: a tree of three node kinds.
///
/// - **`Route`** is the only named node. It can be a leaf (no children),
///   a layout (component + children), or a URL-grouping namespace.
/// - **`Stack`** / **`Switch`** are unnamed containers that organize
///   `Route` children. Their direct children **must** be `Route` nodes.
///
/// Wrap in a [`CompiledTree`] to address and query it.
#[derive(Clone, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum RouteTree {
    /// A named node: optionally a screen, optionally with children.
    Route(RouteDef, Vec<RouteTree>),
    /// An **ordered** container: push/pop, has history.
    /// Children must be `Route` nodes.
    Stack(Vec<RouteTree>),
    /// A **parallel** container: keeps all branches alive, selects one.
    /// Children must be `Route` nodes (giving each branch a name).
    Switch(SwitchDef, Vec<RouteTree>),
}

impl RouteTree {
    /// A leaf Route (no children) from a segment + id.
    pub fn route(segment: impl Into<String>, id: impl Into<String>) -> Self {
        RouteTree::Route(RouteDef::new(segment, id), Vec::new())
    }

    /// A Route with a component and children.
    pub fn route_with(def: RouteDef, children: Vec<RouteTree>) -> Self {
        RouteTree::Route(def, children)
    }

    /// A [`RouteTree::Stack`] from its ordered children.
    pub fn stack(children: Vec<RouteTree>) -> Self {
        RouteTree::Stack(children)
    }

    /// A [`RouteTree::Switch`] from a [`SwitchDef`] and its branches.
    pub fn switch(def: SwitchDef, branches: Vec<RouteTree>) -> Self {
        RouteTree::Switch(def, branches)
    }

    /// The children of this node.
    pub fn children(&self) -> &[RouteTree] {
        match self {
            RouteTree::Route(_, c) => c,
            RouteTree::Stack(c) => c,
            RouteTree::Switch(_, c) => c,
        }
    }

    /// The [`RouteDef`] if this is a `Route` node.
    pub fn route_def(&self) -> Option<&RouteDef> {
        match self {
            RouteTree::Route(def, _) => Some(def),
            _ => None,
        }
    }
}

/// Per-node metadata pre-computed by [`CompiledTree`].
#[derive(Clone, Debug)]
pub struct NodeInfo {
    /// Stable identity (pre-order index).
    pub id: NodeId,
    /// Positional address.
    pub path: NodePath,
    /// Path of the parent (`None` for the root).
    pub parent: Option<NodePath>,
    /// The [`RouteDef::id`] if this is a `Route`, else `None`.
    pub route_id: Option<String>,
    /// The full URL of this node if it is a `Route` with a component
    /// (a renderable screen), else `None`.
    pub url: Option<String>,
    /// The internal fully-qualified URL including route-group segments.
    /// This identifies a specific placement without leaking groups into the
    /// host-visible location.
    pub qualified_url: Option<String>,
    /// The component id if this is a `Route` with a component.
    pub component: Option<String>,
    /// `true` if this is a group Route `"(name)"`.
    pub is_group: bool,
}

/// A [`RouteTree`] wrapped with a pre-computed, addressable metadata
/// table.
///
/// Build with [`CompiledTree::new`]. Lookups by [`NodePath`] are
/// `O(depth)`; lookups by [`NodeId`] are `O(log n)`.
#[derive(Clone, Debug)]
pub struct CompiledTree {
    root: RouteTree,
    // NodePath → info, keyed by the path vec for ordered iteration.
    by_path: BTreeMap<Vec<usize>, NodeInfo>,
    by_id: BTreeMap<usize, NodePath>,
}

impl CompiledTree {
    /// Compile a [`RouteTree`], assigning [`NodeId`]s in pre-order and
    /// pre-computing parents + URLs.
    pub fn new(root: RouteTree) -> Self {
        let mut by_path = BTreeMap::new();
        let mut by_id = BTreeMap::new();
        let mut counter = 0usize;
        Self::walk(
            &root,
            NodePath::root(),
            None,
            String::new(),
            String::new(),
            &mut counter,
            &mut by_path,
            &mut by_id,
        );
        CompiledTree {
            root,
            by_path,
            by_id,
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn walk(
        node: &RouteTree,
        path: NodePath,
        parent: Option<NodePath>,
        public_url_so_far: String,
        qualified_url_so_far: String,
        counter: &mut usize,
        by_path: &mut BTreeMap<Vec<usize>, NodeInfo>,
        by_id: &mut BTreeMap<usize, NodePath>,
    ) {
        let id = NodeId(*counter);
        *counter += 1;

        let (
            route_id,
            this_url,
            this_qualified_url,
            child_public_url_base,
            child_qualified_url_base,
            component,
            is_group,
        ) = match node {
            RouteTree::Route(def, rt_children) => {
                let segment = def.segment.as_deref().unwrap_or("");
                let child_qualified_url_base = if def.segment.is_none() {
                    qualified_url_so_far.clone()
                } else {
                    join_url(&qualified_url_so_far, segment)
                };
                // Groups qualify a placement but are not part of the public
                // URL, matching Expo Router's `(group)` semantics.
                let child_public_url_base = if def.segment.is_none() || def.is_group {
                    public_url_so_far.clone()
                } else {
                    join_url(&public_url_so_far, segment)
                };
                let has_url = def.component.is_some()
                    || (def.segment.is_some() && rt_children.is_empty())
                    || def.is_group;
                let this_url = if has_url {
                    Some(normalize_root(&child_public_url_base))
                } else {
                    None
                };
                let this_qualified_url = if has_url {
                    Some(normalize_root(&child_qualified_url_base))
                } else {
                    None
                };
                (
                    Some(def.id.clone()),
                    this_url,
                    this_qualified_url,
                    child_public_url_base,
                    child_qualified_url_base,
                    def.component.clone(),
                    def.is_group,
                )
            }
            RouteTree::Stack(_) | RouteTree::Switch(_, _) => (
                None,
                None,
                None,
                public_url_so_far.clone(),
                qualified_url_so_far.clone(),
                None,
                false,
            ),
        };

        by_path.insert(
            path.0.clone(),
            NodeInfo {
                id,
                path: path.clone(),
                parent,
                route_id,
                url: this_url,
                qualified_url: this_qualified_url,
                component,
                is_group,
            },
        );
        by_id.insert(id.0, path.clone());

        for (i, child) in node.children().iter().enumerate() {
            Self::walk(
                child,
                path.child(i),
                Some(path.clone()),
                child_public_url_base.clone(),
                child_qualified_url_base.clone(),
                counter,
                by_path,
                by_id,
            );
        }
    }

    /// The root node.
    pub fn root(&self) -> &RouteTree {
        &self.root
    }

    /// The node at `path`, if any.
    pub fn node_at(&self, path: &NodePath) -> Option<&RouteTree> {
        let mut node = &self.root;
        for &idx in &path.0 {
            node = node.children().get(idx)?;
        }
        Some(node)
    }

    /// Metadata for the node at `path`.
    pub fn info_at(&self, path: &NodePath) -> Option<&NodeInfo> {
        self.by_path.get(&path.0)
    }

    /// The [`NodePath`] of a node addressed by [`NodeId`].
    pub fn path_of_id(&self, id: NodeId) -> Option<&NodePath> {
        self.by_id.get(&id.0)
    }

    /// The full URL of the route at `path` (pathless containers → `None`).
    ///
    /// This is the segment-concatenation derivation: walk from the root,
    /// joining each `Route`'s static segment parts; containers
    /// contribute nothing.
    pub fn url_of(&self, path: &NodePath) -> Option<String> {
        self.info_at(path).and_then(|i| i.url.clone())
    }

    /// The internal URL of `path`, including route-group qualifiers.
    pub fn qualified_url_of(&self, path: &NodePath) -> Option<String> {
        self.info_at(path).and_then(|i| i.qualified_url.clone())
    }

    /// The nearest route-group name containing `path`, without parentheses.
    pub fn group_of(&self, path: &NodePath) -> Option<String> {
        for depth in (0..=path.len()).rev() {
            let ancestor = NodePath(path.0[..depth].to_vec());
            let Some(RouteTree::Route(def, _)) = self.node_at(&ancestor) else {
                continue;
            };
            if let Some(group) = def.group_name() {
                return Some(group.to_string());
            }
        }
        None
    }

    /// All [`NodePath`]s whose `Route` has the given [`RouteDef::id`],
    /// in **declaration order** (pre-order).
    pub fn paths_with_route_id(&self, route_id: &str) -> Vec<NodePath> {
        self.by_path
            .values()
            .filter(|i| i.route_id.as_deref() == Some(route_id))
            .map(|i| i.path.clone())
            .collect()
    }

    /// Match a concrete URL (`/detail/123`) against the route **patterns**
    /// (`/(home)/detail/:id`), returning the matched route's id and the
    /// captured `:param` values. Returns `None` if no route matches.
    ///
    /// An unqualified input matches public patterns, from which route groups
    /// are omitted. An input containing a group qualifier matches qualified
    /// patterns exactly. Thus `/detail/42` can yield several placements,
    /// while `/(home)/detail/42` names only the Home placement.
    pub fn match_url(&self, url: &str) -> Option<(String, BTreeMap<String, String>)> {
        let pathname = destination_pathname(url);
        let qualified = contains_group_segment(pathname);
        let input: Vec<&str> = pathname.split('/').filter(|s| !s.is_empty()).collect();
        for info in self.by_path.values() {
            let pattern = if qualified {
                info.qualified_url.as_deref()
            } else {
                info.url.as_deref()
            };
            let (Some(pattern), Some(route_id)) = (pattern, info.route_id.as_deref()) else {
                continue;
            };
            let pat: Vec<&str> = pattern.split('/').filter(|s| !s.is_empty()).collect();
            if let Some(params) = match_segments(&pat, &input) {
                return Some((route_id.to_string(), params));
            }
        }
        None
    }

    /// All [`NodePath`]s whose public or qualified route URL matches `url`,
    /// in declaration order.
    pub fn paths_matching_url(&self, url: &str) -> Vec<NodePath> {
        self.route_matches(url)
            .into_iter()
            .map(|matched| matched.path)
            .collect()
    }

    /// All leaf-route matches for `url`, retaining each placement's own
    /// captured parameters. Qualified destinations match qualified patterns
    /// exactly; unqualified destinations match public patterns.
    pub(crate) fn route_matches(&self, url: &str) -> Vec<RouteMatch> {
        let pathname = destination_pathname(url);
        let qualified = contains_group_segment(pathname);
        let input: Vec<&str> = pathname.split('/').filter(|s| !s.is_empty()).collect();
        self.by_path
            .values()
            .filter_map(|i| {
                // A destination is a navigable **leaf** screen, never a
                // container Route (a `(group)` / layout with children). A
                // group's URL equals its index child's, so without this a bare
                // `/` (or `/(group)`) matches the container too and — being a
                // nearer common ancestor of the current position — gets picked
                // over the index screen inside it.
                if !self.is_leaf_route(&i.path) {
                    return None;
                }
                let pattern = if qualified {
                    i.qualified_url.as_deref()
                } else {
                    i.url.as_deref()
                };
                let pattern = pattern?;
                let pat: Vec<&str> = pattern.split('/').filter(|s| !s.is_empty()).collect();
                match_segments(&pat, &input).map(|params| RouteMatch {
                    path: i.path.clone(),
                    params,
                })
            })
            .collect()
    }

    /// Whether `path` addresses a leaf `Route` (a screen) — a `Route` with no
    /// children, as opposed to a `Stack` / `Switch` / `(group)` container.
    fn is_leaf_route(&self, path: &NodePath) -> bool {
        matches!(self.node_at(path), Some(RouteTree::Route(_, kids)) if kids.is_empty())
    }

    /// **Container** Routes (a `(group)` / layout with children) whose URL
    /// matches `url`. The fallback for a URL that names no leaf screen — e.g.
    /// a bare `/(group)` whose group has no index `""` child; the caller
    /// descends the chosen container to its index leaf.
    pub fn container_paths_matching_url(&self, url: &str) -> Vec<NodePath> {
        let pathname = destination_pathname(url);
        let qualified = contains_group_segment(pathname);
        let input: Vec<&str> = pathname.split('/').filter(|s| !s.is_empty()).collect();
        self.by_path
            .values()
            .filter(|i| {
                if self.is_leaf_route(&i.path) {
                    return false;
                }
                let pattern = if qualified {
                    i.qualified_url.as_deref()
                } else {
                    i.url.as_deref()
                };
                let Some(pattern) = pattern else {
                    return false;
                };
                let pat: Vec<&str> = pattern.split('/').filter(|s| !s.is_empty()).collect();
                match_segments(&pat, &input).is_some()
            })
            .map(|i| i.path.clone())
            .collect()
    }

    /// Group containers whose qualified URL exactly matches `url`.
    pub(crate) fn group_paths_matching_url(&self, url: &str) -> Vec<NodePath> {
        let pathname = destination_pathname(url);
        self.by_path
            .values()
            .filter(|info| info.is_group && info.qualified_url.as_deref() == Some(pathname))
            .map(|info| info.path.clone())
            .collect()
    }

    /// All [`NodePath`]s whose `Route` derives the given full URL
    /// (exact match, no group-optional logic), in declaration order.
    pub fn paths_with_url(&self, url: &str) -> Vec<NodePath> {
        self.by_path
            .values()
            .filter(|i| i.url.as_deref() == Some(url))
            .map(|i| i.path.clone())
            .collect()
    }

    /// Iterate every node's metadata in declaration (pre-order) order.
    pub fn iter_infos(&self) -> impl Iterator<Item = &NodeInfo> {
        self.by_path.values()
    }
}

/// One concrete match, kept atomic so params cannot be captured from a
/// different shared-route placement.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct RouteMatch {
    pub path: NodePath,
    pub params: BTreeMap<String, String>,
}

/// Join the static parts of a route segment onto an accumulated URL.
///
/// `:name` dynamic parts are kept as `:name` placeholders in the URL so
/// `post/:id` derives `/post/:id`. A pathless / empty segment leaves the
/// base unchanged (apart from ensuring a leading `/` at the root).
/// Match `input` against one already-selected public or qualified pattern.
/// Group segments in qualified patterns are ordinary literals; public
/// patterns contain no groups. `:name` segments capture.
fn match_segments(pattern: &[&str], input: &[&str]) -> Option<BTreeMap<String, String>> {
    let mut params = BTreeMap::new();
    if pattern.len() != input.len() {
        return None;
    }
    for (pattern_segment, input_segment) in pattern.iter().zip(input) {
        if let Some(name) = pattern_segment.strip_prefix(':') {
            params.insert(name.to_string(), (*input_segment).to_string());
        } else if pattern_segment != input_segment {
            return None;
        }
    }
    Some(params)
}

fn join_url(base: &str, segment: &str) -> String {
    // Build from the segment's own parts, preserving order and :params.
    let seg_parts: Vec<&str> = segment.split('/').filter(|p| !p.is_empty()).collect();

    if seg_parts.is_empty() {
        // Pathless route (e.g. the "" home route). Its URL is the base,
        // normalised to "/" at the root.
        if base.is_empty() {
            return "/".to_string();
        }
        return base.to_string();
    }

    let mut url = if base.is_empty() || base == "/" {
        String::new()
    } else {
        base.to_string()
    };
    for part in seg_parts {
        url.push('/');
        url.push_str(part);
    }
    url
}

fn normalize_root(path: &str) -> String {
    if path.is_empty() {
        "/".to_string()
    } else {
        path.to_string()
    }
}

fn destination_pathname(url: &str) -> &str {
    url.split(['?', '#']).next().unwrap_or(url)
}

fn contains_group_segment(pathname: &str) -> bool {
    pathname
        .split('/')
        .filter(|segment| !segment.is_empty())
        .any(|segment| segment.starts_with('(') && segment.ends_with(')'))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The example app shape: tabs (a Switch) whose two stacks share the
    /// `detail/:id` route.
    fn tree() -> CompiledTree {
        CompiledTree::new(RouteTree::switch(
            SwitchDef::new("tabs", 0),
            vec![
                RouteTree::stack(vec![
                    RouteTree::route("", "home"),
                    RouteTree::route("detail/:id", "detail"),
                ]),
                RouteTree::stack(vec![
                    RouteTree::route("list", "list"),
                    RouteTree::route("detail/:id", "detail"),
                ]),
            ],
        ))
    }

    #[test]
    fn match_url_index_literal_and_param() {
        let t = tree();
        assert_eq!(t.match_url("/").map(|(id, _)| id), Some("home".into()));
        assert_eq!(t.match_url("/list").map(|(id, _)| id), Some("list".into()));
        let (id, params) = t.match_url("/detail/123").expect("matches detail/:id");
        assert_eq!(id, "detail");
        assert_eq!(params.get("id").map(String::as_str), Some("123"));
    }

    #[test]
    fn match_url_no_match_and_arity() {
        let t = tree();
        assert!(t.match_url("/nope").is_none());
        assert!(t.match_url("/detail/123/extra").is_none());
        assert!(t.match_url("/detail").is_none());
    }

    /// The example app shape with group routes (expo-router style):
    /// Route(TabsLayout) { Switch { Route("(home)") { Stack { ... } } } }
    fn grouped_tree() -> CompiledTree {
        CompiledTree::new(RouteTree::route_with(
            RouteDef {
                id: "tabs_layout".into(),
                segment: None,
                params: vec![],
                component: Some("tabs_layout".into()),
                is_group: false,
            },
            vec![RouteTree::switch(
                SwitchDef::new("tabs", 0),
                vec![
                    RouteTree::route_with(
                        RouteDef {
                            id: "(home)".into(),
                            segment: Some("(home)".into()),
                            params: vec![],
                            component: None,
                            is_group: true,
                        },
                        vec![RouteTree::stack(vec![
                            RouteTree::route("", "home"),
                            RouteTree::route("detail/:id", "detail"),
                        ])],
                    ),
                    RouteTree::route_with(
                        RouteDef {
                            id: "(search)".into(),
                            segment: Some("(search)".into()),
                            params: vec![],
                            component: None,
                            is_group: true,
                        },
                        vec![RouteTree::stack(vec![
                            RouteTree::route("list", "list"),
                            RouteTree::route("detail/:id", "detail"),
                        ])],
                    ),
                ],
            )],
        ))
    }

    #[test]
    fn grouped_url_derivation() {
        let t = grouped_tree();
        let urls: Vec<_> = t
            .iter_infos()
            .filter_map(|i| Some((i.route_id.as_deref()?, i.url.as_deref()?)))
            .collect();
        assert!(urls.contains(&("(home)", "/")));
        assert!(urls.contains(&("(search)", "/")));
        let home_url = urls.iter().find(|(id, _)| *id == "home").map(|(_, u)| *u);
        assert_eq!(home_url, Some("/"));
        let list_url = urls.iter().find(|(id, _)| *id == "list").map(|(_, u)| *u);
        assert_eq!(list_url, Some("/list"));
        assert_eq!(
            t.qualified_url_of(&NodePath(vec![0, 1, 0, 0])).as_deref(),
            Some("/(search)/list")
        );
    }

    #[test]
    fn grouped_match_url() {
        let t = grouped_tree();
        assert_eq!(
            t.match_url("/(home)").map(|(id, _)| id),
            Some("(home)".into())
        );
        assert_eq!(
            t.match_url("/(search)").map(|(id, _)| id),
            Some("(search)".into())
        );
        let r = t.match_url("/detail/42");
        assert!(r.is_some(), "'/detail/42' should match with group skipped");
        let (id, params) = r.unwrap();
        assert_eq!(id, "detail");
        assert_eq!(params.get("id").map(String::as_str), Some("42"));
        let r = t.match_url("/(home)/detail/7");
        assert!(r.is_some(), "'/(home)/detail/7' should match");
        assert!(t.match_url("/").is_some());
    }
}
