{
  "formatVersion": "1.1",
  "component": {
    "group": "rs.whisker",
    "module": "whisker-module-android",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "rs.whisker",
          "module": "lynx-android",
          "version": {
            "requires": "3.8.0-whisker.12"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-base-android",
          "version": {
            "requires": "3.8.0-whisker.12"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-trace-android",
          "version": {
            "requires": "3.8.0-whisker.12"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-service-api-android",
          "version": {
            "requires": "3.8.0-whisker.12"
          }
        },
        {
          "group": "org.lynxsdk.lynx",
          "module": "primjs",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-module-android-0.1.5.aar",
          "url": "whisker-module-android-0.1.5.aar",
          "size": 75190,
          "sha512": "dae02ead0a21092158f4526ac0b2b951037a3f42e7923d142bd6976626ff0025cadf8af451323b536d03cbe2b31645226851879931b2bf650e6f85d09e659ba2",
          "sha256": "29996d71a211706b028fd3912e11fdc2b9caebbdee182eba2c2b4fbd0a2287ad",
          "sha1": "ce75cb7d632ce82471655267383e010cca65e416",
          "md5": "69051d62cff6c44023a47fdd9bc044cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "rs.whisker",
          "module": "lynx-android",
          "version": {
            "requires": "3.8.0-whisker.12"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-base-android",
          "version": {
            "requires": "3.8.0-whisker.12"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-trace-android",
          "version": {
            "requires": "3.8.0-whisker.12"
          }
        },
        {
          "group": "rs.whisker",
          "module": "lynx-service-api-android",
          "version": {
            "requires": "3.8.0-whisker.12"
          }
        },
        {
          "group": "org.lynxsdk.lynx",
          "module": "primjs",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "whisker-module-android-0.1.5.aar",
          "url": "whisker-module-android-0.1.5.aar",
          "size": 75190,
          "sha512": "dae02ead0a21092158f4526ac0b2b951037a3f42e7923d142bd6976626ff0025cadf8af451323b536d03cbe2b31645226851879931b2bf650e6f85d09e659ba2",
          "sha256": "29996d71a211706b028fd3912e11fdc2b9caebbdee182eba2c2b4fbd0a2287ad",
          "sha1": "ce75cb7d632ce82471655267383e010cca65e416",
          "md5": "69051d62cff6c44023a47fdd9bc044cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-module-android-0.1.5-sources.jar",
          "url": "whisker-module-android-0.1.5-sources.jar",
          "size": 22841,
          "sha512": "fda4ff3ecdea5ae829eba8e4965f02362999a245aa4c3191523d035251f15e6b6762004ba9132359cc568b4623eeff7ea33475dbd8ad04512d5b97e275cb1154",
          "sha256": "686e4e9f36eecddd184761a9542df7968765c70a0a90fa501019c55d3942ad78",
          "sha1": "b5fb0455a04e8af315e085afeb60f96a0a33662e",
          "md5": "636f330c1a81506155eb602780410bc7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "whisker-module-android-0.1.5-javadoc.jar",
          "url": "whisker-module-android-0.1.5-javadoc.jar",
          "size": 419244,
          "sha512": "4ff4d389eda3f9e0b5ba991c10685c946659fb841e0bd14ba3a8236e5ff5ae08a3a6feb112a5a8cf000d3c22e69b27e3951bd36fa47c00b63837e2c74df9842f",
          "sha256": "6baecb7393b1d42e97311671ac82bc115cd6fb27cf5f94e3bc4a221d619c439d",
          "sha1": "947bec777727f51d5c6deb542c2b5c9fb72f8792",
          "md5": "2a05799accd5044c01371a2a3cff9937"
        }
      ]
    }
  ]
}
