package {{android_application_id}}

import android.content.Intent
import android.os.Bundle
import androidx.activity.ComponentActivity
import rs.whisker.runtime.WhiskerAppContext
import rs.whisker.runtime.WhiskerView{{main_activity_imports}}
import rs.whisker.runtime.WhiskerWindow
import rs.whisker.runtime.generated.WhiskerModuleBehaviors

/**
 * Native Host composition root generated by whisker-cng.
 */
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
{{main_activity_pre_super}}        super.onCreate(savedInstanceState)

        window.setBackgroundDrawableResource(R.color.whisker_background)
        WhiskerWindow.enableEdgeToEdge(this)
        System.loadLibrary("{{rust_lib_name}}")
        WhiskerModuleBehaviors.registerAll()
        setContentView(WhiskerView(this))
        dispatchDeepLink(intent)
{{main_activity_post_super}}    }

    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        setIntent(intent)
        dispatchDeepLink(intent)
    }

    private fun dispatchDeepLink(intent: Intent) {
        intent.dataString?.let(WhiskerAppContext::dispatchDeepLink)
    }
}
