// Macro implementation for `@WhiskerElement("x-tag")` +
// `@WhiskerModule("Name")`.
//
// `@WhiskerElement` keeps the v1 shape — emits an `@objc` static
// `__whiskerElementTag` constant on the annotated `LynxUI<View>`
// subclass; behaviour registration itself is generated by the
// `WhiskerElementsCodegen` SwiftPM build-tool plugin from the
// annotation discovery.
//
// `@WhiskerModule` (Phase 7-Φ.F) is a peer-emission macro that
// expands into a top-level `@_cdecl` C dispatch shim:
//
//   ```swift
//   @WhiskerModule("WhiskerLocalStore")
//   public class WhiskerLocalStoreImpl {
//       func save(_ args: [WhiskerValue]) -> WhiskerValue { … }
//       func load(_ args: [WhiskerValue]) -> WhiskerValue { … }
//       func remove(_ args: [WhiskerValue]) -> WhiskerValue { … }
//   }
//   ```
//
// expands to (added as a sibling top-level decl in the same file):
//
//   ```swift
//   @_cdecl("_whiskerDispatch_WhiskerLocalStore")
//   public func _whiskerDispatch_WhiskerLocalStore(
//       methodName: UnsafePointer<CChar>?,
//       args: UnsafePointer<WhiskerValueRaw>?,
//       argCount: Int
//   ) -> WhiskerValueRaw {
//       let method = methodName.flatMap { String(cString: $0) } ?? ""
//       let decoded = WhiskerValue.decodeArray(args, count: argCount)
//       let instance = WhiskerLocalStoreImpl()
//       let result: WhiskerValue
//       switch method {
//       case "save":   result = instance.save(decoded)
//       case "load":   result = instance.load(decoded)
//       case "remove": result = instance.remove(decoded)
//       default:
//           result = .error("unknown method \(method) on WhiskerLocalStore")
//       }
//       return result.toRaw()
//   }
//   ```
//
// The C bridge looks the dispatch fn up via the lookup table
// populated by the `WhiskerElementsCodegen`-generated
// `WhiskerModuleBehaviors.registerAll()` call to
// `whisker_bridge_register_module_dispatch("WhiskerLocalStore",
//  _whiskerDispatch_WhiskerLocalStore)` at app launch.

import SwiftCompilerPlugin
import SwiftSyntax
import SwiftSyntaxMacros

/// Compiler plugin entry point. Registers both macros so the Swift
/// compiler picks them up when consumers `import WhiskerElements`.
@main
struct WhiskerElementsPlugin: CompilerPlugin {
    let providingMacros: [Macro.Type] = [
        WhiskerElementMacro.self,
        WhiskerModuleMacro.self,
    ]
}

/// `@WhiskerModule("Name")` — emit the per-module `@_cdecl` C
/// dispatch shim as a peer of the annotated class. The
/// `WhiskerElementsCodegen` SwiftPM plugin discovers the
/// annotation via SwiftSyntax and emits a registration call
/// against `whisker_bridge_register_module_dispatch` pointing at
/// the generated shim.
///
/// The annotated class is expected to declare zero-or-more
/// instance methods of the shape
/// `func name(_ args: [WhiskerValue]) -> WhiskerValue`. The macro
/// emits one `case` per such method into the dispatch switch;
/// methods with other shapes cause a Swift compile error at the
/// call site, which surfaces to the author with the right
/// source-location diagnostic.
public struct WhiskerModuleMacro: PeerMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingPeersOf declaration: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard let moduleName = whiskerModuleFirstStringArgument(of: node) else {
            // Parser ensures the argument exists at the syntactic
            // level — a malformed string-literal expression makes
            // the macro a no-op (the consumer still sees the
            // Swift parser's diagnostic for the malformed source).
            return []
        }
        guard let classDecl = declaration.as(ClassDeclSyntax.self) else {
            // `@WhiskerModule` on non-class decls is meaningless;
            // bail with no output and let Swift's normal type
            // checker surface the mismatch.
            return []
        }
        let className = classDecl.name.text
        let methodNames = discoverInstanceMethods(in: classDecl)
        let dispatchFnName = "_whiskerDispatch_\(sanitiseIdentifier(moduleName))"

        // Build the switch body. With no methods we emit just the
        // default arm — the dispatch fn still resolves to a real
        // symbol (so registration doesn't fail), and every call
        // reports "unknown method" as the error value.
        var switchArms = ""
        for method in methodNames {
            switchArms += """
                case "\(method)":
                    result = instance.\(method)(decoded)

            """
        }

        // The instance lifetime is per-call: the macro doesn't
        // know which methods are stateful, and pulling that into
        // a `static let shared` here would tie module dispatch to
        // class-level state that author code can't override.
        // Module impls that need shared state can stash it in a
        // singleton themselves (matching the Android side, where
        // the KSP processor emits an `object` rather than a
        // `class` instance).
        let body = """
        @_cdecl("\(dispatchFnName)")
        public func \(dispatchFnName)(
            methodName: UnsafePointer<CChar>?,
            argsPtr: UnsafePointer<WhiskerValueRaw>?,
            argCount: Int
        ) -> WhiskerValueRaw {
            let method = methodName == nil ? "" : String(cString: methodName!)
            let decoded = WhiskerValue.decodeArray(argsPtr, count: argCount)
            let instance = \(className)()
            let result: WhiskerValue
            switch method {
        \(switchArms)    default:
                result = .error("unknown method \\(method) on \(moduleName)")
            }
            return result.toRaw()
        }
        """

        return [DeclSyntax(stringLiteral: body)]
    }
}

/// Names of every instance-method declaration in `classDecl`.
/// Excludes `static` / `class` methods (no `self` to dispatch on),
/// `init` / `deinit` (different decl kinds in SwiftSyntax — not
/// `FunctionDeclSyntax`), and `private` methods (intentionally
/// hidden from the module-dispatch surface).
private func discoverInstanceMethods(in classDecl: ClassDeclSyntax) -> [String] {
    var names: [String] = []
    for member in classDecl.memberBlock.members {
        guard let funcDecl = member.decl.as(FunctionDeclSyntax.self) else {
            continue
        }
        var isStatic = false
        var isPrivate = false
        for modifier in funcDecl.modifiers {
            let text = modifier.name.text
            if text == "static" || text == "class" {
                isStatic = true
            }
            if text == "private" || text == "fileprivate" {
                isPrivate = true
            }
        }
        if isStatic || isPrivate { continue }
        names.append(funcDecl.name.text)
    }
    return names
}

/// Make a Swift identifier out of a module name. Replaces any
/// non-`[A-Za-z0-9_]` byte with `_` so the dispatch fn name is
/// always a legal Swift identifier even for hyphenated module
/// names. Identical to the sanitisation
/// `WhiskerElementsCodegen/main.swift` does on the consumer side
/// when emitting the registration call.
private func sanitiseIdentifier(_ raw: String) -> String {
    var out = ""
    out.reserveCapacity(raw.count)
    for char in raw.unicodeScalars {
        if (char.value >= 0x30 && char.value <= 0x39) ||  // 0-9
           (char.value >= 0x41 && char.value <= 0x5A) ||  // A-Z
           (char.value >= 0x61 && char.value <= 0x7A) ||  // a-z
           char.value == 0x5F {                           // _
            out.unicodeScalars.append(char)
        } else {
            out.append("_")
        }
    }
    return out
}

/// First positional string-literal argument of an `@Attr("...")`
/// invocation. Shared shape — `@WhiskerElement(_ tag:)` and
/// `@WhiskerModule(_ name:)` both take exactly one string arg.
private func whiskerModuleFirstStringArgument(of node: AttributeSyntax) -> String? {
    guard
        let arguments = node.arguments?.as(LabeledExprListSyntax.self),
        let firstArg = arguments.first,
        let stringLiteral = firstArg.expression.as(StringLiteralExprSyntax.self),
        stringLiteral.segments.count == 1,
        let firstSegment = stringLiteral.segments.first?.as(StringSegmentSyntax.self)
    else {
        return nil
    }
    return firstSegment.content.text
}

public struct WhiskerElementMacro: MemberMacro, MemberAttributeMacro {
    /// Emits a static `__whiskerElementTag` constant carrying the
    /// tag-name argument. Future build-pipeline introspection
    /// (SwiftSyntax pass during whisker-build sync) reads this to
    /// produce registrations without the manifest detour.
    public static func expansion(
        of node: AttributeSyntax,
        providingMembersOf declaration: some DeclGroupSyntax,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard let tag = tagArgument(of: node) else {
            // Diagnostic is intentionally terse — a user who
            // forgets the tag string gets a Swift parser error
            // before this macro even runs.
            return []
        }
        return [
            // `@objc public static let` so the constant is reachable
            // from Obj-C and SwiftSyntax introspection alike. The
            // identifier is namespaced with the `__whisker` prefix
            // to keep it out of the user's API surface.
            """
            @objc public static let __whiskerElementTag: String = \(literal: tag)
            """
        ]
    }

    /// Adds `@objc` to the annotated class so its Obj-C runtime
    /// name matches the bare Swift class name (no `_TtC...`
    /// mangling). Skipped when the user already wrote `@objc`
    /// themselves — Swift refuses two `@objc` attributes on the
    /// same decl.
    public static func expansion(
        of node: AttributeSyntax,
        attachedTo declaration: some DeclGroupSyntax,
        providingAttributesFor member: some DeclSyntaxProtocol,
        in context: some MacroExpansionContext
    ) throws -> [AttributeSyntax] {
        // `MemberAttributeMacro` is invoked per-member — we don't
        // want to scatter @objc onto every method. Skip everything
        // except returning an empty list here; the @objc-on-class
        // emission happens via the SwiftSyntax `peer`/`extension`
        // role in future iterations if we need it. For now the
        // class still works because LynxUI itself inherits from
        // NSObject — its subclasses are implicitly Obj-C-exposed
        // and the runtime class name matches the bare Swift name.
        []
    }

    private static func tagArgument(of node: AttributeSyntax) -> String? {
        guard
            let arguments = node.arguments?.as(LabeledExprListSyntax.self),
            let firstArg = arguments.first,
            let stringLiteral = firstArg.expression.as(StringLiteralExprSyntax.self),
            stringLiteral.segments.count == 1,
            let firstSegment = stringLiteral.segments.first?.as(StringSegmentSyntax.self)
        else {
            return nil
        }
        return firstSegment.content.text
    }
}
