{
  "formatVersion": "1.1",
  "component": {
    "group": "rs.whisker",
    "module": "ksp",
    "version": "0.1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.16.jar",
          "url": "ksp-0.1.16.jar",
          "size": 11123,
          "sha512": "3aab15db995703fca4e61c3778c8b9cc1429fec183ed7e6b5897bb5b2ef099157709fece9e9762504b1078f708710e5579396c677ae9b70e9f87a887ee3349d1",
          "sha256": "f1a9a393ae81ef81e514e8a0ad451e4c596035658ea33723b51ce80d99823095",
          "sha1": "42790d23e690e3f1400763f7526ce7cd4b8d689b",
          "md5": "1694d5d63a01a447e67d3e0a4b977011"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.0.21-1.0.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ksp-0.1.16.jar",
          "url": "ksp-0.1.16.jar",
          "size": 11123,
          "sha512": "3aab15db995703fca4e61c3778c8b9cc1429fec183ed7e6b5897bb5b2ef099157709fece9e9762504b1078f708710e5579396c677ae9b70e9f87a887ee3349d1",
          "sha256": "f1a9a393ae81ef81e514e8a0ad451e4c596035658ea33723b51ce80d99823095",
          "sha1": "42790d23e690e3f1400763f7526ce7cd4b8d689b",
          "md5": "1694d5d63a01a447e67d3e0a4b977011"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ksp-0.1.16-sources.jar",
          "url": "ksp-0.1.16-sources.jar",
          "size": 5750,
          "sha512": "534623052978a31fddc2ebe56040630923ed85378bc1e2770f371f7756cbeb8db93777ba1cfd16a00b6d46fe15df9f3905c49d7227c538400b366b8c12fe098b",
          "sha256": "ea980d0a6afcf54bf8a2a3ff2df73d8dcf943498a76aea1ffaf0faf82e858e53",
          "sha1": "264608b2a13f33256dd0141da1ae8ba11da856ba",
          "md5": "1ba6eb6379779229346d9d7c1166a357"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ksp-0.1.16-javadoc.jar",
          "url": "ksp-0.1.16-javadoc.jar",
          "size": 261,
          "sha512": "0fbde246b3a2491a15f6a17d446affbadf6fb8dd3ead7daaeaade9018ba4f56f6ffdcad6254ea7b44742a0e62d6963866230cc72621df8566f5c2032e7772854",
          "sha256": "22f8430ddf3191ba33e4bde9d94784638a77deaf6ff3a0e1d46a76bc403d6d77",
          "sha1": "873188c1cf7df1a046f4a01eba41a3579fb8df64",
          "md5": "73d05f1a59114f84d8e2bac48f6be557"
        }
      ]
    }
  ]
}
