//! Built-in control-flow components — `for_each` (keyed list) and
//! `show` (conditional).
//!
//! Both are written exactly as a user-defined control flow would
//! be: regular `#[component]` functions that allocate a *fragment*
//! ([`create_phantom_element`](whisker_runtime::view::create_phantom_element)),
//! install a reactive [`effect`](whisker_runtime::reactive::effect) to
//! diff their input source, and return the fragment. There's no
//! `ControlFlow` trait, no `View::ControlFlow` enum variant, no
//! special path through the surrounding container builder — the
//! `render!` macro treats `ForEach(...)` / `Show(...)` like any
//! other user component (`PropsBuilder` pattern).
//!
//! A user implementing their own control flow follows the same
//! outline:
//!
//! ```ignore
//! use whisker::prelude::*;
//!
//! #[whisker::component]
//! pub fn animated_show(
//!     when: ReadSignal<bool>,
//!     duration_ms: u32,
//!     children: Children,
//! ) -> Element {
//!     let frag = whisker::runtime::view::create_phantom_element();
//!     let mounted: std::rc::Rc<std::cell::RefCell<Option<_>>> =
//!         std::rc::Rc::new(std::cell::RefCell::new(None));
//!     effect(move || {
//!         /* ... mount / unmount under `frag` based on `when.get()` ... */
//!     });
//!     frag
//! }
//! ```
//!
//! The fragment's phantom-hoisting machinery (see
//! [`docs/wrapper-less-control-flow-design.md`](https://github.com/whiskerrs/whisker/blob/main/docs/wrapper-less-control-flow-design.md))
//! routes the mounted children to the nearest non-phantom ancestor
//! in the Lynx tree, so the on-screen DOM is wrapper-less while
//! the user code keeps its hierarchical mental model.

use std::cell::RefCell;
use std::collections::HashMap;
use std::hash::Hash;
use std::rc::Rc;

use whisker_runtime::reactive::{create_owner, dispose_owner, effect, with_owner, OwnerId};
use whisker_runtime::view::{
    append_child, create_phantom_element, remove_child, Children, EachFn, Element, Fallback,
    ItemFn, KeyFn, WhenFn,
};

use crate::component;

// ---------------------------------------------------------------------------
// `for_each` → `ForEach` (PascalCase alias generated by `#[component]`)
// ---------------------------------------------------------------------------

/// Keyed-list control flow. Returns a fragment populated with one
/// element per item; reactive updates re-key against the previous
/// render so survivors keep their per-item owners (and any reactive
/// state inside) intact.
///
/// `each` is the reactive items source (a `Fn() -> Vec<T>` closure
/// wrapped in [`EachFn`] via `Into`). On every dep change the effect
/// recomputes it, derives new keys via `key`, and diffs against the
/// previous frame:
///
///   - kept (same key) → owner + element preserved
///   - new key → fresh owner, `children(item)` runs
///   - missing key → owner disposed, element detached
///
/// Reordering: detach every surviving handle, then re-attach in the
/// new order. The fragment's phantom-hoisting routes each operation
/// to the nearest non-phantom Lynx ancestor.
#[component]
pub fn for_each<T, K>(each: EachFn<T>, key: KeyFn<T, K>, children: ItemFn<T>) -> Element
where
    T: 'static,
    K: Eq + Hash + Clone + 'static,
{
    let frag = create_phantom_element();

    struct Entry {
        owner: OwnerId,
        handle: Element,
    }
    let entries: Rc<RefCell<HashMap<K, Entry>>> = Rc::new(RefCell::new(HashMap::new()));

    // Clone the closure props into the effect's capture set so the
    // outer body (a `FnMut` per `#[component]`'s hot-reload wrapper)
    // never gets them moved out of.
    let each = each.clone();
    let key = key.clone();
    let children = children.clone();

    effect(move || {
        let items = each.call();
        let mut new_entries: HashMap<K, Entry> = HashMap::new();
        let mut new_keys_in_order: Vec<K> = Vec::with_capacity(items.len());

        let mut old = std::mem::take(&mut *entries.borrow_mut());

        for item in items {
            let k = key.call(&item);
            if let Some(existing) = old.remove(&k) {
                new_entries.insert(k.clone(), existing);
            } else {
                let item_owner = create_owner(None);
                let handle = with_owner(item_owner, || {
                    let h = children.call(item);
                    append_child(frag, h);
                    h
                });
                new_entries.insert(
                    k.clone(),
                    Entry {
                        owner: item_owner,
                        handle,
                    },
                );
            }
            new_keys_in_order.push(k);
        }

        // Disappeared items: detach + dispose.
        for (_, entry) in old.drain() {
            remove_child(frag, entry.handle);
            dispose_owner(entry.owner);
        }

        // Reorder: detach every surviving handle, then re-attach in
        // the new order. The fragment's phantom-hoisting routes each
        // detach + re-attach pair to the real ancestor on the Lynx
        // side, one element at a time.
        for k in &new_keys_in_order {
            if let Some(entry) = new_entries.get(k) {
                remove_child(frag, entry.handle);
            }
        }
        for k in &new_keys_in_order {
            if let Some(entry) = new_entries.get(k) {
                append_child(frag, entry.handle);
            }
        }

        *entries.borrow_mut() = new_entries;
    });

    frag
}

// ---------------------------------------------------------------------------
// `show` → `Show` (PascalCase alias generated by `#[component]`)
// ---------------------------------------------------------------------------

/// Conditional control flow. When `when` reads true the `children`
/// closure's element is mounted under the returned fragment; when
/// false, `fallback` (if any) is mounted instead. On every flip the
/// mounted branch's owner is disposed before the other branch is
/// instantiated, so reactive state from the previous branch can't
/// leak.
#[component]
pub fn show(
    when: WhenFn,
    children: Children,
    #[prop(default = ::std::default::Default::default())] fallback: Fallback,
) -> Element {
    let frag = create_phantom_element();

    // Track the currently-mounted (owner, leaf handles) pair so we
    // can dispose + detach on every flip.
    let mounted: Rc<RefCell<Option<(OwnerId, Vec<Element>)>>> = Rc::new(RefCell::new(None));

    // Clone props into the effect's capture set so the outer body
    // (a `FnMut` per `#[component]`'s hot-reload wrapper) never has
    // them moved out of. `Rc<dyn Fn>` clones are cheap.
    let when = when.clone();
    let children = children.clone();
    let fallback = fallback.clone();

    effect(move || {
        // Tear down the previously-mounted branch.
        if let Some((owner, handles)) = mounted.borrow_mut().take() {
            for h in handles {
                remove_child(frag, h);
            }
            dispose_owner(owner);
        }

        let cond = when.call();

        if cond {
            // Truthy branch: `children` is `Children` = `Fn() -> View`.
            let owner = create_owner(None);
            let handles = with_owner(owner, || {
                let view = children();
                view.attach_to(frag)
            });
            *mounted.borrow_mut() = Some((owner, handles));
        } else if let Some(fb) = &fallback.0 {
            // Falsy branch: `fallback` is `Fn() -> Element` (single
            // element). Mount it directly under the fragment.
            let owner = create_owner(None);
            let handle = with_owner(owner, || {
                let h = fb();
                append_child(frag, h);
                h
            });
            *mounted.borrow_mut() = Some((owner, vec![handle]));
        }
    });

    frag
}
