//! Built-in control-flow components — `for_each` (keyed list) and
//! `show` (conditional).
//!
//! Both are written exactly as a user-defined control flow would be:
//! regular `#[component]` functions that allocate a *fragment*
//! ([`create_phantom_element`](whisker_runtime::view::create_phantom_element)),
//! install a reactive [`effect`](whisker_runtime::reactive::effect) to
//! diff their input source, and return the fragment. There is no
//! `ControlFlow` trait and no special path through the surrounding
//! builder — `render!` treats `ForEach(...)` / `Show(...)` like any
//! other user component.
//!
//! A user implementing their own control flow follows the same
//! outline:
//!
//! ```ignore
//! use whisker::prelude::*;
//!
//! #[whisker::component]
//! pub fn animated_show(
//!     when: ReadSignal<bool>,
//!     duration_ms: u32,
//!     children: Children,
//! ) -> Element {
//!     let frag = whisker::runtime::view::create_phantom_element();
//!     let mounted: std::rc::Rc<std::cell::RefCell<Option<_>>> =
//!         std::rc::Rc::new(std::cell::RefCell::new(None));
//!     effect(move || {
//!         /* ... mount / unmount under `frag` based on `when.get()` ... */
//!     });
//!     frag
//! }
//! ```
//!
//! The fragment's phantom-hoisting machinery (see
//! [`docs/wrapper-less-control-flow-design.md`](https://github.com/whiskerrs/whisker/blob/main/docs/wrapper-less-control-flow-design.md))
//! routes the mounted children to the nearest non-phantom ancestor
//! in the Host tree, so the on-screen DOM is wrapper-less while
//! the user code keeps its hierarchical mental model.

use std::cell::{Cell, RefCell};
use std::collections::HashMap;
use std::hash::Hash;
use std::rc::Rc;

use whisker_runtime::reactive::{Owner, effect};
use whisker_runtime::view::{
    Children, EachFn, Element, Fallback, ItemFn, KeyFn, WhenFn, append_child,
    create_phantom_element, remove_child,
};

use crate::component;

// ---------------------------------------------------------------------------
// `for_each` → `ForEach` (PascalCase marker generated by `#[component]`)
// ---------------------------------------------------------------------------

/// Keyed-list control flow. Returns a fragment populated with one
/// element per item; reactive updates re-key against the previous
/// render so survivors keep their per-item owners (and any reactive
/// state inside) intact.
///
/// `each` is the reactive items source (a `Fn() -> Vec<T>` closure
/// wrapped in [`EachFn`] via `Into`). On every dep change the effect
/// recomputes it, derives new keys via `key`, and diffs against the
/// previous frame:
///
///   - kept (same key) → owner + element preserved
///   - new key → fresh owner, `children(item)` runs
///   - missing key → owner disposed, element detached
///
/// Reordering: detach every surviving handle, then re-attach in the
/// new order. The fragment's phantom-hoisting routes each operation
/// to the nearest non-phantom Host ancestor.
#[component]
pub fn for_each<T, K>(each: EachFn<T>, key: KeyFn<T, K>, children: ItemFn<T>) -> Element
where
    T: 'static,
    K: Eq + Hash + Clone + 'static,
{
    let frag = create_phantom_element();

    struct Entry {
        owner: Owner,
        handle: Element,
    }
    let entries: Rc<RefCell<HashMap<K, Entry>>> = Rc::new(RefCell::new(HashMap::new()));

    // The outer body is a `FnMut` (per `#[component]`'s hot-reload
    // wrapper), so the closure props must be cloned in rather than
    // moved out of it.
    let each = each.clone();
    let key = key.clone();
    let children = children.clone();

    effect(move || {
        let items = each.call();
        let mut new_entries: HashMap<K, Entry> = HashMap::new();
        let mut new_keys_in_order: Vec<K> = Vec::with_capacity(items.len());

        let mut old = std::mem::take(&mut *entries.borrow_mut());

        for item in items {
            let k = key.call(&item);
            if let Some(existing) = old.remove(&k) {
                new_entries.insert(k.clone(), existing);
            } else {
                let item_owner = Owner::new(None);
                let handle = item_owner.with(|| {
                    let h = children.call(item);
                    append_child(frag, h);
                    h
                });
                new_entries.insert(
                    k.clone(),
                    Entry {
                        owner: item_owner,
                        handle,
                    },
                );
            }
            new_keys_in_order.push(k);
        }

        for (_, entry) in old.drain() {
            remove_child(frag, entry.handle);
            entry.owner.dispose();
        }

        // Reorder by detaching every surviving handle and re-attaching
        // in the new order; phantom-hoisting routes each pair to the
        // real Host ancestor one element at a time.
        for k in &new_keys_in_order {
            if let Some(entry) = new_entries.get(k) {
                remove_child(frag, entry.handle);
            }
        }
        for k in &new_keys_in_order {
            if let Some(entry) = new_entries.get(k) {
                append_child(frag, entry.handle);
            }
        }

        *entries.borrow_mut() = new_entries;
    });

    frag
}

// ---------------------------------------------------------------------------
// `show` → `Show` (PascalCase marker generated by `#[component]`)
// ---------------------------------------------------------------------------

/// Conditional control flow. When `when` reads true the `children`
/// closure's element is mounted under the returned fragment; when
/// false, `fallback` (if any) is mounted instead. On every flip the
/// mounted branch's owner is disposed before the other branch is
/// instantiated, so reactive state from the previous branch can't
/// leak.
///
/// The branch is rebuilt only when the condition **changes**, not on
/// every dependency change of `when`. `WriteSignal::set` notifies
/// unconditionally (even when the value is unchanged), so an effect
/// keyed on a signal `when` reads would otherwise tear down and
/// re-mount its branch for a no-op write — churning the DOM, disposing
/// the branch's internal reactive state, re-firing its `on_mount`, and
/// (through phantom hoisting) re-anchoring the *following siblings*,
/// which resigns a sibling native input's focus. Tracking the last
/// condition and skipping the rebuild avoids all of that. `when.call()`
/// is still evaluated every run, so the effect's dependency
/// subscription is preserved.
#[component]
pub fn show(
    when: WhenFn,
    children: Children,
    #[prop(default = ::std::default::Default::default())] fallback: Fallback,
) -> Element {
    let frag = create_phantom_element();

    type Mounted = Rc<RefCell<Option<(Owner, Vec<Element>)>>>;
    let mounted: Mounted = Rc::new(RefCell::new(None));
    // The condition the mounted branch reflects; `None` until first run.
    let last_cond: Rc<Cell<Option<bool>>> = Rc::new(Cell::new(None));

    // The outer body is a `FnMut`, so props are cloned in rather than
    // moved out of it. `Rc<dyn Fn>` clones are cheap.
    let when = when.clone();
    let children = children.clone();
    let fallback = fallback.clone();

    effect(move || {
        // Evaluate on every run to keep the dependency subscription,
        // but only rebuild when the condition actually changed.
        let cond = when.call();
        if last_cond.get() == Some(cond) {
            return;
        }
        last_cond.set(Some(cond));

        if let Some((owner, handles)) = mounted.borrow_mut().take() {
            for h in handles {
                remove_child(frag, h);
            }
            owner.dispose();
        }

        if cond {
            let owner = Owner::new(None);
            let handles = owner.with(|| {
                let view = children();
                view.attach_to(frag)
            });
            *mounted.borrow_mut() = Some((owner, handles));
        } else if let Some(fb) = &fallback.0 {
            let owner = Owner::new(None);
            let handle = owner.with(|| {
                let h = fb();
                append_child(frag, h);
                h
            });
            *mounted.borrow_mut() = Some((owner, vec![handle]));
        }
    });

    frag
}
