plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "rs.whisker.runtime"
    compileSdk = 34

    defaultConfig {
        minSdk = 24

        ndk {
            abiFilters += listOf("arm64-v8a")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

// Lynx AARs are produced by `cargo xtask android build-lynx-aar`
// (which patches the upstream Lynx build to export the Element PAPI
// symbols our Rust bridge calls into). They land under
// `target/lynx-android/` and the consuming app's `settings.gradle.kts`
// (generated by whisker-cng) registers that dir as a `flatDir` repo.
// We reference them here by Maven coordinate-style name + extension.
//
// Why not `api(files(.../LynxAndroid.aar))`? AGP 8.x rejects direct
// local .aar file deps when the consuming app does `assembleRelease`
// (which transitively builds this library's AAR): "would produce a
// broken AAR". `flatDir` + `api(name=...)` is the AGP-blessed
// escape hatch and works for both debug and release.
//
// The flatDir lives in `settings.gradle.kts` rather than here because
// the consuming-app `settings.gradle.kts` declares
// `FAIL_ON_PROJECT_REPOS`, which forbids project-level repository
// declarations. Repos must live at the settings level.

dependencies {
    // `api` (not `implementation`) so consuming apps can see LynxView /
    // LynxEnv types that leak through `WhiskerView`'s superclass.
    //
    // `:<name>@aar` is the Kotlin-DSL string form for "no group,
    // this name, this extension" — resolves against the flatDir repo
    // declared in the consuming-app's settings.gradle.kts.
    api(":LynxAndroid@aar")
    api(":LynxBase@aar")
    api(":LynxTrace@aar")
    api(":ServiceAPI@aar")
    api("org.lynxsdk.lynx:primjs:3.7.0")

    implementation("androidx.appcompat:appcompat:1.7.0")
}
